### ISSUE TITLE
Does it work with .NET Core?

### ISSUE THREAD

**Issue by HamedFathi** [aelassas/Wexflow#10]
Hi

I want to know Does **Wexflow** work with .NET Core or not ?

If need any clarification or explanation that would be great :)

**Comment by wilson6** [comment]
use 'inno setup' and .iss file to generate Windows Installtion EXE.

**Comment by HamedFathi** [comment]
@wilson6 

That is not my answer, I want to know WexFlow has any provider for working with .net core applications ?

**Comment by aelassas** [comment]
Hi,
Sorry Wexflow does not support .NET Core.
Regards,
