### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by bakes82** [aelassas/wexflow#10]
Is there a way to group a collection of tasks, IE per client.
Set params per client/profile and inherit thru to jobs.

Examples:
Have N # clients, all clients have the same jobs/tasks, would like to create/copy a collection of tasks IE get files from ftp, call endpoints, etc dont matter what the tasks are per say, but the format for ever flow is the same per client, but maybe each client has a standard set of "config" variables that could be set at a "profile" level so we can say create the "Client Bobs" profile set their account id, ftp credentials, and some other "standard" things that can then be inherited down to each flow.  Then have ability to copy/clone a set of "flows" and they pull the ftp creds from the profile or the accountId etc, but the code for each flow is the same, maybe the trigger time changes from 5min to 20min but the ability to pull the info from the profile is the key.

Multi server processing, due to having multi clients most likely would need to be able to have multi boxes to process.

Can flows be configured to only run 1 instanced, so if job is set to every 5min, but its taking longer than 5min to run, the next occurrence wont run, but on a diff flow it can.

**Comment by janborup** [comment]
Hi Bakes82

Maybe I can answer some of you questions.
As I read you suggestions about different clients, I think this is a combination of using a set of variables to be used in the same task, and then run a task with this set of variables. 
https://github.com/aelassas/wexflow/wiki/Global-Variables
https://github.com/aelassas/wexflow/wiki/Local-Variables
As I know today, there is no posibility to dynamicly read variable-values from a file or SQL-script, and then loop trough each variable set with the same task(s), but that you be a great feature.

>Can flows be configured to only run 1 instanced

On a task you have the "Enable parallel jobs" setting, and if this is checked, you can multi-threded tasks, but if not checked the jobs are just queued up.
https://github.com/aelassas/wexflow/wiki/Get-Started#designer

Best regards
JanBorup

**Comment by anykeypress** [comment]
I have a quick question before I install and try out the application...
I have the following scenario in mind,
1. Query / Gt mails from an account
2. Parse the contents (the body contains json)
3. Based on the contents, fill variables
4. Execute a script to retreive information from other systems and fill variables
5. Base on the varisables / information obtained send an email out based on a template

Would all of the above be possible with this application?

Thx in advance,
Phil
