### ISSUE TITLE
Installation - Dotnet core on windows throw error while running run.bat

### ISSUE THREAD

**Issue by youngsmith1** [aelassas/Wexflow#100]
This happened after fresh installation of wexflow-4.0-windows-dotnet-core. Wexflow wasn't installed on my machine. I followed [this](https://github.com/aelassas/Wexflow/wiki/Installation#windows-net-core) guide and after double clicking on run.bat, it throw error

> Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Wexflow-dotnet-core\Database\Wexflow.db'.

**Comment by youngsmith1** [comment]
Turns out it was expecting Database directory in C:\Wexflow-dotnet-core directory. I created Database folder manually and then again started run.bat and this time around it worked successfully.

@aelassas Seems like install.bat should create this directory.

**Comment by aelassas** [comment]
Yes, this is a bug that I will fix in the version 4.2.

**Comment by aelassas** [comment]
@youngsmith1  I fixed this issue in the [version 4.2](https://github.com/aelassas/Wexflow/releases/tag/v4.2) that I've just released.

Can you test on your side and tell me if it's fixed?

**Comment by aelassas** [comment]
@youngsmith1 Can I close this issue?

**Comment by youngsmith1** [comment]
@aelassas I have tested version 4.2 and is working fine now. Database directory is created this time around. i am closing this issue.
