### ISSUE TITLE
Workflow_MailsSender task with Html body

### ISSUE THREAD

**Issue by youngsmith1** [aelassas/Wexflow#101]
Is there a way to send HTML in email body?

**Comment by aelassas** [comment]
No, at the moment there's no way to send HTML in email body. However, I'll provide this feature in the version 4.2.

**Comment by aelassas** [comment]
@youngsmith1 I added the ability to send the email body as HTML in the version 4.2 that I will release next week (I will notify you when I'll release it).

Here is how it works: To send the email body as HTML, you must use CDATA and set the setting option isBodyHtml to true (defaults to true). Below is an example:

```xml
<Mails>
	<Mail>
		<From>user@host.com</From>
		<To>user@host.com</To>
		<Subject>Wexflow testing</Subject>
		<Body>
		<![CDATA[
			<b>Wexflow testing email body.</b>
			<br/>
			<i>Wexflow testing email body.</i>
		]]>
		</Body>
	</Mail>
</Mails>
```

I hope that this is what you wanted.

**Comment by youngsmith1** [comment]
@aelassas I will test and close this issue once you release 4.2

**Comment by aelassas** [comment]
@youngsmith1 Ok, Thank you.

**Comment by aelassas** [comment]
@youngsmith1 The [version 4.2](https://github.com/aelassas/Wexflow/releases/tag/v4.2) was released. 

Can you test and tell me if the feature regarding HTML email body responds to your needs?

**Comment by zeusmos** [comment]
i have tried the 4.2 version and i get the following error  

2019-08-05 10:25:59,767 ERROR [12] - [TestWF / 1] [MailsSender] An error occured while sending mails.
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Wexflow.Tasks.MailsSender.MailsSender.Run()
2019-08-05 10:25:59,767  INFO [12] - [TestWF / 1] [MailsSender] Task finished.

**Comment by aelassas** [comment]
@zeusmos Can you show me the XML file that contains the emails to load?

**Comment by zeusmos** [comment]
```

<Mails>
	<Mail>
		<From>DoNotReply@xyz.com</From>
		<To>myemailid@gmail.com</To>
		<Subject>Test system Queue has unprocessed docs</Subject>
		<Body>
		<![CDATA[
			<b>Please verify the identified records are valid.</b>
			<br/>
			<i>http://url ...</i>
		]]>
		</Body>
	</Mail>
</Mails>
```

**Comment by aelassas** [comment]
@zeusmos The XML file is valid and has a Root element. I have tested it in the version 4.2 and did not get the error that you've got.

Can you show me your workflow?

**Comment by zeusmos** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<Workflow id="123" name="TestWF" description="Monitors Archive Queue" xmlns="urn:wexflow-schema">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
    <Setting name="period" value="00.00:00:00" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="1" name="SqlToCsv" description="execute sql check for unprocessed docs" enabled="true">
      <Setting name="connectionString" value="con string" />
      <Setting name="sql" value="sql query" />
      <Setting name="type" value="sqlserver" />
    </Task>
    <Task id="2" name="FilesMover" description="Moving csv files from temp folder" enabled="true">
      <Setting name="destFolder" value="C:\WexflowTesting\SqlToCsv\toarchive" />
      <Setting name="selectFiles" value="1" />
    </Task>
    <Task id="3" name="FilesLoader" description="Load mail info" enabled="true">
      <Setting name="file" value="C:\WexflowTesting\Mails\toarchive\mails.xml" />
      <Setting name="folder" value="C:\WexflowTesting\SqlToCsv\Archive" />
    </Task>
    <Task id="4" name="MailsSender" description="send mail" enabled="true">
      <Setting name="enableSsl" value="true" />
      <Setting name="host" value="smtp.gmail.com" />
      <Setting name="password" value="pwd" />
      <Setting name="port" value="587" />
      <Setting name="selectAttachments" value="3" />
      <Setting name="user" value="myemail@gmail.com" />
      <Setting name="selectFiles" value="3" />
    </Task>
  </Tasks>
</Workflow>
```

also the wf has sqltocsv task. seams couple of things should be corrected ? 
1. if the result is empty the file should not be created
2. the results in csv file should be column wise generated

**Comment by aelassas** [comment]
@zeusmos Why do you load files from Archive folder in the third task into the MailsSender task:

```xml
 <Setting name="folder" value="C:\WexflowTesting\SqlToCsv\Archive" />
```

Maybe there is an invalid XML file in Archive folder.

Can you try loading only the file that you show me:

```xml
    <Task id="3" name="FilesLoader" description="Load mail info" enabled="true">
      <Setting name="file" value="C:\WexflowTesting\Mails\TheFileThatYouShowMe.xml" />
    </Task>

    <Task id="4" name="MailsSender" description="send mail" enabled="true">
      <Setting name="enableSsl" value="true" />
      <Setting name="host" value="smtp.gmail.com" />
      <Setting name="password" value="pwd" />
      <Setting name="port" value="587" />
      <Setting name="selectAttachments" value="3" />
      <Setting name="user" value="myemail@gmail.com" />
      <Setting name="selectFiles" value="3" />
    </Task>
```

**Comment by zeusmos** [comment]
trying to keep in structured so only specific wf can use this mail format other wf will use other folder mail format and there is only one xml file in the folder

yes i can load this file

```
<Mails>
	<Mail>
		<From>DoNotReply@xyz.com</From>
		<To>myemailid@gmail.com</To>
		<Subject>Test system Queue has unprocessed docs</Subject>
		<Body>
		<![CDATA[
			<b>Please verify the identified records are valid.</b>
			<br/>
			<i>http://url ...</i>
		]]>
		</Body>
	</Mail>
</Mails>
```

**Comment by aelassas** [comment]
@zeusmos When you load that file, do you get the error?

**Comment by zeusmos** [comment]
no

**Comment by aelassas** [comment]
@zeusmos  Ok, so this issue seams to be solved. right?

I think that maybe an invalid XML file was loaded in MailsSender task. That's why you got that error.

**Comment by zeusmos** [comment]
when I debugged the code the fileloader was the problem since i have include the mail and attachment as well on one task 3 and when the mail task was running it was first picking up the generated csv file causing the issue.
 
the mails file should be part of the MailsSender don't you think?

and can you also please answer my other question posted earlier?

**Comment by aelassas** [comment]
@zeusmos If you want to add files as attachements, you have to use the setting option **selectAttachments** in MailsSender task.

Here is an example:

```xml
<Workflow xmlns="urn:wexflow-schema" id="9" name="Workflow_MailsSender" description="Workflow_MailsSender">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
	</Settings>
	<Tasks>
		<Task id="1" name="FilesLoader" description="Loading mails" enabled="true">
			<Setting name="file" value="C:\WexflowTesting\Mails\mails.xml" />
		</Task>
		<Task id="2" name="FilesLoader" description="Loading attachments" enabled="true">
			<Setting name="file" value="C:\WexflowTesting\file1.txt" />
		</Task>
		<Task id="3" name="MailsSender" description="Sending mails" enabled="true">
			<Setting name="selectFiles" value="1" />
			<Setting name="selectAttachments" value="2" />
			<Setting name="host" value="smtp.gmail.com" />
			<Setting name="port" value="587" />
			<Setting name="enableSsl" value="true" />
			<Setting name="user" value="username" />
			<Setting name="password" value="password" />
		</Task>
	</Tasks>
</Workflow>
```

And which question are you talking about?

**Comment by zeusmos** [comment]
correct, what i am trying to say is the emails mails task should be part of the MailSender task or change the filename **selectFiles** to mailConfigfile or something in MailsSender task.


and the other question i have is in the wf has sqltocsv task.
1. if the result is empty the file should not be created.
2. the results in csv file should be column wise generated

**Comment by aelassas** [comment]
@zeusmos  Ok, I understand what you want in MailsSender task. But for now, I will let the selectFiles setting option since I've been using this since the version 1.0.

Regarding the SqlToCsv task, I'll add an option to not generate the file if it's empty in the version 4.3 that I'll try to release next week.

And regarding column wise generated CSVs, can you show an example?

**Comment by zeusmos** [comment]
instead of semicolon please put comma. 

eg:-
header1,header2,header3
value1,value2,value3
value1,value2,value3

then opening in xls will show in column wise

**Comment by aelassas** [comment]
Ok, but you can change the separator through **separator** setting option in the task:

```xml
<Setting name="separator" value="," />
```

Should give you column wise CSVs. right?

**Comment by zeusmos** [comment]
ah, i see i didn't knew that since the new settings on sqltocsv shows only 4 types that i can select

**Comment by aelassas** [comment]
@youngsmith1 Can I close this issue?

**Comment by youngsmith1** [comment]
@aelassas Sorry i was away for couple of days.
I have tested this, it is working fine.

Thank you
