### ISSUE TITLE
Hosting .net core in IIS

### ISSUE THREAD

**Issue by youngsmith1** [aelassas/Wexflow#102]
Is there a way to host .net core server in IIS. Instead of running run.bat every time i want to host .net core package in IIS.

Any document or tutorial will help.

**Comment by aelassas** [comment]
Wexflow .net core cannot be hosted on IIS. However, there are multiple solutions:
- Use Windows task scheduler to auto start Wexflow .net core automatically after boot.
- Use Topshelf and create a windows service but if I do this some tasks in the version 4.2 (YouTube tasks) won't be available in the .net core version.
- For Linux, you can use upstart or similar tools to auto start Wexflow automatically after boot.
- For macOS, you can follow this [tutorial](https://www.idownloadblog.com/2015/03/24/apps-launch-system-startup-mac/).

**Comment by youngsmith1** [comment]
This makes sense. I am closing this question.
