### ISSUE TITLE
flowchart Workflow (If/While/Switch)

### ISSUE THREAD

**Issue by zeusmos** [aelassas/Wexflow#104]
i am i missing something? i cant find the task  (If/While/Switch)

**Comment by aelassas** [comment]
@zeusmos You can declare If/While/Switch in the execution graph of the workflow. There is no task If/While/Switch. Check out the [documentation](https://github.com/aelassas/Wexflow/wiki/Samples#flowchart-workflows) to see how to create flowchart workflows.

**Comment by zeusmos** [comment]
thanks

**Comment by zeusmos** [comment]
can you show me an example if file exist send email else not ?
