### ISSUE TITLE
execute exe file task ?

### ISSUE THREAD

**Issue by zeusmos** [aelassas/Wexflow#106]
do you have an run exe file task ?

**Comment by aelassas** [comment]
Yes, [ProcessLauncher](https://github.com/aelassas/Wexflow/wiki/ProcessLauncher) task.

**Comment by zeusmos** [comment]
i have a simple wf to run the exe file. the output from exe is a status of 0 or 1. what is the settings that can capture this status info? based on this information i should be able to send email 

```
<Workflow id="1004" name="ExecuteBatch" description="Executes Batch job" xmlns="urn:wexflow-schema">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
  </Settings>
  <LocalVariables />
  <Tasks>
      <Task id="1" name="ProcessLauncher" description="run batch" enabled="true">
	    <Setting name="processPath" value="C:\WexflowTesting\ProcessLauncher\BatchExecute.exe" />
            <Setting name="generatesFiles" value="false" />
            <Setting name="hideGui" value="true" />
	</Task>
  </Tasks>
</Workflow>
```

**Comment by aelassas** [comment]
You can write the output of your exe in a file by using >. But unfortunatly, there's no way to send an email depending on the content of that file in Wexflow yet. However, if you can change your exe to create a file or not then you can use FileExists or FileMatch with MailsSender task.

**Comment by aelassas** [comment]
@zeusmos If I create a new flowchart task FileContentMatch which takes as input a file and a regex, and returns true if the text of the file matches the regex. False, otherwise. I think that you would be able to run MailsSender depending on the output of your exe if you redirect the output of your exe to a file through >.

**Comment by zeusmos** [comment]
Yes, if I implement the exe to write a file then I can make it work should be easy. And thanks for suggestion on what task to use.
