### ISSUE TITLE
http* tasks for older asmx services?

### ISSUE THREAD

**Issue by zeusmos** [aelassas/Wexflow#107]
any plans to support older webservice asmx in wexflow http* tasks?

**Comment by aelassas** [comment]
Can you give me an example to understand how to implement this in Wexflow?

**Comment by zeusmos** [comment]
any traditional .net webservices

the reason i am looking for this option is there are many older ERP that can communicate with the traditional services.

**Comment by zeusmos** [comment]
i have utilized to use custom task for this functionality.
