### ISSUE TITLE
If we're already using a NoSQL DB, can WexFlow use this instead of LiteDB?

### ISSUE THREAD

**Issue by stanspotts** [aelassas/Wexflow#108]
As the title asks. We're using Cosmos DB, and another group is using Mongo DB. Can these be used instead of LiteDB? How modular is the storage code?

**Comment by aelassas** [comment]
At the moment it is not possible to use another NoSQL DB other than LiteDB. Maybe in a future version I'll update the DB mechanism to use other DBs by implementing a plugin based architecture.

**Comment by aelassas** [comment]
@stanspotts, @melf I am working on MongoDB database layer. It will be part of the release v4.7 that I plan to release next week. There will be to possible database options LiteDB and MongoDB. LiteDB will be the default one since it needs zero configuration and MongoDB will be possible after a little bit of configuration that I will document in the wiki.

**Comment by melf** [comment]
Thank you for the prompt response, I'm looking forward to that. I would also love to contribute to the documentation.

**Comment by aelassas** [comment]
@melf I've already started working on MongoDB's [documentation](https://github.com/aelassas/Wexflow/wiki/MongoDB). Can you read it and tell me how you find it? I finished MongoDB database and RavenDB database. Now, I am working on CosmosDB database. Wexflow will give the user the choice of MongoDB, CosmosDB, RavenDB, LiteDB and maybe Cassandra.

**Comment by melf** [comment]
@aelassas The documentation looks great. Thank you for the great work.

**Comment by aelassas** [comment]
@stanspotts, @melf I have just published the [version 4.7](https://github.com/aelassas/Wexflow/releases/tag/v4.7) which includes [CosmosDB](https://github.com/aelassas/Wexflow/wiki/CosmosDB) and [MangoDB](https://github.com/aelassas/Wexflow/wiki/MongoDB) support. As well as [RavenDB](https://github.com/aelassas/Wexflow/wiki/RavenDB) support and a new [command line client](https://github.com/aelassas/Wexflow/wiki/Command-line-client).

**Comment by aelassas** [comment]
CosmosDB and MongoDB are now supported.
