### ISSUE TITLE
Connecting input/output between steps, across flow 

### ISSUE THREAD

**Issue by jakenuts** [aelassas/Wexflow#11]
I may be missing something, but it appears that all the variables are coded into XML and state in the workflow relies on external stores (files go in a folder, folder is used again later). It would be great to find some way to define the inputs & outputs of a task in a way that they can be bound to other tasks. I'm always hoping to find a sweet spot between totally dynamic state & something that can be statically verified so inputs & outputs & tasks can be reused for slightly different flows. Not sure that spot exists tho..

**Comment by aelassas** [comment]
I updated the documentation regarding selectFiles and selectEntities.

See the section "How tasks communicate between each other?" [here](https://github.com/aelassas/Wexflow/wiki/Usage#general).

**Comment by HaMster21** [comment]
Great 👍 
This is one of the concepts I found out way too late and I think it should be one of the first things to explain, right after what workflows are and how tasks are used
