### ISSUE TITLE
How to trigger Job execution from Command Line?

### ISSUE THREAD

**Issue by kevalkothari** [aelassas/Wexflow#113]
Hi Guys,

I am new to Wexflow and I am trying to find way to execute Job/Workflow from Command line  and want to make it such a way so Command line (.bat) file do not execute next job until the Wexflow completes it's execution on command line.

Is it possible?

Thanks,
Keval

**Comment by aelassas** [comment]
You can use curl POST request to execute a workflow: http://localhost:8000/wexflow/start/{id}

You can get the status of the job by using curl GET request: http://localhost:8000/wexflow/workflow/{id}

If the workflow is running, IsRunning attribute will be true.

See [RESTful API](https://github.com/aelassas/Wexflow/wiki/RESTful-API) for more information.

**Comment by kevalkothari** [comment]
Hi aelassas,

Any plan to add command line execution support for it? It's very useful to command line so this can be used with other ETL process as command line step.

Thanks,
Keval

**Comment by aelassas** [comment]
@kevalkothari I will create a command line tool to execute a job, to get status of a job and for other basic operations in a future version. I will notify you once it's done.

**Comment by aelassas** [comment]
@kevalkothari I have just published the [version 4.7](https://github.com/aelassas/Wexflow/releases/tag/v4.7) which includes a [command line client](https://github.com/aelassas/Wexflow/wiki/Command-line-client). Through this client, you can create a batch that triggers a job and waits until the job finishes (see the examples in the documentation).

**Comment by kevalkothari** [comment]
Hi @aelassas  That's fantastic news. Thanks for making change so fast. I will play with it today. 
- One more suggestion to make it more dynamic is to allows job to take arguments from Command line.
So If I created one job and that job reading one file and transforming to  XML  I can pass command line argument path of the file and job can read it from dynamic path.

something like this 
https://help.talend.com/reader/D1cTGvPXH6uoENz7jLetkQ/157aCzI4OnZGD2MYiWiZdA


Thanks,
Keval
