### ISSUE TITLE
Questions: IfCheck, WhileCheck, and SwitchCheck possible in dotnet-core?

### ISSUE THREAD

**Issue by burque505** [aelassas/Wexflow#114]
I have started using the dotnet-core version to be able to use programs with GUIs. It is working great so far. I have noticed the #[pull request for If, While and Switch](https://github.com/aelassas/Wexflow/pulls) for dotnet.

- Is it possible to add the If, While, and Switch commands in the Execution Graph section of a workflow in the dotnet-core version also, and if so can it be done directly in the XML?
- Might those pulls from @atimhome be added to the dotnet-core version? I would be happy to provide a (most likely rough) translation of the Mandarin comments in @atimhome's source code if needed.

**Comment by aelassas** [comment]
@burque505 If, While and Switch flowchart nodes are already available in the .NET Core version. See the [documentation](https://github.com/aelassas/Wexflow/wiki/Samples#flowchart-workflows) for further details. You can add them directly in XML.

**Comment by aelassas** [comment]
Now, you can add If, While and Switch in XML and JSON.
