### ISSUE TITLE
Question: Variable Return List

### ISSUE THREAD

**Issue by akleine01** [aelassas/Wexflow#115]
Hello!

is it possible to define a list variable?

I want to create a new task which must return a variable of string.

Is this possible?

A.Kleine

**Comment by aelassas** [comment]
You can write your result in Hashtable property of the task so it can be
accessible to other tasks.

Le mar. 17 sept. 2019 à 10:07, akleine01 <notifications@github.com> a
écrit :

**Comment by akleine01** [comment]
Thats great..
Thanks
