### ISSUE TITLE
Code security issues

### ISSUE THREAD

**Issue by stanspotts** [aelassas/Wexflow#116]
Our security scans and reports from security sites gives Wexflow a very low score. I'm having difficulty getting it approved even for trial purposes.

Here's one report: https://cuckoo.cert.ee/analysis/1191312/summary/

Checkmarx showed these low-high issues:
SC-28 Protection of information at Rest (P1) - 16 issues
SC-4 Information in Share Resources (P1) - 58 issues
SC-5 Denial of Service Protection (P1) - 129 issues
SC-8 Transmission Confidentiality and Integrity (P1) - 79 issues
SC-19 Information Input Validation (P1) - 7 issues
SC-11 Error Handling (P2) - 88 issues
SC-15 Information Output Filtering (P0) - 5 issues

Overall, 26 High, 68 Medium, 367 Low, and 916 Information issues found.

Do you have plans to add static security scanning to your build pipeline and address such issues in any way?

**Comment by aelassas** [comment]
@stanspotts I am using Inno Setup to create the installer of the .NET version of Wexflow. Maybe those issues are related to how I generate the installer of the .NET version. Also, I always check Wexflow packages with Windows Defender before to upload them to GitHub and Windows Defender has never reported a problem or malware threats.
