### ISSUE TITLE
How join a splitted file?

### ISSUE THREAD

**Issue by fabionaspolini** [aelassas/Wexflow#119]
Hi, I splitted file with "FilesSplitter" task, but in another task, I need joiner files with original name, it's possible with some existing task? 

I using dot net core  platform.

**Comment by aelassas** [comment]
You can use [FilesConcat](https://github.com/aelassas/Wexflow/wiki/FilesConcat). And if all the chunks are in a folder, you can use:
```xml
<Task id="1" name="FilesLoader" description="Loading chunks" enabled="true">
	<Setting name="folder" value="YourFolderPath" />
</Task>
```
See [FileLoader](https://github.com/aelassas/Wexflow/wiki/FilesLoader) task for more details.

**Comment by fabionaspolini** [comment]
I had problem with solution because order of FilesLoader task result with a lot of splitted files is not a sequential correct bytes to concatenate and the resulted file name too is problem for me. 
I created "FilesJoiner" task to solve two problems. Pull request number 135.
