### ISSUE TITLE
Discussion - Visual Editor

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [aelassas/wexflow#12]
So, there is a MIT licensed repo here on Github, https://github.com/RobinKa/netprints, with a beautiful editor.

If, say, the automation capabilities of this project were combined with those visuals- I would say- that would make one fantastic product.

**Comment by aelassas** [comment]
The  current visual editor does the job. The only remaining feature is the creation of flowchart workflows from the visual editor. If I decide to add that remaining feature I would move to [@antv/x6](https://github.com/antvis/x6).

**Comment by gmij** [comment]
the [mxgraph ](https://github.com/jgraph/mxgraph) is a good flowchart wokrflows,
