### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ToddForsberg** [aelassas/Wexflow#121]
Error	CS0016	Could not write to output file 'D:\dev\Wexflow\src\src\dotnet-core\Wexflow.Core\Wexflow.Core.xml' -- 'The device is not ready.	Wexflow.Core

![image](https://user-images.githubusercontent.com/37591206/65524839-218ed880-deb4-11e9-9778-430c6038a56a.png)

Error is from this block in Wexflow.Core.csproj

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <DocumentationFile>D:\dev\Wexflow\src\src\dotnet-core\Wexflow.Core\Wexflow.Core.xml</DocumentationFile>
</PropertyGroup>
```

**Comment by aelassas** [comment]
Yes, I understand the error. Just uncheck documentation in project settings
of Wexflow.Core and it should work.

Le mar. 24 sept. 2019 à 16:15, Todd Forsberg <notifications@github.com> a
écrit :

**Comment by ToddForsberg** [comment]
Thanks.
