### ISSUE TITLE
Feature Request - encrypted password fields

### ISSUE THREAD

**Issue by akleine01** [aelassas/Wexflow#123]
One of my favorite request would be encrypted password fields.

This concerns e.g. Mail and FTP task

A.Kleine

**Comment by aelassas** [comment]
@akleine01 I added a field type password to the designer. This feature will be available in the v5.6.

**Comment by aelassas** [comment]
@akleine01 I have just released the [v5.6](https://github.com/aelassas/Wexflow/releases/tag/v5.6).  I added a field type password to the designer.
