### ISSUE TITLE
Wexflow Folder Workflow - Trash Question

### ISSUE THREAD

**Issue by akleine01** [aelassas/Wexflow#124]
In the [wiki ](https://github.com/aelassas/Wexflow/wiki/Usage#general)I found that there are folder workflows and trash

![image](https://user-images.githubusercontent.com/6866078/65748827-17174d80-e105-11e9-91b4-f4f38c168bbd.png)

On my system, I can't find them.
Is this history?

A.Kleine

**Comment by aelassas** [comment]
Workflows and Trash folders are no longer needed since the workflows are stored in the database now. I updated the wiki.
