### ISSUE TITLE
Task to set File Trigger

### ISSUE THREAD

**Issue by akleine01** [aelassas/Wexflow#126]
I would like to see tasks where I can set a file trigger as an option.

This would make the design of the workflow much easier.

For example, check if one or more directories are empty and set a trigger file as result. After that, it was very easy to query.
Or directly when moving, download ftp, etc. set the file trigger if something was done.

Or would that be a paradigm shift?
From writing the xml file to setting a flag directly?

A.Kleine

**Comment by aelassas** [comment]
@akleine01 can you explain what you want? I don't understand your feature request.

**Comment by akleine01** [comment]
I would suggest thats some task can set a file trigger optional.

**Comment by aelassas** [comment]
Do you want some tasks that create optional trigger file? Which tasks?

Le sam. 28 sept. 2019 à 19:02, akleine01 <notifications@github.com> a
écrit :

**Comment by akleine01** [comment]
Yes, I already made some "extented" task for ftp and fileExists.

Last week I made a workflow for GetFromFTP and inform user by mail if any new files.
Although the GetFromFTP Job should only get files by regexpattern.
I ended with 3 workflows and a total of 26 tasks.
With the new extended task I need only one workflow with 8 task.

A.Kleine
