### ISSUE TITLE
iOS device installation

### ISSUE THREAD

**Issue by GraemeWellington** [aelassas/Wexflow#127]
Hi, I downloaded Wexflow 4.8 [wexflow-4.8-windows-x64.exe] and installed on my Windows 10  PC - basic install - no configuration  changes.

I was following the installation guide for installing Wexflow on iOS device [iPhone XR 12.4.1] - local network.

In the 'Configure Wexflow server URL:' the example setting is: http:://aelassas-pc:8000/wexflow/

On my device I tried syntax similar to this but did not work.

I had to add '.local' to the host name as follows: http:://graeme-pc.local:8000/wexflow/

Is this something to do with my network configuration?

**Comment by aelassas** [comment]
Try to put your IP address instead. To get your IP, open a cmd and type
ipconfig.

**Comment by GraemeWellington** [comment]
Hi Akram El Assas

Thanks for the response.

[cid:image001.jpg@01D576D6.C1510910]

I tried using the IP but no success:

http://192.168.132.1:8000/wexflow/      ; Failed to Connect
http://192.168.132.1/wexflow/                 ; Failed to Connect
http://graeme-pc.local:8000/wexflow/  ; Successfully Connected

I read that because it is an Apple device [iPhone] it requires the ‘.local’ appended to the host name.

Regards

Graeme Wellington
Pro-Time Building Solutions Pty Ltd
178 Martin Road WALL FLAT SA 5254
Mobile: 0419 808 473
Email: graeme.wellington@ptbuildingsolutions.com.au<mailto:graeme.wellington@ptbuildingsolutions.com.au>

[PTBSX-Logo]

**Comment by aelassas** [comment]
Now, it's working?

Also, the port 8000 must be open in the firewall.

**Comment by GraemeWellington** [comment]
I originally had port 8000 open in firewall.

Yes it is working with this setting on the iPhone:                 http://graeme-pc.local:8000/wexflow/

Appending ‘.local’ to the host name made it work - I will investigate further using IP.

Thanks for your help.

Regards

Graeme Wellington
Pro-Time Building Solutions Pty Ltd
178 Martin Road WALL FLAT SA 5254
Mobile: 0419 808 473
Email: graeme.wellington@ptbuildingsolutions.com.au<mailto:graeme.wellington@ptbuildingsolutions.com.au>

[PTBSX-Logo]

**Comment by aelassas** [comment]
@GraemeWellington Thank you. I will update the documentation.
