### ISSUE TITLE
Email Receiver

### ISSUE THREAD

**Issue by wbasterfield** [aelassas/Wexflow#128]
Hi there,
I cant find the Email Receiver Task on the .net-core version, running on linux.
Any help would be greatly appreciated.

**Comment by aelassas** [comment]
@wbasterfield [MailsReceiver](https://github.com/aelassas/Wexflow/wiki/MailsReceiver) task is not available in the .net core version at the moment. I will add it in the upcoming version 4.9.

**Comment by wbasterfield** [comment]
Many thanks

**Comment by aelassas** [comment]
@wbasterfield I've just released the [v4.9](https://github.com/aelassas/Wexflow/releases/tag/v4.9).
