### ISSUE TITLE
WexFlow Debug Custom Task - Error when ListWorkflow

### ISSUE THREAD

**Issue by akleine01** [aelassas/Wexflow#129]
I follow the instruction for debugging.

The Wexflow Server is runing in Visual Studio 2019.

But if I open the Backend and try to list the workflows I get a nullReferenceException:

![image](https://user-images.githubusercontent.com/6866078/65967704-58d82900-e462-11e9-99d3-6f44ac0192a0.png)

**Comment by aelassas** [comment]
Did you copy the content of [wexflow-4.8-windows-samples.zip](https://github.com/aelassas/Wexflow/releases/download/v4.8/wexflow-4.8-windows-samples.zip) in C:\\?

**Comment by akleine01** [comment]
Yes

**Comment by aelassas** [comment]
This seems to be a problem with your database. Backup your db (C:\Wexflow\Database\Wexflow.db) and copy the database in src\samples\dotnet\Wexflow\Database\Wexflow.db in C:\Wexflow\Database and tell me if this works.

If you added new custom tasks, did you reference them in Wexflow.Server project?

**Comment by akleine01** [comment]
I copy the database from here src\samples\dotnet\Wexflow\Database\Wexflow.db to C:\Wexflow\Database and check the reference of the custom task.
Still the same error.

>>This works:
var ret2 = WexflowWindowsService.WexflowEngine.Workflows.ToList();
No Select No Where on this List works.

**Comment by aelassas** [comment]
Do you have the latest version of the source code?

**Comment by akleine01** [comment]
I guess its a x86 / x64 Problem.
The installation I made was with x64.
This version runs.

**Comment by aelassas** [comment]
@akleine01 I have just tested the latest version of the souce code on GitHub with the latest version of the database in src\samples\dotnet\Wexflow\Database\Wexflow.db but I can't reproduce your error. When you run Wexflow in debug mode, you need to stop Wexflow windows service if Wexflow is installed in the same dev machine.

**Comment by aelassas** [comment]
@akleine01 Ok great. Let me know if you face other issues.
