### ISSUE TITLE
how to pass TaskA's result to TaskB's parameter

### ISSUE THREAD

**Issue by 564064202** [aelassas/Wexflow#13]
how to pass TaskA's result to TaskB's parameter

**Comment by HaMster21** [comment]
This is a question I get a lot from other developers new to Wexflow. There probably needs to be documentation specifically on how to use selectFiles and selectEntities.

**Comment by aelassas** [comment]
Refer to this [issue](https://github.com/aelassas/Wexflow/issues/11).

**Comment by aelassas** [comment]
I updated the documentation regarding selectFiles and selectEntities.

See the section "How tasks communicate between each other?" [here](https://github.com/aelassas/Wexflow/wiki/Usage#general).
