### ISSUE TITLE
thread.abort is obsolete, runtime throw PlatformNotSupportedException

### ISSUE THREAD

**Issue by gmij** [aelassas/wexflow#13]
on Core.Workflow.Stop(stopBy) method, using _thread.Abort(), program throw [PlatformNotSupportedException](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0006)

please fixed.

**Comment by aelassas** [comment]
All fixed. Now stop/suspend/resume are supported on the .net core version as well. Check out the[ v7.8](https://github.com/aelassas/wexflow/releases/tag/v7.8).
