### ISSUE TITLE
FileMatch on network shares not working

### ISSUE THREAD

**Issue by tematim** [aelassas/Wexflow#133]
Hello,

I setup Wexflow on a windows server and setup the backend panel in a IIS server.

I try to make a workflow to watch a directory and execute an exe with any file paste in it.

The issue is that the server on my username can read the directory but the task is executed, the access is denied.
I think that maybe IIS user execute the task and rights aren't setup.

Please find my current xml :
`<Workflow id="6" name="FilesMatcherToDo" description="FilesMatcherToDo" xmlns="urn:wexflow-schema">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
    <Setting name="approval" value="false" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="99" name="FileMatch" description="Checking file..." enabled="true">
      <Setting name="dir" value="NetworkPath\InFolder" />
      <Setting name="pattern" value=".*\.xlsx" />
      <Setting name="recursive" value="false" />
    </Task>
    <Task id="1" name="Wait" description="Waiting for 1 seconds..." enabled="true">
      <Setting name="duration" value="00.00:00:01" />
    </Task>
    <Task id="2" name="Wait" description="Waiting for 2 seconds..." enabled="true">
      <Setting name="duration" value="00.00:00:02" />
    </Task>
    <Task id="3" name="ProcessLauncher" description="ToFileCleanup" enabled="true">
      <Setting name="selectFiles" value="1" />
      <Setting name="processPath" value="NetworkPath\DebugTransform.exe" />
      <Setting name="processCmd" value="{$filePath}" />
      <Setting name="hideGui" value="true" />
      <Setting name="generatesFiles" value="false" />
    </Task>
  </Tasks>
  <ExecutionGraph>
    <If id="100" parent="-1" if="99">
      <Do>
        <Task id="1">
          <Parent id="-1" />
        </Task>
      </Do>
      <Else>
        <Task id="2">
          <Parent id="-1" />
        </Task>
      </Else>
    </If>
  </ExecutionGraph>
</Workflow>`

I want to know if it's possible to improve the pattern by not executing the task when the file end by ddMMyyyy.xls as integer like 01011900.xls

Thanks for your help

**Comment by aelassas** [comment]
Are you using the .net version or the .net core version? If you are using the .net version, you have to make sure that Wexflow windows service is running under a user that have access rights to that folder.

Regading  the regex, it should be something like this:

```
.*(0[1-9]|[1-2][0-9]|31(?!(?:0[2469]|11))|30(?!02))(0[1-9]|1[0-2])([12]\d{3})\.xls
```

**Comment by tematim** [comment]
Hello,

I'm using .net version and the service is executed as local user.

I'll setup with a service account and keep you up to date.

Thanks for the regex, I'll change it in my flow.

Regards

**Comment by tematim** [comment]
Hello,
I have some updates, the service is working and the FileMatch task is fired but the task after has issue : 
`<Workflow id="6" name="FilesMatcherToDo" description="FilesMatcherToDo" xmlns="urn:wexflow-schema">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
    <Setting name="approval" value="false" />
  </Settings>
  <LocalVriables />
  <Tasks>
    <Task id="99" name="FileMatch" description="Checking file..." enabled="true">
      <Setting name="dir" value="\\MyNetworkPath" />
      <Setting name="pattern" value=".*(0[1-9]|[1-2][0-9]|31(?!(?:0[2469]|11))|30(?!02))(0[1-9]|1[0-2])([12]\d{3})\.xls" />
      <Setting name="recursive" value="false" />
    </Task>
    <Task id="3" name="ProcessLauncher" description="ToFileCleanup" enabled="true">
      <Setting name="selectFiles" value="1" />
      <Setting name="processPath" value="\\MyNetworkPath\DebugTransform.exe" />
      <Setting name="processCmd" value="{$filePath}" />
      <Setting name="hideGui" value="true" />
      <Setting name="generatesFiles" value="false" />
    </Task>
  </Tasks>
</Workflow>`

But the second task isn't working because the filePath isn't given to the exe software : 
`2019-10-09 15:09:34,428  INFO [5] - [FilesMatcherToDo / 1] Workflow started
2019-10-09 15:09:34,506  INFO [5] - [FilesMatcherToDo / 1] [FileMatch] Checking file...
2019-10-09 15:09:34,600  INFO [5] - [FilesMatcherToDo / 1] [FileMatch] A file matching the pattern .*(0[1-9]|[1-2][0-9]|31(?!(?:0[2469]|11))|30(?!02))(0[1-9]|1[0-2])([12]\d{3})\.xls was found in the directory \\MyNetworkPath -> \\MyNetworkPath\extract_19092019.xlsx.
2019-10-09 15:09:34,600  INFO [5] - [FilesMatcherToDo / 1] [FileMatch] Task finished
2019-10-09 15:09:34,646  INFO [5] - [FilesMatcherToDo / 1] [ProcessLauncher] Launching process...
2019-10-09 15:09:35,396  INFO [23] - [FilesMatcherToDo / 1] [ProcessLauncher] filePath : {$filePath}
2019-10-09 15:09:35,990  INFO [23] - [FilesMatcherToDo / 1] [ProcessLauncher]
2019-10-09 15:09:35,990 ERROR [24] - [FilesMatcherToDo / 1] [ProcessLauncher]
2019-10-09 15:09:36,068  INFO [5] - [FilesMatcherToDo / 1] Workflow finished.`

The filepath line is a Console.WriteLine of args0.

Thanks for your help

**Comment by tematim** [comment]
Hello,

I tried your xml and I need to remove the empty Else condition in order to save the flow in the designer.

The issue still present because the file name isn't send as arguments. My software create a file, so do I need to put the right setting to true ?

Regards

**Comment by aelassas** [comment]
@tematim can I see your logs?

**Comment by tematim** [comment]
Hello,
Please find the logs : 
`2019-10-10 20:53:48,514  INFO [6] - [FilesMatcherToDo / 1] Workflow started.
2019-10-10 20:53:48,529  INFO [6] - [FilesMatcherToDo / 1] [FileMatch] Checking file...
2019-10-10 20:53:48,686  INFO [6] - [FilesMatcherToDo / 1] [FileMatch] A file matching the pattern .*(0[1-9]|[1-2][0-9]|31(?!(?:0[2469]|11))|30(?!02))(0[1-9]|1[0-2])([12]\d{3})\.xls was found in the directory \\RemotePath -> \\RemotePath \extract_19092019.xlsx.
2019-10-10 20:53:48,686  INFO [6] - [FilesMatcherToDo / 1] [FileMatch] Task finished
2019-10-10 20:53:48,686  INFO [6] - [FilesMatcherToDo / 1] [FilesLoader] Loading files...
2019-10-10 20:53:48,686  INFO [6] - [FilesMatcherToDo / 1] [FilesLoader] File loaded: \\RemotePath\extract_19092019.xlsx
2019-10-10 20:53:48,686  INFO [6] - [FilesMatcherToDo / 1] [FilesLoader] Task finished.
2019-10-10 20:53:48,686  INFO [6] - [FilesMatcherToDo / 1] [ProcessLauncher] Launching process...
2019-10-10 20:53:52,149  INFO [4] - [FilesMatcherToDo / 1] [ProcessLauncher] argsValue : --{$filePath}--
2019-10-10 20:55:24,822  INFO [4] - [FilesMatcherToDo / 1] [ProcessLauncher]
2019-10-10 20:55:24,947  INFO [6] - [FilesMatcherToDo / 1] Workflow finished.`

And my code sample :  
`namespace DebugTransformForTest
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length == 1)
            {
                Console.WriteLine("argsValue : --" + args[0] + "--");
            }
        }
    }
}`

Regards

**Comment by aelassas** [comment]
@tematim Try the following workflow with generatesFiles setting set to true:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="urn:wexflow-schema" id="6" name="FilesMatcherToDo" description="FilesMatcherToDo">
   <Settings>
      <Setting name="launchType" value="trigger" />
      <Setting name="enabled" value="true" />
      <Setting name="approval" value="false" />
   </Settings>
   <LocalVriables />
   <Tasks>
      <Task id="99" name="FileMatch" description="Checking file..." enabled="true">
         <Setting name="dir" value="\\MyNetworkPath" />
         <Setting name="pattern" value=".*(0[1-9]|[1-2][0-9]|31(?!(?:0[2469]|11))|30(?!02))(0[1-9]|1[0-2])([12]\d{3})\.xls" />
         <Setting name="recursive" value="false" />
      </Task>
      <Task id="1" name="FilesLoader" description="Loading files" enabled="true">
        <Setting name="folder" value="\\MyNetworkPath" />
	<Setting name="regexPattern" value=".*(0[1-9]|[1-2][0-9]|31(?!(?:0[2469]|11))|30(?!02))(0[1-9]|1[0-2])([12]\d{3})\.xls" />
      </Task>
      <Task id="2" name="ProcessLauncher" description="ToFileCleanup" enabled="true">
         <Setting name="selectFiles" value="1" />
         <Setting name="processPath" value="\\MyNetworkPath\DebugTransform.exe" />
         <Setting name="processCmd" value="{$filePath}" />
         <Setting name="hideGui" value="true" />
         <Setting name="generatesFiles" value="true" />
      </Task>
   </Tasks>
   <ExecutionGraph>
		<If id="100" parent="-1" if="99">
			<Do>
				<Task id="1"><Parent id="-1" /></Task>
				<Task id="2"><Parent id="1" /></Task>
			</Do>
		</If>
	</ExecutionGraph>
</Workflow>
```

**Comment by aelassas** [comment]
Did you set generatesFiles setting to true and saved your workflow?

**Comment by tematim** [comment]
Hello,

If I set to true, I have the exception line 94 from https://github.com/aelassas/Wexflow/blob/master/src/dotnet/Wexflow.Tasks.ProcessLauncher/ProcessLauncher.cs#L94

Regards

**Comment by aelassas** [comment]
@tematim You have to specify the output. Try the following setting:

```xml
<Setting name="processCmd" value="{$filePath} {$output:$fileName}" />
```

**Comment by tematim** [comment]
Hello,
With this settings, I have this logs for the ProcessLauncher task :  

generatesFiles at True
2019-10-16 08:45:52,173  INFO [21] - [FilesMatcherToDo / 2] [ProcessLauncher] Launching process...
2019-10-16 08:45:52,345  INFO [22] - [FilesMatcherToDo / 2] [ProcessLauncher]
2019-10-16 08:45:52,345 ERROR [23] - [FilesMatcherToDo / 2] [ProcessLauncher]
2019-10-16 08:45:52,345  INFO [21] - [FilesMatcherToDo / 2] [ProcessLauncher] Task finished.

generatesFiles at False
2019-10-16 08:46:31,937  INFO [24] - [FilesMatcherToDo / 1] [ProcessLauncher] Launching process...
2019-10-16 08:46:32,109  INFO [25] - [FilesMatcherToDo / 1] [ProcessLauncher]
2019-10-16 08:46:32,109 ERROR [26] - [FilesMatcherToDo / 1] [ProcessLauncher]

Regards

**Comment by aelassas** [comment]
This seems to be working with generatesFiles set to true but you have to change your program because now you have two args (args.Length == 1 should be replaced by args.Length == 2). That's why your output is empty.

**Comment by tematim** [comment]
Hello,

With this change, the path of my file is correct in the logs.

Thanks for your help
