### ISSUE TITLE
Custom Task with dependencies

### ISSUE THREAD

**Issue by formiga90** [aelassas/Wexflow#137]
Is it possible to create a custom task which has dependencies on other libraries and is not self-sufficient?

I created a new task and imported with success but when it tries to run my code I get this exception:

"2019-10-05 21:58:35,492 ERROR [15] - An error occured while running the workflow. Error: {id: 9000, name: Workflow_ProcessTestTask, enabled: True, launchType: Periodic}
System.IO.FileNotFoundException: Could not load file or assembly 'LibSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by aelassas** [comment]
Did you copy all the dependencies of your custom task including LibSharp in C:\Program Files\Wexflow?

**Comment by formiga90** [comment]
Sorry, I did not provide all the information: I am using the dotnet-core version that runs as a console application, I think that what you suggested would be for the version installed as a service, correct?

I did copy all the references into C:\Wexflow-dotnet-core\Tasks\.

**Comment by aelassas** [comment]
Ok, copy the dependencies including the custom task in Wexflow.Server
folder.

**Comment by formiga90** [comment]
I already tried including the LibSharp dll in Wexflow.Server,  but didn't try with both in that folder (the Task I had in the c:\Wexflow(...)\Tasks. Both methods seem to be failing. I still get the FileNotFound exception.

**Comment by aelassas** [comment]
Is there a nuget package of the .net core version of LibSharp?

I think that the .net core version does not support referencing external
dependencies of custom tasks at the moment.

You will have to clone Wexflow's repo, open Wexflow.sln, add your custom
task and reference it in Wexflow.Server project. Finally, to create the
.net core package of Wexflow, run setup/setup-windows-dotnet-core.bat

**Comment by formiga90** [comment]
The problem is solved. For future reference: I fixed it by cloning the repo and adding in the dependencies of Wexflow.Server the nuget package of the dependency that was missing.
