### ISSUE TITLE
Killling a task/workflow

### ISSUE THREAD

**Issue by Mohit1215** [aelassas/Wexflow#139]
Is it possible to kill a workflow if it gets stuck. Like for example: I created a custom task that gives back an error and is unable to complete but the workflow shows status as running and doesn't stop or gives back any error.

**Comment by aelassas** [comment]
@Mohit1215 Are you using the .net version or the .net core version?

**Comment by Mohit1215** [comment]
@aelassas I am using the .Net version.

**Comment by aelassas** [comment]
You can stop the workflow from Manager page by selecting the workflow then
clicking on stop.

Le mer. 9 oct. 2019 à 23:38, Mohit Parkhi <notifications@github.com> a
écrit :

**Comment by Mohit1215** [comment]
It doesn't allow me to do that. The stop button remains frozen.

**Comment by aelassas** [comment]
The status of the workflow (under the buttons) is running?

If the stop button is disabled, this means that the workflow is not running.

Le mer. 9 oct. 2019 à 23:50, Mohit Parkhi <notifications@github.com> a
écrit :

**Comment by Mohit1215** [comment]
I got it. Thank you for helping and quick response!
