### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by msquibb** [aelassas/Wexflow#14]
Is this going to support persisting a workflow to a database or some other structure for long running workflows?

**Comment by HaMster21** [comment]
What is your intention here? The workflow is declared once and executed as its Settings tells it to, so why whould you want to store it anywhere else? Or are you intending to let the Wexflow engine load workflows from elsewhere? Like not in an xml declaration?

**Comment by msquibb** [comment]
Say we have a long running workflow (something that could potentially take weeks to complete, requiring multiple different user interactions), and we have a need to restart the workflow server. Without some sort of persistence, would that particular workflow not be lost and have to restart from the beginning?

**Comment by HaMster21** [comment]
At the moment this is true. How would you model user interaction? And what interaction are we talking about? Wexflow is meant to automate things so you don't need human intervention 😉

**Comment by michael-ye** [comment]
Noticed that this is pretty old, has this feature been added? I think this is pretty essential.

**Comment by aelassas** [comment]
@michael-ye This feature has not been added yet. Workflows are persisted in XML files for the moment. I'll think about this feature in a future version.

**Comment by aelassas** [comment]
@msquibb, @michael-ye, @HaMster21 Workflows are now stored and loaded from DB for better performance. This will be released as part of the upcoming version 4.6. I will notify you once published.

**Comment by michael-ye** [comment]
This is great, thank you!

**Comment by aelassas** [comment]
@msquibb, @michael-ye, @HaMster21 I've just pulished the [v4.6](https://github.com/aelassas/Wexflow/releases/tag/v4.6) in which Workflows are stored in the database for better performance and for more security. Workflows and Trash folders are no longer needed. Check out the release notes for the other features released.
