### ISSUE TITLE
Can we use HTTPGet  for consuming a complex API?

### ISSUE THREAD

**Issue by xcellenceit** [aelassas/Wexflow#141]
I am thinking for a use case where we need to download product details from third party portal using their API, and store the same on SQL server.

Does wexflow is a right solution for this kind of integrations? We need to integrate this, and looking to understand if wexflow is a right tool for this kind of jobs?

**Comment by aelassas** [comment]
Yes, you can use HttpGet task for that. But if you see that it does not respond to your need, you can always create a [custom task](https://github.com/aelassas/Wexflow/wiki/Custom-tasks).

**Comment by xcellenceit** [comment]
Hi, 

Thanks for your quick response. 

Is there any example in public domain of doing something like this?

**Comment by aelassas** [comment]
No, but you can try. If you face any issue, feel free to share your difficulties on this thread.

**Comment by xcellenceit** [comment]
Okay, will try.
