### ISSUE TITLE
Problem in saving workflow from xml using RESTAPI

### ISSUE THREAD

**Issue by Mohit1215** [aelassas/Wexflow#142]
I am trying to save workflow using **http://localhost:8000/wexflow/saveXml** api but get an error and a bad request status code. I am using it in my C# application and trying to save an xml using the above REST api but get an error. I have tried using the api with an existing xml but still gives an error so I don't think the problem is with the xml but with the way of sending the request.

**Comment by Mohit1215** [comment]
I am using PostAsXMLAsync to send the request.

**Comment by aelassas** [comment]
Did you set Authorization header (basic access authentication). Also the XML must be a valid workflow.

Here is a sample payload:

```json
{ 
   "workflowId":1,
   "xml":"<Workflow xmlns=\"urn:wexflow-schema\" id=\"1\" name=\"Workflow_CsvToXml\" description=\"Workflow_CsvToXml\">\r\n  <Settings>\r\n    <Setting name=\"launchType\" value=\"trigger\" /> \r\n    <Setting name=\"enabled\" value=\"true\" />\r\n    <Setting name=\"approval\" value=\"false\" />\r\n  </Settings>\r\n  <LocalVariables />\r\n  <Tasks>\r\n    <Task id=\"1\" name=\"FilesLoader\" description=\"Loading CSVs\" enabled=\"true\">\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv1.csv\" />\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv2.csv\" />\r\n    </Task>\r\n    <Task id=\"2\" name=\"CsvToXml\" description=\"Generating XMl files from CSVs\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"1\" />\r\n    </Task>\r\n    <Task id=\"3\" name=\"FilesMover\" description=\"Moving Xmls to CsvToXml folder\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"2\" />\r\n      <Setting name=\"destFolder\" value=\"C:\\WexflowTesting\\CsvToXml\" />\r\n    </Task>\r\n  </Tasks>\r\n</Workflow>"
}
```

**Comment by Mohit1215** [comment]
So the request has to be in Json format?

**Comment by aelassas** [comment]
Yes.

**Comment by Mohit1215** [comment]
I tried adding authentication header and also the same payload that you mentioned but it returns the status as Bad Request. I am using PostAsJsonAsync method to send the request but it gives me bad request.

**Comment by Mohit1215** [comment]
I can provide you more context by sending the piece of code that I am trying to do.

**Comment by aelassas** [comment]
Try the following code (It's working for me):

```csharp
const string Uri = "http://localhost:8000/wexflow";

public bool SaveWorkflow(string username, string password, string payload)
{
	string uri = Uri + "/saveXml";
	var webClient = new WebClient();
	webClient.Headers.Add("Authorization", Base64Encode(username + ":" + password));
	var response = webClient.UploadString(uri, payload);
	return bool.Parse(response);
}

public static string Base64Encode(string plainText)
{
	var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(plainText);
	return System.Convert.ToBase64String(plainTextBytes);
}
```

You should provide password in md5 checksum format. For exmaple for wexflow2018 password, you should provide the following password ee05eaaba7b76f16e285d983d605c9bf.

I also suggest testing your payload with postman.

**Comment by Mohit1215** [comment]
OK so I tried the exact same code and the request did go through but it gives me false as a response. I tried all the above instructions and even tried changing the workflow id but it gives me false as a response. With my own workflow also it does the same thing and also with a new workflow.

I had tried to do it with Postman also, the response I get is false from the server. What do you think could be the issue then?

**Comment by Mohit1215** [comment]
Sure and thank you so much for helping!

But I used the same payload that you had sent earlier. But I will also share xml that I am using and the final payload string that I am sending in the request

**Comment by Mohit1215** [comment]
`<Workflow id="132" name="demo" description="" xmlns="urn:wexflow-schema">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
    <Setting name="approval" value="false" />
    <Setting name="cronExpression" value="0 43 14 * * ?" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="1" name="GetReport" description="" enabled="true">
      <Setting name="format" value="pdf" />
      <Setting name="reportPath" value="USERGROUPRIGHTS" />
      <Setting name="route" value="api/presets/10000078" />
    </Task>
    <Task id="2" name="FilesLoader" description="" enabled="false">
      <Setting name="folder" value="C:\ProgramData\VPM\Temp" />
    </Task>
  </Tasks>
  <ExecutionGraph>
    <Task id="1">
      <Parent id="-1" />
    </Task>
    <Task id="2">
      <Parent id="1" />
    </Task>
  </ExecutionGraph>
</Workflow>`

**Comment by Mohit1215** [comment]
[workflow.txt](https://github.com/aelassas/Wexflow/files/3740832/workflow.txt)

**Comment by Mohit1215** [comment]
This is the payload string that I used:

> var demoString = "{ \"workflowId\":1,\n\"xml\":\"<Workflow xmlns =\"urn:wexflow-schema\" id=\"1\" name=\"Workflow_CsvToXml\" description=\"Workflow_CsvToXml\">\r\n  <Settings>\r\n    <Setting name=\"launchType\" value=\"trigger\" /> \r\n    <Setting name=\"enabled\" value=\"true\" />\r\n    <Setting name=\"approval\" value=\"false\" />\r\n  </Settings>\r\n  <LocalVariables />\r\n  <Tasks>\r\n    <Task id=\"1\" name=\"FilesLoader\" description=\"Loading CSVs\" enabled=\"true\">\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv1.csv\" />\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv2.csv\" />\r\n    </Task>\r\n    <Task id=\"2\" name=\"CsvToXml\" description=\"Generating XMl files from CSVs\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"1\" />\r\n    </Task>\r\n    <Task id=\"3\" name=\"FilesMover\" description=\"Moving Xmls to CsvToXml folder\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"2\" />\r\n      <Setting name=\"destFolder\" value=\"C:\\WexflowTesting\\CsvToXml\" />\r\n    </Task>\r\n  </Tasks>\r\n</Workflow>\"}";

**Comment by Mohit1215** [comment]
[payloadstring.txt](https://github.com/aelassas/Wexflow/files/3740863/payloadstring.txt)

**Comment by aelassas** [comment]
There are some issues in your payload. Can you try the following payload on postman:

```json
{ "workflowId":1, "xml":"<Workflow xmlns=\"urn:wexflow-schema\" id=\"1\" name=\"Workflow_CsvToXml\" description=\"Workflow_CsvToXml\">\r\n  <Settings>\r\n    <Setting name=\"launchType\" value=\"trigger\" /> \r\n    <Setting name=\"enabled\" value=\"true\" />\r\n    <Setting name=\"approval\" value=\"false\" />\r\n  </Settings>\r\n  <LocalVariables />\r\n  <Tasks>\r\n    <Task id=\"1\" name=\"FilesLoader\" description=\"Loading CSVs\" enabled=\"true\">\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv1.csv\" />\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv2.csv\" />\r\n    </Task>\r\n    <Task id=\"2\" name=\"CsvToXml\" description=\"Generating XMl files from CSVs\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"1\" />\r\n    </Task>\r\n    <Task id=\"3\" name=\"FilesMover\" description=\"Moving Xmls to CsvToXml folder\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"2\" />\r\n      <Setting name=\"destFolder\" value=\"C:\\WexflowTesting\\CsvToXml\" />\r\n    </Task>\r\n  </Tasks>\r\n</Workflow>" }
```

Did you set up your custom task GetReport in Wexflow?

**Comment by Mohit1215** [comment]
![Capture_request](https://user-images.githubusercontent.com/31873157/67039961-7ce96a80-f0f0-11e9-8c48-c8bbeae0d7d7.PNG)


 I tried the above payload and I am attaching the response

**Comment by Mohit1215** [comment]
And yes I already have the custom task Get Report in Wexflow.

**Comment by aelassas** [comment]
Under which user you execute the request? admin?

**Comment by Mohit1215** [comment]
yes

**Comment by aelassas** [comment]
Which version of Wexflow are you using?

**Comment by Mohit1215** [comment]
version 4.8

**Comment by aelassas** [comment]
Ok, can you open the log file Wexflow.log and show me the logs after you execute the request.

**Comment by Mohit1215** [comment]
Nothing comes up in the logs file
[Wexflow.log](https://github.com/aelassas/Wexflow/files/3740960/Wexflow.log)

**Comment by aelassas** [comment]
Ok, so I think that there's an issue in your Authorization header. If you are using the default password (wexflow2018), then try the following header in postman:

```
Basic YWRtaW46ZWUwNWVhYWJhN2I3NmYxNmUyODVkOTgzZDYwNWM5YmY=
```

**Comment by Mohit1215** [comment]
I tried that but it still gives false.

**Comment by Mohit1215** [comment]
Also on using **http://localhost:8000/wexflow/start?u=admin&p=wexflow2018&w=1** it returned the status as OK but I cannot see it in logs.

**Comment by aelassas** [comment]
Ah, sorry I thought you're using the 4.9. For the 4.8, you have to specify username and password in the payload. Try the following payload in postman:

```json
{ "workflowId":1, "username": "admin", "password": "ee05eaaba7b76f16e285d983d605c9bf", "xml":"<Workflow xmlns=\"urn:wexflow-schema\" id=\"1\" name=\"Workflow_CsvToXml\" description=\"Workflow_CsvToXml\">\r\n  <Settings>\r\n    <Setting name=\"launchType\" value=\"trigger\" /> \r\n    <Setting name=\"enabled\" value=\"true\" />\r\n    <Setting name=\"approval\" value=\"false\" />\r\n  </Settings>\r\n  <LocalVariables />\r\n  <Tasks>\r\n    <Task id=\"1\" name=\"FilesLoader\" description=\"Loading CSVs\" enabled=\"true\">\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv1.csv\" />\r\n      <Setting name=\"file\" value=\"C:\\WexflowTesting\\CsvToXml\\csv2.csv\" />\r\n    </Task>\r\n    <Task id=\"2\" name=\"CsvToXml\" description=\"Generating XMl files from CSVs\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"1\" />\r\n    </Task>\r\n    <Task id=\"3\" name=\"FilesMover\" description=\"Moving Xmls to CsvToXml folder\" enabled=\"true\">\r\n      <Setting name=\"selectFiles\" value=\"2\" />\r\n      <Setting name=\"destFolder\" value=\"C:\\WexflowTesting\\CsvToXml\" />\r\n    </Task>\r\n  </Tasks>\r\n</Workflow>" }
```

For start, you should provide the password in md5 format as follows: http://localhost:8000/wexflow/start?u=admin&p=ee05eaaba7b76f16e285d983d605c9bf&w=1

**Comment by Mohit1215** [comment]
Finalllyyyy!!! Yes I had to include username and password in the JSON file. I could do it with Postman though. 
So for my code the paload string would loook like this right?

[payloadstring.txt](https://github.com/aelassas/Wexflow/files/3741174/payloadstring.txt)

**Comment by aelassas** [comment]
No, try the following one:

```csharp
var demoString = "{ \"workflowId\":1, \"username\": \"admin\", \"password\": \"ee05eaaba7b76f16e285d983d605c9bf\", \"xml\":\"<Workflow xmlns=\\\"urn:wexflow-schema\\\" id=\\\"1\\\" name=\\\"Workflow_CsvToXml\\\" description=\\\"Workflow_CsvToXml\\\">\\r\\n  <Settings>\\r\\n    <Setting name=\\\"launchType\\\" value=\\\"trigger\\\" /> \\r\\n    <Setting name=\\\"enabled\\\" value=\\\"true\\\" />\\r\\n    <Setting name=\\\"approval\\\" value=\\\"false\\\" />\\r\\n  </Settings>\\r\\n  <LocalVariables />\\r\\n  <Tasks>\\r\\n    <Task id=\\\"1\\\" name=\\\"FilesLoader\\\" description=\\\"Loading CSVs\\\" enabled=\\\"true\\\">\\r\\n      <Setting name=\\\"file\\\" value=\\\"C:\\\\WexflowTesting\\\\CsvToXml\\\\csv1.csv\\\" />\\r\\n      <Setting name=\\\"file\\\" value=\\\"C:\\\\WexflowTesting\\\\CsvToXml\\\\csv2.csv\\\" />\\r\\n    </Task>\\r\\n    <Task id=\\\"2\\\" name=\\\"CsvToXml\\\" description=\\\"Generating XMl files from CSVs\\\" enabled=\\\"true\\\">\\r\\n      <Setting name=\\\"selectFiles\\\" value=\\\"1\\\" />\\r\\n    </Task>\\r\\n    <Task id=\\\"3\\\" name=\\\"FilesMover\\\" description=\\\"Moving Xmls to CsvToXml folder\\\" enabled=\\\"true\\\">\\r\\n      <Setting name=\\\"selectFiles\\\" value=\\\"2\\\" />\\r\\n      <Setting name=\\\"destFolder\\\" value=\\\"C:\\\\WexflowTesting\\\\CsvToXml\\\" />\\r\\n    </Task>\\r\\n  </Tasks>\\r\\n</Workflow>\" }";
```

**Comment by Mohit1215** [comment]
Ok it works from the code too now! Thank you so much for the help!

So what are the changes in the file and how do I create that? I see extra back slashes, is it using JSonConvert.SerializeObject?

**Comment by aelassas** [comment]
I escaped the payload [online](https://www.freeformatter.com/java-dotnet-escape.html).

**Comment by Mohit1215** [comment]
ok
