### ISSUE TITLE
[HELP] Wexflow Manager Web Interface in Linux

### ISSUE THREAD

**Issue by albertobaselga** [aelassas/Wexflow#144]
Hi!,
I'm using the Linux version, but no idea how to enter the web page to visualize the workflows and the designer. When I start the backend server and I access `localhost:8000` it redirects me to `http://localhost:8000/swagger-ui/doc.html`. Can you please help me to access the Web Interface?
Thanks in advance

**Comment by aelassas** [comment]
To access the backend, open thre file /opt/wexflow/Backend/index.html in a
browser.

Le mer. 30 oct. 2019 à 00:03, Alberto Baselga <notifications@github.com> a
écrit :

**Comment by hlaebe** [comment]
Hi,
 how to do this when try to install on a headless linux server ?

TIA

**Comment by aelassas** [comment]
@hlaebe Yes, just install the backend on a web server. Check out the [documentation](https://github.com/aelassas/Wexflow/wiki/Usage#installation).
