### ISSUE TITLE
5.1 Installer doesn't launch

### ISSUE THREAD

**Issue by ggblake** [aelassas/Wexflow#147]
downloaded the x64 .exe  but it will not launch as an installer

**Comment by aelassas** [comment]
@ggblake I've just tested the x64 installer on two Windows 10 machines but I can't reproduce your issue. Can you try again by right clicking on the installer and run it as administrator?

**Comment by ggblake** [comment]
did that
found the problem: the .exe has to be unblocked first


GGB


On 11/11/2019 at 1:43 PM, Akram El Assas <notifications@github.com> wrote:
@ggblake I've just tested the x64 installer on two Windows 10 machines but I
can't reproduce your issue. Can you try again by right clicking on the
installer and run it as administrator?

**Comment by aelassas** [comment]
@ggblake Great. Yes, of course the .exe has to be unblocked first.
