### ISSUE TITLE
WexFlow Update [Question]

### ISSUE THREAD

**Issue by akleine01** [aelassas/Wexflow#148]
Hi,

I want to update to the new version of WexFlow.

What is the best procedure to keep my worksflows (Database)?

A.Kleine

**Comment by aelassas** [comment]
@akleine01 If you're using LiteDB, just backup your database C:\Wexflow\Database\Wexflow.db. Uninstall Wexflow then install the new version of Wexflow. Finally, override C:\Wexflow\Database\Wexflow.db with your database.

**Comment by aelassas** [comment]
Now, you can export and import workflows.
