### ISSUE TITLE
PluginFTPS >> ValidateCertificate 

### ISSUE THREAD

**Issue by JonathanFromISEE** [aelassas/Wexflow#150]
Hello, 
First of all I wanted to thank you and congratulate you for this wonderful project, which we use every day.
I have identified a bug in the FTP task, more precisely in the PluginFTPS.cs file;
Indeed, a client instruction is missing: 
`client.ValidateCertificate += OnValidateCertificate;`
for List(), Download() and Delete() commands (Found it in Upload command only).  To me, add this instruction after each client instantiation allows us to pass the certificate verification when connecting to FTPS.

John.

**Comment by aelassas** [comment]
@JonathanFromISEE Thank you for reporting this. I fixed the issue. I will publish the fix in the v5.2.
