### ISSUE TITLE
Multiple instances of a same workflow defintion

### ISSUE THREAD

**Issue by jeffaries** [aelassas/Wexflow#152]
Hello, 
I have just started my discovery journey of Wexflow. It appears that, when starting multiple instances of a same workflow, the instances are queued and wait for the previous instance to be completed before starting.
Isn't it possible to start multiple instance of a same workflow in parallel?

Thank you

**Comment by aelassas** [comment]
@jeffaries Yes, the instances are queued and wait for the previous instance to be completed before starting. It's not possible for the moment to start multiple instances of a same workflow in parallel. I will try to work on parallel instances in the upcomming version (v5.2). I think, I will add an option in the wokflow (for example enableParallelExecution) to allow parallel execution of the same workflow.

**Comment by jeffaries** [comment]
Thank you for your super fast answer.
And, BTW, great work with Wexflow!

**Comment by dentrazergit** [comment]
Would be very useful for me as well.

**Comment by softwareguy74** [comment]
This is a must.  Kind of defeats the idea of a workflow engine if you can't even run more than one definition at a time.

**Comment by aelassas** [comment]
@softwareguy74 Thanks for your feedback. At the moment, you can run multiple different definitions in parallel. But for the same definition, jobs are queued for the moment. I will work on parallel execution of the same definition in the v5.2.

**Comment by aelassas** [comment]
@jeffaries @dentrazergit @softwareguy74 I added the ability to run workflow jobs of the same workflow definition in parallel through enableParallelJobs setting option. The option is facultative and defaults to true. This means that the default behavior is to run everything in parallel (same workflow definition and different workflow definitions). When set to false, workflow jobs of the same definition are queued. Thank you all for your feedback.

**Comment by jeffaries** [comment]
Hi @aelassas, thank you again for your fast response.
I have run first tests. I can indeed create multiple instances of the same workflow. However, I am afraid that you have to change multiple thing, starting with the API: 

1. To create an instance of a workflow, the workflow definition id is used, and an instance id should be returned.
2. For any other operation (Approve, suspend, ...), the API should use the instance id.

The Workflow definition id is actually required only during Start

**Comment by aelassas** [comment]
I will have to update start api method to return instance id. The instance
id can then be used in suspend, resume... For the moment, running multiple
instances will be possible only through the api. I will update the ui later.

Le lun. 18 nov. 2019 à 22:52, Jeff Gueldre <notifications@github.com> a
écrit :

**Comment by aelassas** [comment]
@jeffaries I added instance id for workflow jobs. Now when a workflow is started, an instance id is returned. The instance id can then be used in suspend, resume, stop,  approve and disapprove functions. 

I also updated the RESTful API, Swagger, Wexflow Manager, the backend and the command line client. The workflow id is required only during start. 

For the moment, running multiple instances of the same workflow definition is possible only through the RESTful API and Swagger.

**Comment by aelassas** [comment]
@jeffaries @dentrazergit @softwareguy74 I will publish parallel jobs of the same workflow definition in the upcoming version (v5.2).

**Comment by aelassas** [comment]
@jeffaries @dentrazergit @softwareguy74 The v5.2 is out:  https://github.com/aelassas/Wexflow/releases/tag/v5.2

This version includes an upgrade to .NET Core 3.1 LTS, support for PostgreSQL, SQL Server, MySQL and SQLite, JSON editor, display of server logs in the backend, parallel jobs of the same workflow definition, date interpolation, bug fixes, performance enhancements and under the hood updates.

**Comment by SenyaMur** [comment]
Can you add **enableParallelJobs** setting to designer?

Thanks for your work!

**Comment by davelock** [comment]
Hi, sorry if this has already been addressed but I'm struggling with this issue, from the dashboard I can't start multiple instances of the same workflow, can you please tell how I can get around this? I've seen ParallelJobId property in Workflow.cs but I can't see where I use it.  Many thanks

**Comment by aelassas** [comment]
You can't start multiple instances from the backend. You can start multiple
instances from Swagger.
