### ISSUE TITLE
MacOS fresh install error

### ISSUE THREAD

**Issue by theobouwman** [aelassas/Wexflow#153]
After installing .NET and extracting everything in /Applications and running `dotnet Wexflow.Server.dll` I get this error:
```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/opt/wexflow/Wexflow/Wexflow.xml'.
```

**Comment by aelassas** [comment]
@theobouwman I think there's an issue in the configuration file of Wexflow server. For the moment, here is the workaround: Edit the configuration file /Applications/wexflow/Wexflow.Server/appsettings.json and remove these two lines (lines 3 and 4):

```json
"WexflowSettingsFileLinux": "/opt/wexflow/Wexflow/Wexflow.xml",
"WexflowSettingsFileMacOS": "/Applications/wexflow/Wexflow/Wexflow.xml",
```

And the line 2 must be like this:

```json
"WexflowSettingsFile": "/Applications/wexflow/Wexflow/Wexflow.xml",
```

**Comment by aelassas** [comment]
@theobouwman Please let me know if the workaround works for you. appsettings.json should be like this:

```json
{
  "WexflowSettingsFile": "/Applications/wexflow/Wexflow/Wexflow.xml",
  "WexflowServicePort":  8000, 
  "DateTimeFormat": "dd-MM-yyyy HH:mm:ss",
  "Smtp.Host": "smtp.gmail.com",
  "Smtp.Port": 587,
  "Smtp.EnableSsl": true,
  "Smtp.User": "user",
  "Smtp.Password": "password",
  "Smtp.From": "user",
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```

**Comment by aelassas** [comment]
@theobouwman I fixed the issue and updated the macOS package. Can you please delete your existing wexflow folder from /Applications/ folder, download the new [wexflow-5.1-macos-dotnet-core.zip](https://github.com/aelassas/Wexflow/releases/download/v5.1/wexflow-5.1-macos-dotnet-core.zip) and try again.

**Comment by aelassas** [comment]
@theobouwman any update?
