### ISSUE TITLE
Failed tasks

### ISSUE THREAD

**Issue by dentrazergit** [aelassas/Wexflow#157]
How can I check if the given task in a workflow failed apart from looking into logs? Is there is something like a progress of workflow execution visualised?

**Comment by aelassas** [comment]
There's final workflow result in Dashboard and History pages. Also, in the log file. But, for task level, the only way to check the status for the moment is the log file.

**Comment by janborup** [comment]
Hi @dentrazergit 

[Serverlogs Feature](https://github.com/aelassas/Wexflow/pull/165#issuecomment-560154530)

The newest Wexflow v. 5.2 has the new serverlog feature, so on dashboard and history in backend, you will get at full logging of your task, so no more finding and digging in the logfiles 👍 

Close this issue, if you are satisfied.
