### ISSUE TITLE
hosting web pages on iis, i don't see the same view when loading from local drive, lets me sign in and brings me to the api page

### ISSUE THREAD

**Issue by rheslar15** [aelassas/Wexflow#158]
hosting web pages on iis, i don't see the same view when loading from local drive, lets me sign in and brings me to the api page, copied entire contents of the wexflow/backend directory of my computer, to a folder on my iis, set it's port as 8000

what do i have to do the get the dashboard page, when hosting on iis?

**Comment by aelassas** [comment]
You must set a port different from 8000. 8000 is used for Wexflow server.

**Comment by rheslar15** [comment]
got it, thanks
