### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by man75** [aelassas/Wexflow#162]
Hi,

je ne trouve pas l'executable pour installer wexflow.

Merci

**Comment by aelassas** [comment]
[Here](https://github.com/aelassas/Wexflow/releases/download/v5.1/wexflow-5.1-windows-x64.exe) is the x64 installer. You must unblock it before install. You can find other installers in [releases](https://github.com/aelassas/Wexflow/releases) page.

**Comment by janborup** [comment]
@man75 Does i solve your request?
Close your issue is you are satisfied.
