### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by aelassas** [aelassas/Wexflow#163]
Here are the enhancement requests from different issues on GitHub. If you have other requests, just post in this issue.

- Support for PostgreSQL (done in v5.2)
- Support for Groups and Organizations
- Support for multiple languages
- Parallel execution of the same workflow definition (done in v5.2)
- Scale-out (however, this could be addressed via Docker Nodes in Kubernetes, which is built for this)
- UI drag and drop designer (I am using the excellent Cytoscape.js library for the execution graph; I may want to also look a https://konvajs.org/  This could be used to build an interactive UI designer) (done in v5.3)
- Check current stage of execution of a workflow in UI - task is highlighted in the execution graph.
- Support callbacks from external systems to resume/pass parameters to next task in the workflow
- Versioning - for long running tasks that are executed using an older workflow version and then it is updated with new tasks

**Comment by janborup** [comment]
- TaskStore (Start out without any tasks, then Adding sample tasks after need) https://plugins.jquery.com/appstore/
- Showing server log in Backed history.
- Backend designer with task Start/Stop, Approval, History and server log in same, for easier task/test/debug when creating tasks.

**Comment by aelassas** [comment]
- Support for SQL Server
- Support for MySQL
- Support for SQLite
- Scalability by adding more servers
- Support for backup and rollback
- Distribute tasks to multiple machines

**Comment by aelassas** [comment]
- Load balancing
- Support for Amazon DynamoDB
- Support for Redis
- Support for Oracle
- Add multi-line settings in the designer
- Add an option to encrypt password setting fields in the designer
- JSON editor in the designer
- Enhanced designer with drag and drop features like https://workflowengine.io

**Comment by aelassas** [comment]
- Import BPMN XML and to convert it to Wexflow's schema
- Take a look at: https://github.com/bpmn-io/diagram-js  And it also forms the basis of this one: https://github.com/bptlab/chor-js The later would be perfect as a workflow designer

**Comment by janborup** [comment]
- SQLtoExcel
- XMLtoExcel
- CSVtoExcel
- JSONtoExcel
https://www.codebyamir.com/blog/create-excel-files-in-c-sharp

**Comment by akleine01** [comment]
What about encrypted password in Tasks (Mail, FTP,..)?

**Comment by aelassas** [comment]
@akleine01 I've already added that in enhancement requests.

**Comment by aelassas** [comment]
@janborup I added server logs to the backend in the dashboard and history pages:

![server-logs](https://user-images.githubusercontent.com/1339626/69917694-20a49500-1469-11ea-9718-795dac7f1253.png)

I will publish these features in the v5.2.

**Comment by aelassas** [comment]
- Move checkboxes to the left to align with the input boxes
- Admin Setting to show/hide XML WF Designer (no need for a header button if XML Designer is hidden)
- Approval Workflows – Approval Type. When sending the Task to a Group, there is a need for Group Approval Modes: i.e. when sending a Task to a Group, there should be options for: 1.) Anyone can approve and 2.) All must Approve.   See here: https://docs.microsoft.com/en-us/power-automate/all-assigned-must-approve   And there is also sometimes the need for 3.) ‘Majority must approve’
- Docker: most modern packages are available as Docker. Create docker images of the releases, to avoid people having to ‘roll their own’ every time
- Embeddability: Wexflow has its own User Management system. However, this presents a difficulty to embed it into existing systems which already have their own User Management setup. Let’s say a Task is assigned to a User in another system which would use Wexflow for Task Management – it would be far easier to do the User Lookup in the other system, instead of trying to sync both User Management systems. Add an API to support Users and Groups via lookup in an external user management system (there could be a system setting to use the native User Management system, or an option for External User Lookup), and the permissions could then be set from the other system, so that Approvers and other Users would not have access to the Admin settings
- UI – it would be great to add the ability to support Themes. https://github.com/DevExpress/bootstrap-themes  The nice thing about this is that users could add additional Themes, if they wanted to, but these two would look really nice and modern as a baseline. Theming is important for Embeddability as well. In general, Bootstrap would be a great way to go, but perhaps something like this would be too much of an effort to move to: https://adminlte.io/   In general, a modern Bootstrap Theme would also make it easier to support mobile devices

**Comment by benjstern** [comment]
What about parallel tasks in the execution graph?

**Comment by aelassas** [comment]
@benjstern For the moment, two things are forbidden in the execution graph:

- Parallel tasks
- Infinite loops

These two things are detected during the validation process when creating a new workflow or updating an existing workflow.

Here is an example of parallel tasks:

![alt tag](https://aelassas.github.io/wexflow/images/Workflow_ExecutionGraph_parallel_tasks.png)

```xml
<ExecutionGraph>
  <Task id="1"><Parent id="-1" /></Task>
  <Task id="2"><Parent id="1"  /></Task>
  <Task id="3"><Parent id="1"  /></Task>
</ExecutionGraph>
```

Here is an example of an infinite loop:

![alt tag](https://aelassas.github.io/wexflow/images/Workflow_ExecutionGraph_infinite_loop_2.png)

```xml
<ExecutionGraph>
  <Task id="1"><Parent id="-1" /></Task>
  <Task id="2"><Parent id="1"  /></Task>
  <Task id="1"><Parent id="2"  /></Task>
</ExecutionGraph>
```

I will think about allowing parallel tasks in the upcoming versions.

**Comment by aelassas** [comment]
- Use [jsPlumb](https://jsplumbtoolkit.com/demonstration/flowchart-builder) to create a new designer with drag and drop features.

**Comment by aelassas** [comment]
@janborup I started working on a brand new designer with drag and drop features using the library Flowy. Here is a live demo of the library: https://alyssax.com/x/flowy/

This is just the beginning, it will requires a lot of work on the UI and probably the backend too. I think that I will also need to tweak Flowy library too.

You can also play with the new designer by opening the designer2.html page from the backend in a web browser.

Tell me what you think about this new designer.

Here are some screenshots with fake data:

![wexflow-flowy-designer-1](https://user-images.githubusercontent.com/1339626/77856880-1a91ab80-71f2-11ea-837e-9717c90dbb6d.png)
![wexflow-flowy-designer-2](https://user-images.githubusercontent.com/1339626/77856882-1bc2d880-71f2-11ea-9bc3-ff672a631bce.png)
![wexflow-flowy-designer-3](https://user-images.githubusercontent.com/1339626/77856884-1cf40580-71f2-11ea-95b7-e5a1b1ec4c5b.png)
![wexflow-flowy-designer-4](https://user-images.githubusercontent.com/1339626/77856885-1d8c9c00-71f2-11ea-8b9b-e0181fb2ffa3.png)
