### ISSUE TITLE
Support DynamoDB as workflow engine store?

### ISSUE THREAD

**Issue by softwareguy74** [aelassas/Wexflow#167]
Is there currently or planned support for using DynamoDB as the workflow engine backing store?  That would be awesome as I don't want to use any of the other NoSQL options.   I believe a lot or people would appreciate this.

**Comment by aelassas** [comment]
Thank you for your feedback. I will explore DynamoDB integration in upcoming versions.

**Comment by aelassas** [comment]
Sorry, I am not going to implement DynamoDB provider. Wexflow supports now [LiteDB](https://github.com/aelassas/Wexflow/wiki/LiteDB), [MongoDB](https://github.com/aelassas/Wexflow/wiki/MongoDB), [RavenDB](https://github.com/aelassas/Wexflow/wiki/RavenDB), [CosmosDB](https://github.com/aelassas/Wexflow/wiki/CosmosDB), [PostgreSQL](https://github.com/aelassas/Wexflow/wiki/PostgreSQL), [SQL Server](https://github.com/aelassas/Wexflow/wiki/SQL-Server), [MySQL](https://github.com/aelassas/Wexflow/wiki/MySQL) and [SQLite](https://github.com/aelassas/Wexflow/wiki/SQLite).
