### ISSUE TITLE
My Custom Task is not displayed in Wexflow Version 5.2

### ISSUE THREAD

**Issue by PraveenSubbarao7** [aelassas/Wexflow#172]
Hello,
I have installed Wexflow 5.2 & created a custom task. I have placed the dll file in:
1. C:\Program Files\Wexflow
2. C:\Wexflow\Tasks

Placed the xml files in :
1. C:\Program Files\Wexflow\Wexflow.Scripts.MongoDB\Workflows
2.C:\Wexflow\Workflows ( This folder was not there, as per the instructions given created this folder)
Please help in resolving this issue.

**Comment by PraveenSubbarao7** [comment]
This is the xml used:

<?xml version="1.0" encoding="utf-8"?>
<Workflow xmlns="urn:wexflow-schema" id="200" name="Workflow_MyWorkflow" description="Workflow_MyWorkflow">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
  </Settings>
  <Tasks>
    <Task id="1" name="MyTask" description="Launching Chrome Browser" enabled="true">
      <Setting name="settingName" value="settingValue" />
    </Task>
    </Tasks>
</Workflow>

**Comment by aelassas** [comment]
You must update C:\Wexflow\TasksNames.json and C:\Wexflow\TasksSettings.json then you can create your workflow from the designer.

**Comment by aelassas** [comment]
Just add your custom task to C:\Wexflow\TasksNames.json and C:\Wexflow\TasksSettings.json and it will show up in the designer.
