### ISSUE TITLE
Custom workflow event support in ExecutionGraph 

### ISSUE THREAD

**Issue by piyush135** [aelassas/Wexflow#173]
Not able to create custom event in ExecutionGraph like OnRejected and  OnSuccess in Approval workflow. 
Please let us know if there are any dependencies required.

**Comment by aelassas** [comment]
Can I see your workflow?

**Comment by piyush135** [comment]
Below is the Xml used:-

<?xml version="1.0" encoding="utf-8"?>
<Workflow xmlns="urn:wexflow-schema" id="200" name="Multi Level Document Approval workflow" description="MultiLevel_Workflow_Approval">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
    <Setting name="approval" value="true" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="1" name="Approval" description="Waiting for approval" enabled="true" />
    <Task id="2" name="Wait" description="Waiting for 2 seconds" enabled="true">
      <Setting name="duration" value="00.00:00:02" />
    </Task>
	<Task id="3" name="Wait" description="Waiting for 3 seconds" enabled="true">
      <Setting name="duration" value="00.00:00:03" />
    </Task>
	<Task id="4" name="Workflow" description="Starting workflow 10 and 11" enabled="true">
			<Setting name="wexflowWebServiceUri" value="http://localhost:8000/wexflow/" />
			<Setting name="username" value="admin" />
			<Setting name="password" value="ee05eaaba7b76f16e285d983d605c9bf" />
			<Setting name="action" value="start" />
			<Setting name="id" value="10" />
			<Setting name="id" value="11" />
		</Task>
  </Tasks>
  <ExecutionGraph>
	<Task id="1"><Parent id="-1" /></Task>
	<Task id="2"><Parent id="1" /></Task>
	<OnRejected>
		<Task id="3"><Parent id="-1" /></Task>
	</OnRejected>
	<Review>
		<Task id="4"><Parent id="1" /></Task>
	</Review>
  </ExecutionGraph>
</Workflow>

**Comment by aelassas** [comment]
You can't put Review node in the execution graph.

**Comment by piyush135** [comment]
I want to call an event in ExecutionGraph to trigger new workflow. Is this possible?

**Comment by aelassas** [comment]
You can use [Workflow](https://github.com/aelassas/Wexflow/wiki/Workflow) task to trigger your workflow from your workflow.
