### ISSUE TITLE
Not able to delete the user

### ISSUE THREAD

**Issue by NareshPalle9** [aelassas/Wexflow#176]
Hi, I am new to wexflow, and have created a new User, but I can't able to login with new Username and password and delete the user from User tab and by using REST API (http://localhost:8000/wexflow/deleteUser?username=XXXX&password=XXXXXYYY") . 
I work on Mac Catlina vesrsion 10.15.2,  .Net core 3.1 and wexflow 5.2. 

Where are user details stored in wexflow ? 
And When I select the user it shows errors in console.. 

Uncaught TypeError: Cannot read property 'Id' of undefined
    at users.min.js:1
    at XMLHttpRequest.r.onreadystatechange 
Uncaught TypeError: Cannot read property 'Password' of undefined

**Comment by aelassas** [comment]
What is the profile of the user you created? Super-admin or admin or restricted?

**Comment by NareshPalle9** [comment]
Thank you for replaying, I created restricted user profile.

**Comment by aelassas** [comment]
Did you try using Swagger? You must put md5 of the password in the password query string.

**Comment by NareshPalle9** [comment]
<img width="1379" alt="Screenshot 2020-01-03 at 12 57 59 PM" src="https://user-images.githubusercontent.com/57945978/71711815-b6489100-2e28-11ea-845d-c28e3428f1af.png">
<img width="557" alt="Screenshot 2020-01-03 at 12 59 13 PM" src="https://user-images.githubusercontent.com/57945978/71711851-da0bd700-2e28-11ea-8a85-1c9fed60277c.png">
Tried in swageer too, Not working. showing an error in terminal console log. Please check attached images. Shall i need to install light db in my Mac to make it work or it is installed along with wexflow installation ?

**Comment by aelassas** [comment]
LiteDB is installed with Wexflow. You can try LiteDB shell or LiteDB studio to explore the database.

**Comment by NareshPalle9** [comment]
<img width="581" alt="Screenshot 2020-01-03 at 6 14 20 PM" src="https://user-images.githubusercontent.com/57945978/71724072-e1e17080-2e54-11ea-9677-26d741cb7964.png">
 User credentials are saved in db. PFA

**Comment by aelassas** [comment]
Yes, credentials are saved in db.

**Comment by aelassas** [comment]
The v5.4 should work fine now.
