### ISSUE TITLE
cant init user  table in mysql 

### ISSUE THREAD

**Issue by bikaqiou2000** [aelassas/Wexflow#177]
`        public static readonly string TableStruct = "(" + ColumnName_Id + " INT NOT NULL AUTO_INCREMENT, " + ColumnName_Username + " VARCHAR(255), " + ColumnName_Password + " VARCHAR(255), " + ColumnName_UserProfile + " INT, " + ColumnName_Email + " VARCHAR(255), " + ColumnName_CreatedOn + " **TIMESTAMP**, " + ColumnName_ModifiedOn + " **TIMESTAMP**, CONSTRAINT " + DocumentName + "_pk PRIMARY KEY (" + ColumnName_Id + "))";
`
MySQL not allow exist two timestamp columns  in one table ,so we need to  change column type to datetime or any other way.

**Comment by aelassas** [comment]
When I have done MySQL testing, two timestamp columns worked for me. Which version of MySQL are you using?

**Comment by bikaqiou2000** [comment]
> When I have done MySQL testing, two timestamp columns worked for me. Which version of MySQL are you using?
  
mysql version	5.7.22
version_comment	MySQL Community Server (GPL)

**Comment by aelassas** [comment]
MySQL versions before 5.6.1 would not let two TIMESTAMP columns in the same table, unless as you rightly noted without defaults and allowing null.

MySQL 5.6.+ allows two or more TIMESTAMP columns in a table.
