### ISSUE TITLE
linux onstallation problem

### ISSUE THREAD

**Issue by adriano-ghezzi** [aelassas/Wexflow#178]
after unpacking

running 
dotnet Wexflow.Server.dll

In /opt/wexflow/Wexflow-5.2/src/dotnet-core/Wexflow.Server

give me following message

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-Wexflow.Server.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

dotnet seems ok

dotnet -v

.NET Core SDK (3.1.101)
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET Core application.

Thanks

**Comment by aelassas** [comment]
You must unzip the package in /opt/ and Wexflow.Server must be in /opt/wexflow/Wexflow.Server/.

**Comment by aelassas** [comment]
Just follow the instructions in the documentation and it should work fine.
