### ISSUE TITLE
Can Wexflow run in docker

### ISSUE THREAD

**Issue by Ray365** [aelassas/Wexflow#179]
I want deploy WexFlow in K8s, but I dont' know how to create the images of it.

**Comment by janborup** [comment]
Hi Ray.

Yes - you can run Webflow in Docker, but there is not a pre-build image version for this, so you have make this on your own.

[Get an Linux distribution](https://hub.docker.com/search?category=os&source=verified&type=image)
[Get a MS Docker Core](https://hub.docker.com/_/microsoft-dotnet-core)
[Download/Install latest WexFlow Linux Core version](https://github.com/aelassas/Wexflow/releases/tag/v5.2)

Cheers Jan

**Comment by Ray365** [comment]
How could I build the docker images, did you have the sample command script.

**Comment by janborup** [comment]
Hey Ray

A new docker image normally depends on what base-image you want to use, but there i fine [instructions for this on the docker.com site](https://docs.docker.com/develop/develop-images/baseimages/).

/Cheers

**Comment by bh-adrienne** [comment]
@Ray365  I figured a full working example would be useful and I needed one to test this out anyway, so I've linked it here.

**Comment by aelassas** [comment]
@Ray365 @janborup I updated the documentation regarding [Docker](https://github.com/aelassas/Wexflow/wiki/Docker). Tell me if this works fine for you.
