### ISSUE TITLE
Question for you

### ISSUE THREAD

**Issue by bumblebee333** [aelassas/Wexflow#180]
Hi there,
        I am looking at wexflow to automate some file copy and file move tasks in a linux environment. Is it possible for run existing scripts (non .net) with the ProcessStart task in a linux environment?

Thanks,
Rakesh

**Comment by bumblebee333** [comment]
I was able to run a python file using commandline (cmd.exe) using ProcessStart task. I am hoping I can do the same using bash on linux. Will give it a shot.

**Comment by aelassas** [comment]
@bumblebee333 Did you succeed using [ProcessLauncher](https://github.com/aelassas/Wexflow/wiki/ProcessLauncher) task on Linux with your custom configuration?

**Comment by bumblebee333** [comment]
Sorry for the late response. The project changed into a full on python development due to in house expertise. I didn’t get to try this.
