### ISSUE TITLE
Adding custom task to a workflow

### ISSUE THREAD

**Issue by davelock** [aelassas/Wexflow#181]
Hi Akram
I have followed the guide (https://github.com/aelassas/Wexflow/wiki/Custom-tasks) to create a custom task.  But I was unable to add a custom task to a workflow as the task I added was not in the Name dropdown list.  I added my new task to TaskSettings.json and TaskName.json and the task appears.
![image](https://user-images.githubusercontent.com/7046091/73861892-a6600a80-4835-11ea-8cfb-dca33ff0d6df.png)
But when I click on New Task in the designer, select the task from the Name dropdown list and click save, I get a general error popup. 
![image](https://user-images.githubusercontent.com/7046091/73861480-fc807e00-4834-11ea-831d-38fb2f91cf33.png)
I've checked the logs and the error doesn't get written (log4net is set to record all logs). I assume there must be a step that I have missed when creating a new task, can you please help me?
Many thanks
Ps 
Many thanks for responding to the 'multiple wokflow of same type' issue yesterday

**Comment by aelassas** [comment]
Did you put the custom task dll in "C:\Program Files\Wexflow" and restart Wexflow service?

**Comment by davelock** [comment]
Yes, but just to mention, all the others dlls for the other non-custom tasks are in the folder C:\Wexflow.Server so i put them there.  C:\Program Files\Wexflow is empty apart from the log.

**Comment by davelock** [comment]
Is there a way to see exactly what the error is?

**Comment by davelock** [comment]
Ah sorry, I just noticed the error is output to the server console window. It's 'The type of the task NewTask could not be loaded'

**Comment by aelassas** [comment]
Ah, you're using the .net core version. Sorry for the moment custom tasks are supported for the .net version only.

**Comment by davelock** [comment]
Ah, many thanks for your help though.  Do you have plans to roll out custom tasks for .net?
Best regards

**Comment by davelock** [comment]
Hi, I'm sorry for asking again but in order to use Wexflow I need to be able to use .net core for custom tasks.  Are you planning to implement this at any point soon? Many thanks for all of your help with this and my other questions.

**Comment by aelassas** [comment]
Custom tasks are now supported in the .net core version too in the v5.4.
