### ISSUE TITLE
Download specific file from SFTP

### ISSUE THREAD

**Issue by amersasa90** [aelassas/Wexflow#182]
Hello Akram,

I'm trying to download a specific file name from SFTP server, however , its installing all files in that path, how to download only the wanted file?

<?xml version="1.0" encoding="utf-8"?>
<Workflow xmlns="urn:wexflow-schema" id="34" name="Workflow_Sftp_download" description="Workflow_Sftp_download">
  <Settings>
    <Setting name="launchType" value="trigger" />
    
    <Setting name="enabled" value="true" />
    
    <Setting name="approval" value="false" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="1" name="Ftp" description="Listing files" enabled="true">
      <Setting name="command" value="list" />
      <Setting name="protocol" value="sftp" />
      <Setting name="server" value="*******" />
      <Setting name="port" value="22" />
      <Setting name="user" value="****" />
      <Setting name="password" value="*****" />
      <Setting name="path" value="/d/oss/global/var/pm/shared/content3/scheduler/export/bmarayeh/" />
    </Task>
    <Task id="2" name="Ftp" description="Downloading files" enabled="true">
      <Setting name="command" value="download" />
      <Setting name="protocol" value="sftp" />
      <Setting name="server" value="****" />
      <Setting name="port" value="22" />
      <Setting name="user" value="***" />
      <Setting name="password" value="**" />
      <Setting name="path" value="/" />
      <Setting name="selectFiles" value="NOC_Report_Obaida_3G-PLMN-raw-PM_12121-2020_02_06-12_30_01__108.csv" />
    </Task>
    <Task id="3" name="FilesMover" description="Moving files to Sftp_download" enabled="true">
      <Setting name="selectFiles" value="2" />
      <Setting name="destFolder" value="C:\xampp\htdocs\stats\FTP\nokia\" />
      <Setting name="overwrite" value="true" />
    </Task>
  </Tasks>
</Workflow>

**Comment by aelassas** [comment]
Check out this sample: https://github.com/aelassas/Wexflow/blob/master/samples/workflows/dotnet/Workflow_Ftp_download_tag.xml

**Comment by aelassas** [comment]
The Workflow_Ftp_download_tag sample should work fine for this use case.
