### ISSUE TITLE
Check what an approval tasks parameters are before pressing 'Approve' button on Backend\Approval webpage

### ISSUE THREAD

**Issue by davelock** [aelassas/Wexflow#183]
With Approval tasks, is it possible to check what parameters have been sent (when starting a new task via swagger/api) before pressing 'Approve' button on the Backend\Approval webpage?

As in, I want to see what I'm approving (the params of the request) before I press the Approve button.

Is there something to do that already built in or would I have to implement that? 
Many thanks

**Comment by aelassas** [comment]
Sorry this feature is not available. You will have to implement that.

**Comment by aelassas** [comment]
It is now possible to create [approval workflows](https://github.com/aelassas/Wexflow/wiki/Approval-workflows) on generic business objects such as documents, invoices, purchase orders, vacation requests, time sheets, etc. These generic business objects are called records.
