### ISSUE TITLE
Linux - PostgreSQL connection string example is wrong

### ISSUE THREAD

**Issue by hussyd** [aelassas/Wexflow#184]
Hi,

I just want to let you know that I found a wrong example at this page:
https://github.com/aelassas/Wexflow/wiki/PostgreSQL#linux

It says:

> 2.Install PostgreSQL workflow samples. You'll need to modify the connection string in the file /opt/wexflow/Wexflow.Scripts.MongoDB/appsettings.json:

There should be `Wexflow.Scripts.PostgreSQL` instead of `Wexflow.Scripts.MongoDB` .

**Comment by aelassas** [comment]
All fixed. Thank you for reporting this.
