### ISSUE TITLE
Error trying to load custom workflows dependencies

### ISSUE THREAD

**Issue by davelock** [aelassas/Wexflow#185]
Hi

I've pasted an error im getting when the Server project tries to load a custom workflow.  
The custom WF works fine when its empty, but as soon as I add references to other projects within the Wexflow solution, it can't load them. The error i'm getting is: "Could not load file or assembly 'Wexflow.WebClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.":"Wexflow.WebClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"}'. 

Wexflow WebClient is a project that I added and have referenced within my custom WF.

![image](https://user-images.githubusercontent.com/7046091/74449348-5b1cac00-4e74-11ea-934c-0cabd25da53c.png)

Note, in the screenshot, line 510 fails to get the type so it tries to load it from the folder (C:\Wexflow\Tasks). The line that throws the exception is 528.  
I have made sure that all the dlls (including my project Wexflow.WebClient) are in the C:\Wexflow\Tasks folder.  
I'm using Wexflow 5.2 and am not using .net core for any of the referenced projects/assemblies in the custom workflow.

Many thanks

**Comment by aelassas** [comment]
Is Wexflow.WebClient a custom task?

**Comment by davelock** [comment]
Hi, no its a .Net 4.6.1 class library.

**Comment by aelassas** [comment]
Ok, then try to reference it in Wexflow.Server project.

**Comment by davelock** [comment]
Awesome that worked, many thanks
