### ISSUE TITLE
Issue retrieving parameter from custom workflow

### ISSUE THREAD

**Issue by davelock** [aelassas/Wexflow#187]
Hi, apologies for the many questions I've asked during the last week or so but I have another hopefully quick issue:
![image](https://user-images.githubusercontent.com/7046091/74649975-9a9b0f00-5178-11ea-8697-1dd1356d4260.png)

The screen shot above shows a custom Wexflow task.  In the constructor it tries to get a parameter, but the value it returns is the value in the xml ( <Setting name="address" value="**$address**" />) not the actual value ('Testing' in this case).  I'm using Wexflow 5.2 and the task is being loaded from the C:\Wexflow\Tasks as a dll.

The workflow was started from the swagger api with these params:

{
  "WorkflowId": 169,
  "Variables": [
    {
      "Name": "SubmitterId",
      "Value": "15FF0EC1-07B4-452F-848A-08D766B000FC"
    },
    {
      "Name": "AddressValue",
      "Value": "ERT45644EERED"
    },
    {
      "Name": "AddressTitle",
      "Value": "Testing"
    },
    {
      "Name": "Containerid",
      "Value": "93233BD0-54FD-4334-3CAB-08D766D22CDB"
    }
  ]
}

Many thanks

**Comment by aelassas** [comment]
Try Workflow.RestVariables to get parameter values from your task.

**Comment by aelassas** [comment]
@davelock Can I close this issue?

**Comment by davelock** [comment]
Sure, Many thanks, David
