### ISSUE TITLE
Custom workflow starting twice when calling 'startWithParameters' from Swagger api

### ISSUE THREAD

**Issue by davelock** [aelassas/Wexflow#188]
Hi, when starting a custom workflow from swagger, the Workflow.Start method is called twice, is there a workaround/fix available?

![image](https://user-images.githubusercontent.com/7046091/74652158-56f6d400-517d-11ea-8dbc-d534fe6ab701.png)

Many thanks

**Comment by aelassas** [comment]
You mean /startWithVariables. I have just tested it but I can't reproduce your issue. Are you using the .NET Core version of Wexflow on Windows? Are you still facing this issue?

**Comment by aelassas** [comment]
@davelock Can you try the v5.4? Can I close this issue?

**Comment by davelock** [comment]
Sure, thanks David
