### ISSUE TITLE
Turn a single workflow into an executable

### ISSUE THREAD

**Issue by igloo15** [aelassas/Wexflow#191]
I would like to design a workflow and then turn that workflow into an executable to run whenever the executable runs. Is that something that Wexflow could do?

If not could I make so that everytime Wexflow is run it auto runs a single workflow on start and then closes itself?

Most of the ways I have seen Wexflow installed or used is as a service/server that is constantly running with multiple workflows. In my situation I have a rather complex installation/configuration process that I would like to design and then in wexflow and then deploy to other people. You would run wexflow and it would unzip a file and then move stuff around, configure files, etc. But I don't want people to have to start Wexflow login to interface find workflow run it and then manually close wexflow afterwards.

Any thoughts on how to accomplish this?

**Comment by janborup** [comment]
Hi

WexFlow is an cross platform engine, that can be called with external request .
https://github.com/aelassas/Wexflow/wiki/RESTful-API#manager

Just make your on small executeable program/service for your own OS platform, at use the RESTful API, to manage the jobs you like.

/Cheers.

**Comment by aelassas** [comment]
Did you try the [command line client](https://github.com/aelassas/Wexflow/wiki/Command-line-client)?

**Comment by aelassas** [comment]
The command line client should work fine for this use case.
