### ISSUE TITLE
Can we selectEntities from multiple tasks?

### ISSUE THREAD

**Issue by benjstern** [aelassas/Wexflow#192]
In the documentation i know it has a reference to select entities by inputting the taskId like below 
`<Setting name="selectEntities" value="$taskId" />`

Can we select the entities from 2 or more taks like either:
`<Setting name="selectEntities" value="$taskId1,$taskId2" />`
or with just multiple entries?
`<Setting name="selectEntities" value="$taskId1" />`
`<Setting name="selectEntities" value="$taskId2" />`

Thoughts?

**Comment by aelassas** [comment]
You can do it like this:
<Setting name="selectEntities" value="$taskId1" />
<Setting name="selectEntities" value="$taskId2" />

**Comment by benjstern** [comment]
Thanks works like a charm.
