### ISSUE TITLE
Is there a way to prevent a Workflow from launching until previous launch is complete?

### ISSUE THREAD

**Issue by benjstern** [aelassas/Wexflow#193]
I have an issue where my workflow operates in sequential order and if the same workflow is launched again prior to the previous one being complete the results are unexpected.

Is there anyway for a workflow to be locked until the running instance is finished?

**Comment by aelassas** [comment]
You can do it by setting enableParallelJobs to false. Check out the doc https://github.com/aelassas/Wexflow/wiki/Usage#general

**Comment by benjstern** [comment]
Thanks for the direction, that worked
