### ISSUE TITLE
Cron expression	

### ISSUE THREAD

**Issue by amersasa90** [aelassas/Wexflow#194]
Hello,

I'm trying to run a HTTP GET task every Sunday at 07:30 AM , I used below CRON expression:

0 30 7 ? * SUN

Can you assist me ? 

Note : It was working fine with me , but when I changed the PC's timezone  to my region's one, it did not fire.

Thank

**Comment by amersasa90** [comment]
<Workflow id="135" name="site_codes_rf_pending_email" description="site_codes_rf_pending_email" xmlns="urn:wexflow-schema">
  <Settings>
    <Setting name="launchType" value="cron" />
    <Setting name="enabled" value="true" />
    <Setting name="approval" value="false" />
    <Setting name="cronExpression" value="0 38 8 ? * MON" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="1" name="HttpGet" description="site_codes_rf_pending_email" enabled="true">
      <Setting name="url" value="http://admin/pending_emails.php" />
    </Task>
  </Tasks>
</Workflow>

**Comment by janborup** [comment]
Try use www.cronmaker.com
http://www.cronmaker.com/;jsessionid=node01m6c9wr2xppun1bzlmsqo4hdon51718.node0?0

Format looks fine, so try reboot machine and Wexflow Engine.

/Cheers

**Comment by aelassas** [comment]
@amersasa90 Your cron expression is correct. It will fire every Sunday at 07:30 AM. Did you try to reboot your machine and Wexflow as well?

**Comment by aelassas** [comment]
@amersasa90 Can you try the v5.4? Can I close this issue?
