### ISSUE TITLE
Can not create a workflow

### ISSUE THREAD

**Issue by SamKhaan** [aelassas/Wexflow#195]
http://localhost:8000/wexflow/startWithVariables is not working 
I am trying to make an ajax request in .net Core application, though it does not work in Swagger either.

**Comment by janborup** [comment]
Hi Sam

Be sure you are using a POST call, to call this API call.
Use a Body- request like this:
`{
	"WorkflowId":131,
	"Variables":[
	  {
		 "Name":"restVar1",
		 "Value":"C:\\WexflowTesting\\file1.txt"
	  },
	  {
		 "Name":"restVar2",
		 "Value":"C:\\WexflowTesting\\file2.txt"
	  }
	]
} `

/Cheers

**Comment by SamKhaan** [comment]
Hi,

I am using a POST call. Find below is the swagger UI and .net code.

![image](https://user-images.githubusercontent.com/19692047/76007027-64c98a80-5edb-11ea-833b-3ba2e2f01ec0.png)

****.Net code****

 var data = { "WorkflowId": 0, "Variables": [{ "Name": "string", "Value": "string" }] };
        $.ajax({
            url: 'http://localhost:8000/wexflow/start?w=3',
            async: false,
            type: 'Post',
            "crossDomain": true,
            headers: {
             "Access-Control-Allow-Origin": "*",
              "Authorization": "Basic YWRtaW46ZWUwNWVhYWJhN2I3NmYxNmUyODVkOTgzZDYwNWM5YmY="
            }

**Comment by janborup** [comment]
Hi Sam

See you are calling /start?w=3 and not /startwithvariables - is this your error?

Always stress test your call in a Rest tool like GetPostman first, With this you Will found out if the error is in the rest-call or in your program.

/Cheers

**Comment by SamKhaan** [comment]
My bad, I sent you the wrong screen shot , I am calling it with
startwithvariables and I tested it using fiddler but same response.

**Comment by SamKhaan** [comment]
I have sent you sawaager UI where it does not work either.

**Comment by SamKhaan** [comment]
Just wondering why it does not run on Swagger, the screen shot attached above.

**Comment by SamKhaan** [comment]
Find attached the testing with "Fiddler"

**Comment by SamKhaan** [comment]
![rest](https://user-images.githubusercontent.com/19692047/76092612-ad418080-5f8d-11ea-9761-48eaaabeb5b2.PNG)

**Comment by aelassas** [comment]
@SamKhaan I have just tested /startWithVariables and it works fine on my side. Are you using the .NET Core version of Wexflow on Windows? Can you post your custom workflow and your payload?

**Comment by SamKhaan** [comment]
.Net code
var data = { "WorkflowId": 10, "Variables": [{ "Name": "var1", "Value":
"var2” }] };
$.ajax({
url: 'http://localhost:8000/wexflow/startwithvariables',
async: false,
data:data,
type: 'Post',
"crossDomain": true,
headers: {
"Access-Control-Allow-Origin": "*",
"Authorization": "Basic
YWRtaW46ZWUwNWVhYWJhN2I3NmYxNmUyODVkOTgzZDYwNWM5YmY="}

**Comment by aelassas** [comment]
@SamKhaan Ok for the payload. Can you post your workflow in XML as well?

**Comment by aelassas** [comment]
The v5.4 should work fine now.
