### ISSUE TITLE
Wexflow hosted in Azure

### ISSUE THREAD

**Issue by davelock** [aelassas/Wexflow#196]
Hi, I'm trying to host the wexflow database in Azure.  I notice that out of the possible db's that Azure isn't listed (in Wexflow.xml)

Is it possible to use Azure?

Many thanks

**Comment by aelassas** [comment]
Yes, it is possible to host Wexflow's database on Azure. Which db do you want to use? MongoDB, PostgreSQL, CosmosDB?

**Comment by davelock** [comment]
Thanks for replying so quick, I wanted to use SQL Server

**Comment by davelock** [comment]
It works fine when im connecting to a local SQL server but when I use the Azure connection string, I get an error : 'The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections'

**Comment by davelock** [comment]
One thing I noticed is that the Azure connection string uses tcp.
"Server=tcp:databaseurl,1433;Initial Catalog=DatabaseName;...

**Comment by aelassas** [comment]
I haven't tested SQL Server with Azure yet. Did you create an empty wexflow db on Azure? Did you try to connect to the db from Management Studio or an other tool?

**Comment by aelassas** [comment]
@davelock Can you post the full connection string so I can see what's wrong?

Also, can you try to replace "Initial Catalog=" by "Database=" and see if it works.

**Comment by davelock** [comment]
Hi, I'm very sorry for the delay in getting back to you, I got it to work by changing the connection string a little (I removed tcp and copied the over connection strings in the app)

**Comment by aelassas** [comment]
Ok, glad that it worked for you.
