### ISSUE TITLE
How to store variable to each instance of approve workflow

### ISSUE THREAD

**Issue by jeremy-xu** [aelassas/Wexflow#198]
i try to store some info to different instance of an approve workflow. /startWithVariables can just get the value from first instance.

**Comment by aelassas** [comment]
Can you post your workflow in XML please?

**Comment by jeremy-xu** [comment]
<Workflow id="101" name="Test_01" description="Test_01" xmlns="urn:wexflow-schema">
		  <Settings>
		    <Setting name="launchType" value="trigger" />
		    <Setting name="enabled" value="true" />
		    <Setting name="approval" value="true" />
		  </Settings>
		  <LocalVariables />
		  <Tasks>
		    <Task id="1" name="MyTask2" description="" enabled="true">
		      <Setting name="url" value="test1" />
		      <Setting name="param" value="test2" />
		    </Task>
		    <Task id="2" name="Approval" description="" enabled="true" />
		    <Task id="3" name="MyTask2" description="" enabled="true">
		      <Setting name="url" value="https://test" />
		      <Setting name="param" value="value2" />
		    </Task>
		  </Tasks>
		</Workflow>
the MyTask2 is Custom task. i want to get each instance variable from MyTask2.

**Comment by jeremy-xu** [comment]
<Workflow id="101" name="Test_01" description="Test_01" xmlns="urn:wexflow-schema">
		  <Settings>
		    <Setting name="launchType" value="trigger" />
		    <Setting name="enabled" value="true" />
		    <Setting name="approval" value="true" />
		  </Settings>
		  <LocalVariables />
		  <Tasks>
		    <Task id="1" name="MyTask2" description="" enabled="true">
		      <Setting name="url" value="test1" />
		      <Setting name="param" value="test2" />
		    </Task>
		    <Task id="2" name="Approval" description="" enabled="true" />
		    <Task id="3" name="MyTask2" description="" enabled="true">
		      <Setting name="url" value="https://test" />
		      <Setting name="param" value="value2" />
		    </Task>
		  </Tasks>
		</Workflow>

**Comment by jeremy-xu** [comment]
is any way i can store something in each instance of workflow when use the startWithVariables api. so i can get the value from all the tasks of this instance.

**Comment by aelassas** [comment]
With /startWithVariables, you can start a workflow with variables. Here is a sample payload:

```json
{
	"WorkflowId":131,
	"Variables":[
	  {
		 "Name":"restVar1",
		 "Value":"C:\\WexflowTesting\\file1.txt"
	  },
	  {
		 "Name":"restVar2",
		 "Value":"C:\\WexflowTesting\\file2.txt"
	  }
	]
}
```

Here is a sample workflow:

```xml
<Workflow xmlns="urn:wexflow-schema" id="138" name="Workflow_RestVariables" description="Workflow_RestVariables">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
  </Settings>
  <LocalVariables></LocalVariables>
  <Tasks>
    <Task id="1" name="FilesLoader" description="Loading files" enabled="true">
      <Setting name="file" value="$restVar1" />
      <Setting name="file" value="$restVar2" />
    </Task>
    <Task id="2" name="ListFiles" description="Listing files" enabled="true"></Task>
  </Tasks>
</Workflow>
```

**Comment by jeremy-xu** [comment]
![图片](https://user-images.githubusercontent.com/34293558/78009791-1beae180-7374-11ea-9021-47faef7f955c.png)
i can not receive value from restVariables except the first instance of same workflow.

**Comment by aelassas** [comment]
Try this from Run method:

```cs
var list = this.Workflow.RestVariables;
```

Also, can you post your payload?

**Comment by aelassas** [comment]
@jeremy-xu Can you try the v5.4? Can I close this issue?
