### ISSUE TITLE
How to run wexflow on docker with custom Task

### ISSUE THREAD

**Issue by jeremy-xu** [aelassas/Wexflow#199]
where i should put the custom task .dll file when using docker?

**Comment by aelassas** [comment]
Custom tasks are not supported when using Docker for the moment. They are only supported by the .NET version.

What you can do is to clone the repo, open Wexflow's solution and add your custom tasks in the .net core version. In this case, don't forget to reference your custom task in Wexflow.Server project.

**Comment by jeremy-xu** [comment]
> 
> 
> Custom tasks are not supported when using Docker for the moment. They are only supported by the .NET version.
> 
> What you can do is to clone the repo, open Wexflow's solution and add your custom tasks in the .net core version. In this case, don't forget to reference your custom task in Wexflow.Server project.

Is wexflow support linux with custom tasks?

**Comment by aelassas** [comment]
No, custom tasks are not supported in Linux for the moment. Even if you copy .dll and .pdb files to /opt/wexflow/Wexflow.Server, it won't work.
To create your own tasks on Linux, you have to clone the repo, create your custom task in the solution, reference your custom task in Wexflow.Server project then create the .net core package (see .net core installation [script](https://github.com/aelassas/Wexflow/blob/master/setup/setup-linux-dotnet-core.bat)).

**Comment by jeremy-xu** [comment]
> 
> 
> No, custom tasks are not supported in Linux for the moment. Even if you copy .dll and .pdb files to /opt/wexflow/Wexflow.Server, it won't work.
> To create your own tasks on Linux, you have to clone the repo, create your custom task in the solution, reference your custom task in Wexflow.Server project then create the .net core package (see .net core installation [script](https://github.com/aelassas/Wexflow/blob/master/setup/setup-linux-dotnet-core.bat)).

I try the docker way to run custom task and it is work by copy .dll and .pdb files. 
>But i found that the running workflow is remove when restart the docker container using sqlite way.
> The processing workflow can not maintain the status when restart container using sqlite way.
Dose the sqlite store the status of running workflow?

**Comment by aelassas** [comment]
Do you use Dockerfile or Docker Compose?

Also, Try another database system like [MongoDB](https://github.com/aelassas/Wexflow/wiki/MongoDB) for example.

**Comment by aelassas** [comment]
@jeremy-xu I added support for custom tasks to the .net core server. Now, you just have to copy the .dll and it will work. I will publish this feature in the v5.4.

**Comment by aelassas** [comment]
@jeremy-xu I've just released the [v5.4](https://github.com/aelassas/Wexflow/releases/tag/v5.4). Can you test   the .net core version and custom tasks and let me know?

**Comment by aelassas** [comment]
The v5.4 is working fine now regarding custom tasks for both the .net and the .net core version.
