### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by SavaNDragos** [aelassas/Wexflow#2]
Hi,

I might be interested in this kind of project. 
My question is first: what is the cross paltform support? I saw : "Linux: Update Wexflow to work on Linux (Mono) and create a setup project for Linux.". Isn't .net core better?
The only advantage at the moment is: simple for you to work with windows forms; .net core can provide a powerfull web server. So do you plan to migrate to .net core? Also you can control the steps from there.
Other stuff xml is great but json can also work nice. Think on double support? 

Thanks

**Comment by aelassas** [comment]
Hi,

Regarding the cross platform support, I'm going to do the following things:
- Create a console application project that will be used as a daemon under Linux so it will run like a windows service (This concerns the port of the windows service to Linux).
- Create a cross platform GUI (I'll probably use something like Eto.Forms).
- Create an .sh script that installs everything.

That's all.

Regarding JSON, It's a good idea but I have already started with XML and I've done a lot of development so it would be very tough to migrate everything to JSON.

Kind regards,
