### ISSUE TITLE
Wexflow Logs Galore

### ISSUE THREAD

**Issue by janborup** [aelassas/wexflow#2]
**How do we minimize Webflow logs?**
I love Wexflow, but I'm always frustrated when logs is a little to much.
On a server I have about 10 tasks schedule for running each 1 to 5 min.
Theese tasks generates about 1 million log/folder structure in a 2 months period, so I do a lot of clean up on theese logs, only the delete them

**Wexflow needs a log strategy**
Can we make a log strategy setting e.g.
None = No Logs
Minimum = Only last log
Severely = Only last log and log with errors.
All = All logs (like now)

**Alternatively  Logging Frameworks**
We could consider supporting a external.

There are 4 logging frameworks that pretty much dominate the .NET space. Those are [log4net](https://logging.apache.org/log4net/), [NLog](https://nlog-project.org/), [Serilog](https://serilog.net/), and [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1) (only for .NET Core and ASP.NET Core). All of them are great, free, and offer similar functionality.

**Comment by aelassas** [comment]
For logging, I'm using log4net.

For logs, I will add LogLevel setting option to Wexflow engine with the following options:

None = No Logs
Minimum = Only last log
Severely = Only last log and logs with errors
All = All logs (like now)

Is it OK for you?

**Comment by aelassas** [comment]
@janborup I added a new setting to wexflow server called LogLevel with the following options:

* Debug: All logs and debug logs.
* All: All logs without debug logs.
* Severely: Only last workflow log and error logs.
* Minimum: Only last workflow log.
* None: No logs.

You can change this setting in Wexflow.Server.exe.config for .NET:

```xml
<!-- LogLevel: Debug | All | Severely | Minimum | None -->
<add key="LogLevel" value="All"/>
```

And appsettings.json for .NET Core:

```js
"LogLevel": "All",
```

I will publish it in the upcoming version 6.1.
