### ISSUE TITLE
[Linux U18] Can't sign in...

### ISSUE THREAD

**Issue by sriptorium** [aelassas/Wexflow#200]
Hi there,
I've followed all instructions. .NET core, wexflow unziped in /opt, etc
Can see the login page.
But after using credentials (admin/wexflow2018) nothing happens.
Using a clean u18.04.4LTS server (no gui) on a virtualbox VM.
Followed the procedure twice to double check.
Nothing happens at sign in... :/

**Comment by aelassas** [comment]
Did you installed Wexflow's backend (/opt/wexflow/Backend) on a web server (since you're using Ubuntu 18.04.4LTS server edition - no GUI)?

**Comment by sriptorium** [comment]
Thank you for your answer.
Yes, after the normal installation, I did a 
sudo cp -r /opt/wexflow/Backend /var/www/html

lamp installed. 
the vm is on the local network.
By the way, I was surprised to have access to the login from http://machine-ip:8000
and also from http://machine-ip/Backend/index.html
Except the second adress provides a "lost password" link that the first does not have.
Anyway, can't login to both...

**Comment by sriptorium** [comment]
(firewall is open on 80, 443, and 8000)

**Comment by aelassas** [comment]
You need to update Backend/js/settings.js on your web server /var/www/html/Backend and put the following config:

```js
Settings = {
    Uri: "http://machine-ip:8000/wexflow/"
};
```

**Comment by sriptorium** [comment]
Ok, understood. Will do that (after lunch :) ) and let you know.
Thank you.

**Comment by sriptorium** [comment]
Hi. 
Ok, what you suggested didn't work.
I edited /var/www/html/Backend/js/settings.js as suggested.
went back to /opt/wexflow/Wexflow.Server to do an dotnet Wexflow.Server.dll
When going to http://machine-ip:8000/ or http://machine-ip/Backend/index.html
I couldn't log in.

BUT

I did finally succeed in logging in by :
copying the entire wexflow directory to /html (not only Backend as before) :
cp -r /opt/wexflow /var/www/html
then editing /var/www/html/wexflow/Backend/js/settings.js as suggested above.
then launching dotnet Wexflow.Server.dll not from /opt
but from
/var/www/html/wexflow/Wexflow.Server

I then could log in from this adress:
http://{machine-ip}/wexflow/Backend/index.html
(not from http://{machine-ip}:8000/)

Thank you.

**Comment by aelassas** [comment]
Glad that you found the solution.
