### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by smcgrawDotNet** [aelassas/Wexflow#201]
Good day,

Using: .NET (not core); Windows 10; Installed all as admin; PostgreSQL access;

Wexflow Manager will start - runs; Nothing else will load.  For example, I get the Designer webpage with login (login is not processed). Note the page address below: 
file:///C:/Program%20Files/Wexflow/Backend/index.html

Is the server processing the page?

**Comment by aelassas** [comment]
Can you check if the web service is running by opening http://localhost:8000/ on a web browser.

**Comment by smcgrawDotNet** [comment]
Akram,

It is running - I get the API.

Swagger Wexflow

 5.2

[ Base URL: localhost:8000/wexflow ]

http://localhost:8000/swagger-ui/swagger.yaml

Wexflow's RESTful API.
Contact the developer <akram.elassas@gmail.com>
MIT <https://opensource.org/licenses/MIT>
Find out more about Wexflow <https://wexflow.github.io/>

**Comment by aelassas** [comment]
Can you open the developer console of the browser and tell me what error you are getting when you try to log in to the backend.

**Comment by smcgrawDotNet** [comment]
*So, only one error: *
CONSOLE21301: serviceWorker.getRegistrations is rejected due to unsecure
context or host restriction in
file:///C:/Program%20Files/Wexflow/Backend/index.html.

*Per research, I added to trusted on edge (restarted server, etc):*
localhost:8000
HTTPS:8000
Get an *"Unspecified error"* error in the console window - now.

*From the Console*

   1. HTML1300: Navigation occurred.
   index.html (1,1)
   2. CSS3121: The media query -ms-viewport has been deprecated.
   3. 0: Unspecified error.
   login.min.js (60,36)


Unlocalized string: vs_editor_contrib_find_browser_findWidget_13
Add to watches
------------------------------
Copy
------------------------------
Clear Console (Ctrl+L)

**Comment by aelassas** [comment]
Which web browser are you using?

**Comment by aelassas** [comment]
@smcgrawDotNet I've just published a [new version](https://github.com/aelassas/Wexflow/releases/tag/v5.3). Can you uninstall Wexflow, install this new version and check if you still face the same issue?

**Comment by smcgrawDotNet** [comment]
So; good news - bad new,

I downloaded the latest - tried it on all four browsers - the same issue.
I downloaded the source and I"m able to get that to run from VS 2017 - it
is running under 2017's local iisexpress edition. So, I think I'm suffering
some kind of server error when running the package.  I traced your set-up
scripts and can't seem to find anything (limit time to work on that).

By-the-way if you are not using MS telemetry code to track -- you have a
snooping / trojan in your code:  vortex-win.data.microsoft.com - it is an
'exe'.

thanks,

Sam

**Comment by aelassas** [comment]
@smcgrawDotNet Could you tell me what Chrome console says about the error? 

I looked for vortex-win.data.microsoft.com in my code but couldn't find anything. I also analyzed all the source code and all the binaries with Windows Defender but couldn't find anything. Could you tell me where you found it?
