### ISSUE TITLE
imap

### ISSUE THREAD

**Issue by jrose0414** [aelassas/Wexflow#202]
Question:  I need imap support to retrieve attachments from a specific folder.  i see pop3 - how do i get imap attributes set up for mail receiver? Is this adding functionality and a recompile?  Thank you!

**Comment by aelassas** [comment]
MailsReceiver task only supports POP3 for the moment. To implement IMAP, you'll have to update the task to support IMAP. You'll need to add a task setting option protocol=POP3/IMAP. Then, if the setting option protocol is equal to IMAP, you put the code to download the emails and their attachments.

**Comment by aelassas** [comment]
@jrose0414 I added support for IMAP in MailsReceiver task. I will publish it in the v5.3.

**Comment by jrose0414** [comment]
Fantastic!

**Comment by aelassas** [comment]
@jrose0414 I've just published the [v5.3](https://github.com/aelassas/Wexflow/releases/tag/v5.3).  I added support for IMAP in MailsReceiver task in both .NET and .NET Core versions.

**Comment by jrose0414** [comment]
Downloaded and installed. Thank you!
