### ISSUE TITLE
Flowy implemention

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#203]
@aelassas the Flowvy implementation in the v5.3 looks great.

I have tried it out and the new version, and over all it working **GREAT.... very good work.**

I have only found minor improvements missing.
- When task i created, you cannot change header task details like, type etc, but you can enter it, and works fine when creating the new task. 
- JSON is missing ExecutionGraph code
- Flowy not yet ready for designing ExecutionGraph code.
- Browse / search / Cannot search for task id.

Else then it's looking great and much better than the standard up-to v.5.2

/Cheers

**Comment by aelassas** [comment]
@janborup Thanks for your feedback. Glad that you liked the v5.3. Regrding flowy, yes it is not ready for designing the execution graph for the moment. I will take in consideration your feedback in the v5.4.

**Comment by aelassas** [comment]
@janborup I added the execution graph to the json view. Can you check it and tell me how you find it?

**Comment by janborup** [comment]
Hi @aelassas 
The Execution Graph is working fine now and showing in JSON, and i like the Blockly Graph implementation.
GREAT.

**Comment by janborup** [comment]
Now a follow decision (Mayby it should be in a new topic)
What about implementation of the LocalVariables of a workflow?
- Right now this is only able, in XML/JOSN, but should this be made in the designer by Flowy or Blockly ?
If you can made a decision, I could make a mock-up for it, if you like to.

**Comment by aelassas** [comment]
@janborup Please open a new issue for this and tag it as enhancement. We can edit local variables in the editor but not in the designer yet. I think I will add them in the right panel of workflow settings.

**Comment by janborup** [comment]
Extra Flowy designer implementations.
- Suport for Add multiple settings per workflow task.

**Comment by aelassas** [comment]
@janborup I added multiple settings to designer. Can you test it and tell me how you find it?

**Comment by janborup** [comment]
I have tested the support for multible settings, and this works fine. Check 👌

A little enhancement to this topic.
-  When using ex. Selectfile-setting in a task-setting to get the task-number, you cannot see the numbers of the other Flowy tasks, so simply nummerize the tasks in Flowy.   

![image](https://user-images.githubusercontent.com/6866443/79136086-b6a1e200-7db0-11ea-8e76-6ca9f394aedb.png)

**Comment by aelassas** [comment]
@janborup All done. I've just updated the designer with the little enhancement.

**Comment by janborup** [comment]
Thanks the Task-Id, does the trick. 👍

New issue:
There is a layout error in "Mobile"-view, so when entering the designer, the Right-side Workflow-settings popin - is stuck, it's showing even it is slide in or slide out.
Don't think it's new layout error, saw it yesterday also.
Desktop view works fine.
 
**Here is mobile view in Chrome:**
![image](https://user-images.githubusercontent.com/6866443/79139682-084d6b00-7db7-11ea-8fff-f651e3c560ed.png)

**Here is mobile view on iPhone mobile**
![image](https://user-images.githubusercontent.com/6866443/79139999-945f9280-7db7-11ea-8386-230f49c1611e.png)

**Comment by aelassas** [comment]
@janborup I've fixed mobile layout issues in the designer. Can you try again an let me know if it is working fine now?

**Comment by janborup** [comment]
Yep... the **Position: fixed**, solved the issue :-)

I don't see anymore issues in the designer, only some small CSS tidy up like aligning the checkboxes in the settings both in desktop/mobile (see above), but that can always be done.

Case closed.
