### ISSUE TITLE
How to use entities

### ISSUE THREAD

**Issue by mpalladi** [aelassas/Wexflow#21]
Can you provide a sample for using entities , it's not clear from the documentation or samples what their purpose is and how to use them. 

A simple example might be to connect to a database and expose the recordset as a web service, use that endpoint in the next task. Is that what you have in mind when designing the application ?

**Comment by aelassas** [comment]
Entity is an abstract class having the Id of the task as property:

```cs
namespace Wexflow.Core
{
    public abstract class Entity
    {
        public int TaskId { get; set; }
    }
}
```

The entity class is designed to be inherited by other classes such as objects retrieved from a database or a web service or an API or whatever. Then, these objects can be loaded in a task by calling the method Add or AddRange:

```cs
this.Entities.Add(myEntity);
this.Entities.AddRange(myEntities);
```

Then the entities loaded can be selected in other tasks by their task Id as follows:

```xml
<Setting name="selectEntities" value="$taskId" />
```

If you want to use entities, you need to create a custom task with your custom entities.

That's it.

**Comment by HaMster21** [comment]
Never used that before, but sounds interesting 👍
