### ISSUE TITLE
Query Instance of a workflow?

### ISSUE THREAD

**Issue by RingoKam** [aelassas/Wexflow#212]
Is there a way to query for status of an a workflow instance? I have multiple instance running and would like to query the status of each.

Thank you 🙏

**Comment by aelassas** [comment]
You can use http://localhost:8000/wexflow/workflow?w={id} but it will return the status of the first job only. I will add in the v5.4 a function that returns the status by job id.

**Comment by RingoKam** [comment]
thanks for the quick response! How and where are the instances stored? I tried looking them up in the SQL table but can't seem to find it.

**Comment by aelassas** [comment]
They are stored in memory for the moment but I am thinking about storing them in db to enable load balancing on multiple servers sharing the same db. I will let you know about the function returning job status.

**Comment by aelassas** [comment]
@RingoKam I added /job?w={id}&i={guid} to retrieve information of a job of a workflow. I also added /jobs?w={id} to retrieve all jobs of a worfklow. These two new functions will be available in the v5.4. Now, I'm thinking about updating the manager page to include all jobs of a workflow + the ability to stop/suspend/resume each job in a popup.

**Comment by aelassas** [comment]
@RingoKam I've just released the [v5.4](https://github.com/aelassas/Wexflow/releases/tag/v5.4). I added /job, /jobs and jobs view to the manager page in the backend.
