### ISSUE TITLE
Designer: Edit LocalVariables

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#213]
We can edit local variables in the editor but not in the designer yet. I think I will add them in the right panel of workflow settings.

This should be the way to obsolete the Editor view.

**Comment by aelassas** [comment]
@janborup Thank you for opening this issue. I will work on this as soon as possible to make it available for the v5.4.

**Comment by aelassas** [comment]
@janborup I added local variables to the designer. Can you test it on your side and let me know if it's ok? This feature will be available in the v5.4.

**Comment by janborup** [comment]
Hi @aelassas 

The add/edit/delete variables works fine (If you remember to Save the workflow)

**A little error:** If you open workflow 115, and then open workflow 114 - the localvariables from wf 115 is still active in the propoerties.

**Suggestion to Enhancement:**
- A localvariable should maybe be 2 lines, so the most content is revealed
- There should be a warning when open another wf or chance tab/menu, and user not saved the wordflow.

![image](https://user-images.githubusercontent.com/6866443/79082321-2f5b5c80-7d25-11ea-91db-47096817e0d1.png)

**Comment by aelassas** [comment]
@janborup I fixed the issues and updated the style of local variables. Can you test it again and let me know?

> There should be a warning when open another wf or chance tab/menu, and user not saved the wordflow.

Can you open a new issue for this please and tag it as enhancement?

**Comment by aelassas** [comment]
> This should be the way to obsolete the Editor view.

@janborup Now that I have added local variables and multiple settings to the designer, I'm going to remove the editor. What do you think about this?

**Comment by janborup** [comment]
Thumb's up. 👍

I don't use the Editor view anymore.

Med venlig hilsen

Jan Borup Coyle

**Comment by aelassas** [comment]
@janborup Ok thanks. I will remove the editor view.

**Comment by janborup** [comment]
I have test again, and everything works fine now :-)
Case closed
