### ISSUE TITLE
Designer: Autosaving / Warning

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#216]
In Designer, when open another workflow or change/click tab/menu, the workflow is not saved, and you have missed your changes.
The system should AutoSave the changes, or there should be a warning - "Workflow not saved [Save] - {Cancel]"
Autosaving could be a user setting - but default should be "ON".

**Comment by aelassas** [comment]
@janborup I added autosaving popup to the designer. Can you test it and let me know if it is working fine in the diagram view, in the json view and in the xml view?

**Comment by janborup** [comment]
Yep... Saving dialog now works fine on "Browse" open-task, but changing menu-tabs, is still not saving the the Workflow.

![image](https://user-images.githubusercontent.com/6866443/79247665-1795ec80-7e7b-11ea-89bd-96bd9f9614f2.png)

**Comment by aelassas** [comment]
@janborup I added autosaving on tab click. Can you test it and let me know if it is working fine on your side?

**Comment by aelassas** [comment]
@janborup Can I close this issue?

**Comment by janborup** [comment]
Yep .. works fine with tab/menu change also.

Case closed
