### ISSUE TITLE
Designer: Period is not reloaded.

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#217]
When entering a Workflow Period setting, it works fine but it's not reloaded next time opening.

CRON works fine.

![image](https://user-images.githubusercontent.com/6866443/79215483-e4883480-7e4b-11ea-8913-016390bfe462.png)

**Comment by aelassas** [comment]
@janborup I fixed the issue. Can you test again and let me know if it is working fine now?

**Comment by janborup** [comment]
Hi... 

I have ReTestet it on Net.Core, but now I maybe have another problem that crash the server, and think it a problem in the ExecutionGraph.

The Server now starts a custom workflow with a Period settings, but the Workflow breaks, and shut's down, so now.

![image](https://user-images.githubusercontent.com/6866443/79236431-3a210900-7e6d-11ea-9b3d-dc09f98762bd.png)
![image](https://user-images.githubusercontent.com/6866443/79236794-b87dab00-7e6d-11ea-9494-c81986a00c6d.png)

My Breaking Workflow is following.
[workflow-1000.xml.txt](https://github.com/aelassas/Wexflow/files/4475960/workflow-1000.xml.txt)

**Comment by aelassas** [comment]
@janborup I have changed the database. Can you export your custom workflows, remove your database in C:\Wexflow-dotnet-core\Database run Wexflow.Scripts.LiteDB and try again?

**Comment by janborup** [comment]
Yep... Deleting the Database, and the Server starts fine, but is same second i'm, importing the Workflow i think the "Autosave" startes the job with the "One second" periodic, and then the server breaks again, and it will not start up again.

**Comment by aelassas** [comment]
@janborup I will investigate on this issue and let you know.

**Comment by aelassas** [comment]
@janborup I fixed the issue. I've just updated LiteDB to the latest version (5.0.7) and it worked. Can you try and let me know if it is working on your side too?

**Comment by janborup** [comment]
Yep... @aelassas 

That solved the problem, and the Server don't breaks anymore, and Period setting loads fine.
