### ISSUE TITLE
SMB connect/disconnect

### ISSUE THREAD

**Issue by TinuS-OG** [aelassas/Wexflow#219]
Hi

I'm thinking of using Wexflow on a Windows machine. A frequent workflow should do a SMB connect (with the required credentials) to a Share on a Linux machine, check a folder for incoming files, process them, disconnect the SMB connection.

Unfortunately  your Network tasks so far don't serve such a possibility to include the temporary connection to a network share and end the connection after completion.

At the moment probably I will write a small batch script to use it as a workaround.

**Comment by aelassas** [comment]
@TinuS-OG I will try to work on this use case and make it available in the v5.5. For the moment, you can use batch scripts and call them from Wexflow (by using [ProcessLauncher](https://github.com/aelassas/Wexflow/wiki/ProcessLauncher) task).

**Comment by aelassas** [comment]
@TinuS-OG SMB/CIFS is now supported by all the .NET tasks. To connect, simply read the following [documentation](https://github.com/aelassas/Wexflow/wiki/SMB). This new feature will be available in the v5.5.

I also added [FileSystemWatcher](https://github.com/aelassas/Wexflow/wiki/FileSystemWatcher) task for files monitoring. And the good news is that it supports SMB/CIFS too. This new task is also available for .net core.

I added SMB connection on task level to be able to have different SMB connections for the same workflow.

**Comment by aelassas** [comment]
@TinuS-OG Can I close this issue?

**Comment by TinuS-OG** [comment]
Dear Akram
You have developed and released this very appreciated extension of wexflow much too fast for me. I haven't yet had the time to get the v5.5 and look into it. I will work on this feature in the next 2-3 weeks and in case I'll find something, I'll let you know again.

Thank you very much for your ongoing hard work on your project, you're doing great!

Greetings, Martin
