### ISSUE TITLE
SSH connection to execute commands

### ISSUE THREAD

**Issue by TinuS-OG** [aelassas/Wexflow#220]
Hi

I saw your License Page (https://github.com/aelassas/Wexflow/wiki/License) and that you already are using SSH.NET (SSH.NET: An SSH library for .NET written in C# and under MIT license.)

I'm thinking of using Wexflow on a Windows machine. A frequent workflow should monitor the behaviour of a Linux machine. After finding a certain condition, the workflow should initiate a reboot of the Linux machine.

Unfortunately your Network tasks so far don't offer a SSH Task. How about to connect by using SSH to the Linux Machine (User and Password) and initiate some commands (like a reboot, but maybe also others, too), then disconnect again?

**Comment by aelassas** [comment]
@TinuS-OG I will create a new task for running SSH commands. This task will be available in the v5.5. For the moment, you can use powershell scripts and call them from Wexflow (by using [ProcessLauncher](https://github.com/aelassas/Wexflow/wiki/ProcessLauncher) task) to run your SSH commands.

**Comment by aelassas** [comment]
@TinuS-OG I added [SshCmd](https://github.com/aelassas/Wexflow/wiki/SshCmd) task to execute SSH commands. You will be able to reboot a Linux machine from a workflow. This task will be available in the v5.5. I will notify you once I release it.

**Comment by TinuS-OG** [comment]
Hi Akram

Perfect! You were super-fast to implement this extension! Great work you do!

Greetings, Martin

**Comment by aelassas** [comment]
@TinuS-OG Can I close this issue?

**Comment by TinuS-OG** [comment]
Dear Akram
You have developed and released this very appreciated extension of wexflow much too fast for me. I haven't yet had the time to get the v5.5 and look into it. I will work on this feature in the next 2-3 weeks and in case I'll find something, I'll let you know again.

Thank you very much for your ongoing hard work on your project, you're doing great!

Greetings, Martin
