### ISSUE TITLE
Hot folder Workflow Import storage

### ISSUE THREAD

**Issue by TinuS-OG** [aelassas/Wexflow#221]
Hi

In an earlier Version of Wexflow (Wexflow 4.6, Stored workflows in the database for better performance) you switched from a text based storage of the Workflows to a Database based Storage of them.

Before this change, it was possible to update the Workflow's text file with a new Version of it, the engine automatically did load the updated version of the Workflow during its run time. And immediately an updated Version of a Workflow became active.

Such a feature of a 'hot folder Workflow Import storage' would be interesting. This way a Workflow could get updated on a central location, then stored as a text file. Such an updated text file easily could get copied to several remote machines also running with Wexflow Engines. Those engines then would automatically load an updated Workflow. And without further action those would become active.

**Comment by aelassas** [comment]
@TinuS-OG This feature is still available. If you update the workflow from the designer (diagram/json view/xml view), the workflow will be reloaded automatically. You can check this in Wexflow logs. If you have several instances of Wexflow, you can make them share the same database and the reloading of workflows will work from an instance to another automatically. Also, if you import an existing workflow file (json/xml) from the designer, the workflow will be reloaded automatically.

**Comment by TinuS-OG** [comment]
Yes, when a user is using the designer. But interesting would be an update without designer and user at stage.

Like, the backend service is running and checking again (as until Wexflow v4.5) the folder "C:\Wexflow\Workflows\" and would import and activate like a hot folder an updated Workflow (file).

Until then I was able to place an updated Workflow like "C:\Wexflow\Workflows\My_workflow.xml" and the backend engine did read, load and activate such an updated Workflow.

Back until Wexflow 4.5 this was logged like following:
2019-09-04 14:41:13,178  INFO [21] - FileSystemWatcher.OnCreated
2019-09-04 14:41:13,182  INFO [21] - Workflow loaded: {id: 201, name: My_workflow, enabled: True, launchType: Trigger} (C:\Wexflow\Workflows\My_workflow.xml)

And the Wexflow 4.5 Config looked like:
C:\Wexflow\Wexflow.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Wexflow>
  <Setting name="workflowsFolder" value="C:\Wexflow\Workflows" />
...

Such an update/import of Workflows would be helpful. Why? I have no users to import or update a Workflow. I have no stable network connection between the central location (where I could prepare such updates). Therefore all Servers need to run with their own, local DB. But I could send updated text files from the central location to the remote site. And it would be nice if the remote Wexflow engine could pick those arrived XML Workflow files and just import and activate them.

**Comment by aelassas** [comment]
@TinuS-OG  understand what you want. You want me to add a hot folder where if a new file is created or modified it will be imported, saved in the database, started if necessary and scheduled just like in older versions. I will add this feature in the v5.5. What about if the file is deleted from the folder, should we ignore it and do nothing or delete the workflow?

**Comment by TinuS-OG** [comment]
Good point! I think, it makes the most sense to delete the workflow in this case, because there's no other option to do so. of course it would be possible to just disable a workflow by sending a new file. But I'm with you, deleting makes the most sense.

**Comment by aelassas** [comment]
Ok great. I will work on this as soon as possible.

**Comment by aelassas** [comment]
@TinuS-OG I added a hot folder for workflows. Now, if a new file is created or modified it will be imported, saved in the database, started if necessary and scheduled just like in older versions. If the workflow file definition is deleted the workflow is deleted. I also added sync between the designer and the hot folder. If you edit a workflow from the designer, the workflow file definition is updated too automatically. If you delete a workflow from the designer, the workflow file definition is deleted too. If you create a new workflow from the designer a new workflow file definition is created in the hot folder. This feature is interesting for those who just want to work on workflow file definitions instead of the designer. This feature is also interesting if we have multiple Wexflow servers sharing the same hot folder. By default, I added all the workflow file definition samples in the hot folder so that the hot folder is in sync with the database. Of course, you can hide the samples by creating a folder named disabled in the hot folder and place those workflows in it. I added this feature for both .net and .net core. Thus, the hot folder can be used from Windows, Linux or macOS distributions. 

This new feature will be available in the v5.5. I will notify you when I will release the v5.5.

**Comment by TinuS-OG** [comment]
Hi Akram
I'm quite impressed on how fast you have implemented this quite helpful extension!! Even more useful than I was thinking of with the feature of having the hot folder for workflows and the designer always in sync.

You have done a really good job with your Wexflow project, congratulations!

Greetings, Martin

**Comment by aelassas** [comment]
@TinuS-OG It's here! [Wexflow 5.5](https://github.com/aelassas/Wexflow/releases/tag/v5.5) just released 🎉. This version icludes all the features you requested:
- [Hot folder](https://github.com/aelassas/Wexflow/wiki/Hot-folder)
- [SMB/CIFS](https://github.com/aelassas/Wexflow/wiki/SMB) support
- [SshCmd](https://github.com/aelassas/Wexflow/wiki/SshCmd) task for running SSH commands
- [FileSystemWatcher](https://github.com/aelassas/Wexflow/wiki/FileSystemWatcher) task for files monitoring
- [and much more...](https://github.com/aelassas/Wexflow/releases)

If you need some help for creating your workflows, just open new issues and I will be there to help.

**Comment by aelassas** [comment]
@TinuS-OG Did you try the v5.5? Can I close this issue?

**Comment by TinuS-OG** [comment]
Dear Akram
You have developed and released this very appreciated extension of wexflow much too fast for me. I haven't yet had the time to get the v5.5 and look into it. I will work on this feature in the next 2-3 weeks and in case I'll find something, I'll let you know again.

Thank you very much for your ongoing hard work on your project, you're doing great!

Greetings, Martin
