### ISSUE TITLE
Paragraph on email body message

### ISSUE THREAD

**Issue by hersam** [aelassas/Wexflow#223]
How to make a paragraph on the email body message.

Thank you for your great job on wexflow
BR
HerSam

**Comment by aelassas** [comment]
@hersam Just set **isBodyHtml** to true in [MailsSender](https://github.com/aelassas/Wexflow/wiki/MailsSender) task and use CDATA in the xml input file as follows:

```xml
<Mails>
	<Mail>
		<From>from@host.com</From>
		<To>to@host.com</To>
		<Subject>Email subject</Subject>
		<Body>
		<![CDATA[
			<h1>Paragraph title</h1>
			<p>Paragraph text.</p>
		]]>
		</Body>
	</Mail>
</Mails>
```

**Comment by aelassas** [comment]
@hersam can I close this issue?

**Comment by hersam** [comment]
Hi Akram,

I am sorry for the delay to reply.
Thank you very much, it works for me.

You can close this issue.

Thank you to work on this good workflow system

Cheers
Heri Samuel
