### ISSUE TITLE
Failsafe task creation.

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#227]
I think it's time to eliminate some dummy-error, when a user creates a new workflow.

Many tasks have several mandtory entries, some optional and some can be multiple.

When you in designer start drag-drop a task, the entries list is always blank, so you always have to click new setting, fill out, new setting fill out, etc. but you have really no idea what's mandatory, optional or multiples. 

A pre-created entries list (with blank values), with the mandatory entries to a task, could be a start, and the user should not be allowed to save the workflow before these mandatory entries, are filed out. 

This alone will spare a lot of exceptions in the server, and confusing workflows that do not work.

/Cheers

**Comment by aelassas** [comment]
Nice feature. I will try to work on it in a future version. It will require an update in TasksSettings.json and in the designer. But for the moment the only way to avoid errors is to read the documentation and see the workflow samples in the wiki or in Wexflow.

**Comment by aelassas** [comment]
@janborup I added safe task creation to the designer. Can you please test it on your side? You must update C:\Wexflow-dotnet-core\TasksSettings.json to [the following one](https://github.com/aelassas/Wexflow/blob/master/samples/dotnet-core/windows/Wexflow/TasksSettings.json) for .net core. For .net, you must update C:\Wexflow\TasksSettings.json to [the following one](https://github.com/aelassas/Wexflow/blob/master/samples/dotnet/Wexflow/TasksSettings.json).

**Comment by janborup** [comment]
This is much better.  😎

Some small issues.
1. In Task-MailsSender the "EnableSSL" is a requied field, and the server breaks if it's not filled out.
![image](https://user-images.githubusercontent.com/6866443/80501248-81c88a00-896f-11ea-9b0c-823101f8d46f.png)

2. In Task-FileSplitter the "chunkSize" is a required field.

3. In Task-FTP the "server", "port", "user", "password" is required fields.

4. In Task-ProcesLauncher the "hideGui" and "generatesFiles" is required fields.

5. When drag-drop let's say 3 tasks in designer, the task should be auto incremented, starting with #1, #2 and #3, else when saving the server breaks is some tasks has same Id ex. #0, #0, #0
![image](https://user-images.githubusercontent.com/6866443/80501164-665d7f00-896f-11ea-8cff-ff72d1cc8d18.png)
![image](https://user-images.githubusercontent.com/6866443/80501866-3cf12300-8970-11ea-9a35-31bb902e06d7.png)

**Comment by janborup** [comment]
May a suggest a fieldtype validation as well in the TaskSettings.json.
I had changed the file below with the most common types, "taskId", "string", "int" and "bool"
[TasksSettings.zip](https://github.com/aelassas/Wexflow/files/4546830/TasksSettings.zip)

**Comment by aelassas** [comment]
@janborup All fixed. Thanks! Regarding incremental task ids and field types I will work on that in the v5.6. Now, I am working on releasing the v5.5 this week. Keep this issue open for the moment.

**Comment by aelassas** [comment]
@janborup I added incremental task id to the designer. Can you please pull the latest version, test it and let me know if it is working fine on your side? Now, I will work on filed types.

**Comment by aelassas** [comment]
@janborup For field types, I used the following ones: int, string, bool, password and list. For list, I added "List" property that contains the possible values. I will also add field validation. Can you please check [TasksSettings.zip](https://github.com/aelassas/Wexflow/files/4551076/TasksSettings.zip) for .net and let me know if it is correct please?

**Comment by aelassas** [comment]
@janborup I added field type to the designer for both .net and .net core. Please pull the latest version, update your TasksSettings.json by the following [one](https://github.com/aelassas/Wexflow/blob/master/samples/dotnet-core/windows/Wexflow/TasksSettings.json) for .net core and let me know if it is working fine on your side for both field types and incremental id. If you can test .net also, that would be great.

**Comment by aelassas** [comment]
@janborup Can I close this issue?
