### ISSUE TITLE
Is it possible to create a post request sending JSON parameteres to an API REST in Wexflow?

### ISSUE THREAD

**Issue by rocaseres** [aelassas/Wexflow#230]
Good evening, everyone. 
I have some trouble trying to get a file from an API REST. 
What I want to do is to create a post request sending JSON parameteres to an API REST. I don't know if this is possible in Wexflow. 
Thank you.

**Comment by aelassas** [comment]
@rocaseres Sorry this feature is not available yet. I will add it in the upcoming version.

**Comment by janborup** [comment]
@rocaseres 
https://github.com/aelassas/Wexflow/wiki/RESTful-API
You can send JSON POST parameters to the variables of a task, it this a solution for you ?
/Cheers

**Comment by aelassas** [comment]
@rocaseres  I have just released the [v5.6](https://github.com/aelassas/Wexflow/releases/tag/v5.6). It is now possible to create a post request and send JSON payload to an API REST in Wexflow.
