### ISSUE TITLE
Is it possible define to that await for completion of multiple tasks in the Execution Graph ?

### ISSUE THREAD

**Issue by hrkknt20001** [aelassas/Wexflow#231]
Hello.

I find how to branch parallel task to define the Execution Graph under [link.](https://github.com/aelassas/Wexflow/wiki/Samples#execution-graph)
Then I want to know define of Execution Graph to awaiting multiple tasks completion.

Is it possible in the Wexflow ?

Thank you.

**Comment by aelassas** [comment]
@hrkknt20001 You cannot wait for multiple tasks to complete at the same time. You can only wait for task completion task by task.

**Comment by hrkknt20001** [comment]
Thank you.
I understood.
