### ISSUE TITLE
Is there a specific reason or tech constraint why the SQL Tasks are not available in the .NET Core version of the application?

### ISSUE THREAD

**Issue by shrike71** [aelassas/Wexflow#232]
Specifically, the group of tasks listed here:

https://github.com/aelassas/Wexflow/wiki/Tasks-documentation#sql-tasks

It looks like you have full cross-platform support for a number of databases. Since abundant functionality exists in .NET Core and parallel libraries such as Entity Framework to allow these kinds of tasks to run on a .NET Core deployment, I was surprised why this is not available.

We have a number of scenarios which would involve validating file drops and running SQL inserts on the validated data, and vice versa, so the file tasks and SQL tasks are of real interest to us. However, we do not use Windows servers in our environments.

Just wondering why, and if you had a potential workaround before we start dissecting the API and having a look for ourselves.

Outstanding product,

Thanks,

Patrick

**Comment by aelassas** [comment]
@shrike71 I added Sql tasks to .net core in the v5.6. Sql, SqlToCsv and SqlToXml tasks will be available for .net core in the upcoming version.

**Comment by shrike71** [comment]
Thanks for the super quick reply!

Looking forward to the next release

P

**Comment by aelassas** [comment]
@shrike71 I have just released the [v5.6](https://github.com/aelassas/Wexflow/releases/tag/v5.6). Now, Sql, SqlToCsv and SqlToXml tasks are available for .net core and other tasks too.
