### ISSUE TITLE
Task dll dependencies

### ISSUE THREAD

**Issue by gertus** [aelassas/Wexflow#235]
Hi,

I keep getting en error where the dependency dll of my task dll cannot be loaded? 
I even get that when running wex server from Visual Studio and referencing the task dll project and dependency dll project in both WexFlow.Core and WexFlow.Server

Please help :)

-----------------------------------------------------------------------------------------

2020-05-11 23:32:37.132 INFO - [Send Entity Statement / 1] Workflow started - Instance Id: 70f3ea49-424a-4767-8798-f952dbd4eb3e
2020-05-11 23:33:59.888 ERROR - [Send Entity Statement / 1] Workflow started - Instance Id: 70f3ea49-424a-4767-8798-f952dbd4eb3e
System.BadImageFormatException: Could not load file or assembly 'TCubeB, Version=6.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'TCubeB, Version=6.1.0.0, Culture=neutral, PublicKeyToken=null'
at Wexflow.Tasks.EntityStatementEmail.EntityStatementEmail.Run()
at Wexflow.Core.Workflow.RunSequentialTasks(IEnumerable`1 tasks, Boolean& success, Boolean& warning, Boolean& error) in ..\Wexflow.Core\Workflow.cs:line 1314
at Wexflow.Core.Workflow.StartSync(String startedBy, Guid instanceId, Boolean& resultWarning) in ...\Wexflow.Core\Workflow.cs:line 1005

**Comment by aelassas** [comment]
@gertus What are the dependencies of your task?

**Comment by gertus** [comment]
Hi, I have some bussiness layer dll that is required by the task. Like crystal reports etc, to generate a report and then email it out in specific conditions. 

Another enhancement I think would be great is to allow for assembly name to be specified   In config when adding a custom task as I want to have more than one task in one dll. This allow me to version my tasks and group similar tasks in one dll. Current the loader on allow one task and assembly name must match task name;)

Otherwise this is a great peace of software and I think you have done a wonderfull job.

**Comment by aelassas** [comment]
@gertus Just put all the dlls used by your custom task and your custom task in C:\Program Files\Wexflow. This should work. If you want to use it in the source code, reference your custom task and all the dlls used by your custom task in Wexflow.Server project. This should work too.

**Comment by gertus** [comment]
Eventually I found my issue being the 32 vs 64 bit issue. Different project had different settings.
Another question, is there a way to setup a flow, that trigger periodically, to not trigger again until the previous run completed? ie the same flow do not run concurrently in 2 threads? Is this achieved by unchecking "Enable parallel jobs" on designer ?

**Comment by aelassas** [comment]
@gertus Yes, just uncheck  "Enable parallel jobs" and the next job will wait until the previous one has completed.
