### ISSUE TITLE
Sequential workflows runtime

### ISSUE THREAD

**Issue by palmtreefrb** [aelassas/Wexflow#236]
I need to embed Sequential workflows into an existing .net core app. The requirements are that the user will need to add the sequential workflow, and one or many tasks at runtime. Is this functionality available in Wexflow?

Thanks,
Rick

**Comment by aelassas** [comment]
It is possible to load one or many tasks at runtime from **Tasks** folder. It is also possible to load sequential workflows at runtime from the designer or from **Workflows** hot folder.

**Comment by palmtreefrb** [comment]
Thank you for the response. Your answer leeds me to ask another question. The tasks added will be of a datetime, the user will choose a datetime in the future to have the event executed.

Thanks,
Rick

**Comment by aelassas** [comment]
@palmtreefrb Datetime data type is supported but there isn't a date time picker in the designer yet. The user will have to set the date time field in a text box for the moment.
