### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by gertus** [aelassas/Wexflow#238]
Hi,

is this the call use for the bottom section on the dashboard?
http://localhost:8000/wexflow/searchHistoryEntriesByPageOrderBy?s=&from=0&to=99999&page=0&entriesCount=1000&heo=0

**Comment by aelassas** [comment]
@gertus Here is the call used for the bottom section on the dashboard:

http://localhost:8000/wexflow/searchEntriesByPageOrderBy?s=&from=1589472362588&to=1589558762588&page=1&entriesCount=10&heo=1

Here are the request headers:

````
GET /wexflow/searchEntriesByPageOrderBy?s=&from=1589472362588&to=1589558762588&page=1&entriesCount=10&heo=1 HTTP/1.1
Host: localhost:8000
Connection: keep-alive
Authorization: Basic SECRET_KEY
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Accept: */*
Origin: null
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,ar;q=0.6
````

You can also use Swagger UI from a web browser at http://localhost:8000/ to test this API call.

**Comment by gertus** [comment]
perfect, thank you.
