### ISSUE TITLE
Pause WorkFlow

### ISSUE THREAD

**Issue by gertus** [aelassas/Wexflow#239]
Hi, is there a method to pause / delayed a workflow that have started, from within a task in the WorkFlow? Say I have a WF that need to run each month on the 5th, but should the 5 th be on a weekend, then the task need to "pause" and only continue on Monday, similar logic needed for public holidays.?

**Comment by aelassas** [comment]
Yes, you can pause a running instance of a workflow from within a task through [Workflow](https://github.com/aelassas/Wexflow/wiki/Workflow) task. 

Here is a sample workflow that contains a task that pauses a workflow:

```xml
<?xml version='1.0'?>
<Workflow xmlns="urn:wexflow-schema" id="45" name="Workflow_Workflow" description="Workflow_Workflow">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
	</Settings>
	<Tasks>
		<Task id="1" name="Workflow" description="Pausing workflow 41" enabled="true">
			<Setting name="wexflowWebServiceUri" value="http://localhost:8000/wexflow/" />
			<Setting name="username" value="admin" />
			<Setting name="password" value="SECRET_PASSWORD" />
			<Setting name="action" value="suspend" />
			<Setting name="id" value="41" />
		</Task>
	</Tasks>
</Workflow>
```

For the moment there is an issue while pausing a workflow from Workflow task but this will be fixed in the v5.7.

**Comment by gertus** [comment]
So I would need to do the pause via api from within the task also. There is no short cut?;)

**Comment by gertus** [comment]
Would it be possible for you to send me a sample .net program, that can be used to save a new workflow via json, as I cannot get mine working?

Please. I load it via file on the designer, but would like to push it from another application.

 

Last question :) I am also looking for a .net forms application that can help the user build the quarts cron? Any suggestions?

 

Regards

 

 

Gert Cloete

Cell: 082 782 8798

 <mailto:gert@zubatnine.co.za> gert@zubatnine.co.za

 

Zubat Nine (Pty) Ltd

This content of this email, including but not limited to, all designs, text and images remains the property of Zubat Nine (Pty) Ltd (“Zubat Nine”).  The contents hereof are private and confidential.  This email including attached document/s or any part thereof may not be copied, distributed or transmitted in any form or means without the written consent of Zubat Nine.

**Comment by aelassas** [comment]
@gertus Yes, you can use the api also to pause a workflow. There is no shortcut for the moment other than Workflow task and the api.

Regarding json, you can use webclient or httpclient. You must set authorization header. Here are some samples of api calls: https://github.com/aelassas/Wexflow/blob/master/src/net/Wexflow.Core.Service.Client/WexflowServiceClient.cs

Make sure that your json payload is valid before calling the api. To see an example call, you can use json view from the designer or use chrome network tools while saving a workflow from the designer.

**Comment by gertus** [comment]
Thank you for all the quick responses.
I have the api working for reporting etc, but I cannot get my save for the json workflow working. :(
Please paste some complete sample here that just create an approval task via api json save method.

**Comment by aelassas** [comment]
@gertus Here is a complete sample that creates an approval task via JSON API and save method:

```cs
using Newtonsoft.Json.Linq;
using System;
using System.Net;
using System.Security.Cryptography;
using System.Text;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var uri = "http://localhost:8000/wexflow/save";
            var username = "admin";
            var password = "wexflow2018";
            var payload = "{\"WorkflowInfo\":{\"Id\":\"151\",\"Name\":\"Workflow_Approval\",\"Description\":\"Workflow_Approval\",\"LaunchType\":1,\"Period\":\"\",\"CronExpression\":\"\",\"IsEnabled\":true,\"IsApproval\":true,\"EnableParallelJobs\":true,\"LocalVariables\":[]},\"Tasks\":[{\"Id\":1,\"Name\":\"Approval\",\"Description\":\"Waiting for approval\",\"IsEnabled\":true,\"Settings\":[]}]}";
            var webClient = new WebClient();
            webClient.Headers.Add("Authorization", Base64Encode(username + ":" + GetMd5(password)));
            var result = webClient.UploadString(uri, payload);
            var saveResult = JObject.Parse(result);
            var success = saveResult.Value<bool>("Result");
            if (success)
            {
                Console.WriteLine("The workflow was saved with success.");
            }
            else
            {
                Console.WriteLine("An error occured while saving the workflow.");
            }
            Console.WriteLine();
            Console.WriteLine("Press any key to exit...");
            Console.ReadLine();
        }

        static string GetMd5(string input)
        {
            // Use input string to calculate MD5 hash
            using (MD5 md5 = MD5.Create())
            {
                byte[] inputBytes = Encoding.ASCII.GetBytes(input);
                byte[] hashBytes = md5.ComputeHash(inputBytes);

                // Convert the byte array to hexadecimal string
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("x2"));
                }
                return sb.ToString();
            }
        }

        static string Base64Encode(string plainText)
        {
            var plainTextBytes = Encoding.UTF8.GetBytes(plainText);
            return Convert.ToBase64String(plainTextBytes);
        }
    }
}
```

**Comment by gertus** [comment]
Great thank you! I will try / compare to mine in a bit. 

Any ideas on the quarts cron win forms editor?

I must say your support for your product is of a high standard!

Gertus

**Comment by aelassas** [comment]
@gertus You can inspire from [CronMaker](http://www.cronmaker.com) to create your own cron expression builder. You can also inspire from [Cron expression generator - Quartz](https://www.freeformatter.com/cron-expression-generator-quartz.html). But, be aware that Wexflow is using Quartz cron expressions. UNIX cron expressions and Quartz ones are different. in Unix, cron expressions are as follows (minute, hour, day, month, day_of_week, year) whereas Quartz cron expressions are as follows (second, minute, hour, day, month, day_of_week, year). You can find a documentation about Quartz cron expressions [here](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/crontrigger.html). You can also inspire from [jquery-cron](http://shawnchin.github.io/jquery-cron/), a jQuery plugin for building cron expressions. There is no cron expression builder in Wexflow for the moment but you can search on the Web, you may find a C# library that do what you want.

**Comment by janborup** [comment]
hi.
Use launchtype Cron, and this expression "0 0 8 ? 1/1 MON#1 *", that should do your job. 
/Cheers

**Comment by gertus** [comment]
Can you explain how that work to have the correct output? So I can learn?;)

**Comment by gertus** [comment]
This wil force it to next Monday where I am more looking for next business day after date selected if selected date is not a business day. Need to by dynamic as country holiday etc need to be taken into account also;)

**Comment by gertus** [comment]
> @gertus Here is a complete sample that creates an approval task via JSON API and save method:
> 
> ```cs
> using Newtonsoft.Json.Linq;
> using System;
> using System.Net;
> using System.Security.Cryptography;
> using System.Text;
> 
> namespace ConsoleApp
> {
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             var uri = "http://localhost:8000/wexflow/save";
>             var username = "admin";
>             var password = "wexflow2018";
>             var payload = "{\"WorkflowInfo\":{\"Id\":\"151\",\"Name\":\"Workflow_Approval\",\"Description\":\"Workflow_Approval\",\"LaunchType\":1,\"Period\":\"\",\"CronExpression\":\"\",\"IsEnabled\":true,\"IsApproval\":true,\"EnableParallelJobs\":true,\"LocalVariables\":[]},\"Tasks\":[{\"Id\":1,\"Name\":\"Approval\",\"Description\":\"Waiting for approval\",\"IsEnabled\":true,\"Settings\":[]}]}";
>             var webClient = new WebClient();
>             webClient.Headers.Add("Authorization", Base64Encode(username + ":" + GetMd5(password)));
>             var result = webClient.UploadString(uri, payload);
>             var saveResult = JObject.Parse(result);
>             var success = saveResult.Value<bool>("Result");
>             if (success)
>             {
>                 Console.WriteLine("The workflow was saved with success.");
>             }
>             else
>             {
>                 Console.WriteLine("An error occured while saving the workflow.");
>             }
>             Console.WriteLine();
>             Console.WriteLine("Press any key to exit...");
>             Console.ReadLine();
>         }
> 
>         static string GetMd5(string input)
>         {
>             // Use input string to calculate MD5 hash
>             using (MD5 md5 = MD5.Create())
>             {
>                 byte[] inputBytes = Encoding.ASCII.GetBytes(input);
>                 byte[] hashBytes = md5.ComputeHash(inputBytes);
> 
>                 // Convert the byte array to hexadecimal string
>                 StringBuilder sb = new StringBuilder();
>                 for (int i = 0; i < hashBytes.Length; i++)
>                 {
>                     sb.Append(hashBytes[i].ToString("x2"));
>                 }
>                 return sb.ToString();
>             }
>         }
> 
>         static string Base64Encode(string plainText)
>         {
>             var plainTextBytes = Encoding.UTF8.GetBytes(plainText);
>             return Convert.ToBase64String(plainTextBytes);
>         }
>     }
> }
> ```

This works great, In RestSharp you need to add the payload in a specific way, else the server do not detect the body correctly. See options below


Dim req2 As New RestRequest("save", Method.POST)
 AddAuthHeader(req2)
'Working option
 req2.AddParameter("text/json", JsonConvert.SerializeObject(wexRequest), ParameterType.RequestBody)
'Do not work option
'req2.AddParameter("Body", payload)
