### ISSUE TITLE
Is it possible to use OAuth2.0 rather basic authentication.

### ISSUE THREAD

**Issue by Chengal1207** [aelassas/Wexflow#241]
My requirement is, I want to use OAuth2.0 for authentication rather than basic authentication for all the APIs. 
I see the current way of authentication API's are based on Basic authentication.

**Comment by aelassas** [comment]
@Chengal1207 Yes, the current authentication for API calls is Basic Access Authentication. You can use OAuth 2.0 but to do that you must update all the API and this will require a lot of work. I am not planning to do that for the moment but when I will switch to OAuth 2.0 I will let you know.

**Comment by Chengal1207** [comment]
Thank you @aelassas

**Comment by Chengal1207** [comment]
Yes @aelassas, you can close this
