### ISSUE TITLE
Batch processing of long-running task

### ISSUE THREAD

**Issue by hieu-lam** [aelassas/Wexflow#244]
Hi,

I have a workflow that loads all files in a folder and processes them. The workflow has many tasks, some of which are long-running and could last for hours for each file whereas some can be processed pretty fast and ready to move on to the next tasks. This introduced a bottleneck problem where finished files need to wait for other files to be completed before moving on. 

One of the solutions is to re-design the workflow such that it handles only 1 file at a time, and use the `enableParallelJobs` to execute all of them at a time. 

My question is: how does WexFlow handle when the number of files is a million files? Can I safely spawn a million workflow and let WexFlow handles CPU, RAM, resources, queues... by itself without crashing? 

Thanks in advance. I'm open for any solution/suggestions.

**Comment by aelassas** [comment]
@hieu-lam If you have a lot of files to handle, what you can do is to use [FileSystemWatcher](https://github.com/aelassas/Wexflow/wiki/FileSystemWatcher) task in combination with [Workflow](https://github.com/aelassas/Wexflow/wiki/Workflow) or [SubWorkflow](https://github.com/aelassas/Wexflow/wiki/SubWorkflow) tasks and choose async mode. This way, you can process each file in a dedicated thread. You can set enableParallelJobs to true if you want to process files in parallel or to false to enable queuing. To handle errors, you can use OnError and OnWarning [workflow events](https://github.com/aelassas/Wexflow/wiki/Samples#workflow-events).
