### ISSUE TITLE
How to pass output of one task as input of another task without selectFiles? 

### ISSUE THREAD

**Issue by Chengal1207** [aelassas/Wexflow#247]
How to pass output of one task as input of another task without selectFiles? 
E. G: I have custom api's one api output in one task I have to use as input of another task.

**Comment by aelassas** [comment]
@Chengal1207 You can use [shared memory](https://github.com/aelassas/Wexflow/wiki/Custom-tasks#shared-memory) between tasks.

**Comment by aelassas** [comment]
@Chengal1207 can I close this issue?

**Comment by Chengal1207** [comment]
Yes @aelassas, you can close this

**Comment by diegosps** [comment]
Is `SharedMemory` only valid for custom tasks?
If I wanted to do a series of transformations on data, the only way to do it is reading and writing a series of xml files on disk? This would be inefficient.

I'm thinking something like FME from Safe Software.

Maybe that is not what Wexflow is trying to solve and I just missed the point. Sorry.
