### ISSUE TITLE
Request to Approve the Workflow by Manager and above

### ISSUE THREAD

**Issue by Chengal1207** [aelassas/Wexflow#249]
Below are my requirements, As an end-user, I have to place a request to my manager to approve my request.
1. I have to trigger create a new workflow and when I place a leave request from my application this workflow should get triggered. 
2. Once the workflow triggered, the request has to go to my manager for approval with mail. Once, he approves then my request is fulfilled.

Another case:
If the leaves applied are more than 5days then the request goes to my manager's manager once my manager approves.

Can you please suggest some examples here if you have. I tried with the ApproveRecord but still, I am not able to achieve this with the users we have.

**Comment by aelassas** [comment]
>I have to trigger create a new workflow and when I place a leave request from my application this workflow should get triggered.

You can use [Wexflow API](https://github.com/aelassas/Wexflow/wiki/RESTful-API) to do that from your application.

> Once the workflow triggered, the request has to go to my manager for approval with mail. Once, he approves then my request is fulfilled.

You can create a record and use [ApproveRecord](https://github.com/aelassas/Wexflow/wiki/ApproveRecord) task and start the workflow as manager user using [Wexflow API](https://github.com/aelassas/Wexflow/wiki/RESTful-API). You must create a new user in Wexflow for the manager. [Here](https://github.com/aelassas/Wexflow/wiki/Approval-workflows) is a walkthrough on how to use ApproveRecord task.

> If the leaves applied are more than 5days then the request goes to my manager's manager once my manager approves.

This use case is not supported for the moment.

**Comment by Chengal1207** [comment]
@aelassas Thanks for the update. I have one more question.
Is it possible to approve multiple approvers at the same level? Because I was doing some integration work and both the team managers need to approve then only I should proceed to the next step? is it possible?

**Comment by aelassas** [comment]
@Chengal1207 It will be possible in the v5.7. The v5.6 only supports one approver per record.

**Comment by aelassas** [comment]
@Chengal1207 I released the [v5.7](https://github.com/aelassas/Wexflow/releases/tag/v5.7) today. Now, you can have multiple approvers per record. Check out the [documentation](https://github.com/aelassas/Wexflow/wiki/Approval-workflows#all-must-approve).

**Comment by aelassas** [comment]
@Chengal1207 can I close this issue?

**Comment by Chengal1207** [comment]
Thanks @aelassas. you can close this
