### ISSUE TITLE
Date format error

### ISSUE THREAD

**Issue by clvnong** [aelassas/Wexflow#250]
**Describe the bug**
I using docker to run the system. When I try to update record, but get the error message saying that update failed.
I was referred to container log to get more information and I get the actual error message as below:-
System.FormatException: String '19-05-2020 10:49:04' was not recognized as a valid DateTime. 

**To Reproduce**
1. Go to 'Record tab'
2. Click on 'Document'
3. Scroll down to 'click Save'

**Expected behavior**
Should updated successfully.

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Browser Chrome
 - Version 5.6

**Comment by aelassas** [comment]
@clvnong Thank you for reporting this. I reproduced the issue and fixed it. The fix will be available in the v5.7.
