### ISSUE TITLE
FileSystemWatcher - file used by another process

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#252]
Hi

I have FileSystemWatcher flow (Windows Service.net), and sometimes without no clue, the WexFlow make an error "The process cannot access the file <file> because it is being used by another process".

I can rename the file - stil fails.
I can change the file - stil fails.
I can create new files in same folder - Wexflow runs this.
I remove the file, move it back - then WexFlow runs it without fail. 
Even restarting the Wexflow Service, does't work.

```
2020-05-19 15:36:03,271 ERROR [7] - [OIOXML til OIOUBL (SEK) / 1] [Xslt] An error occured while transforming the file e:\C5\C52010\OIOXML\SEK\OIOXML\4014396_7350076370006.xml
System.IO.IOException: The process cannot access the file 'e:\C5\C52010\OIOXML\SEK\OIOXML\4014396_7350076370006.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Xsl.XslCompiledTransform.Transform(String inputUri, String resultsFile)
   at Wexflow.Tasks.Xslt.Xslt.TransformFiles(Boolean& atLeastOneSucceed)
2020-05-19 15:36:03,271  INFO [7] - [OIOXML til OIOUBL (SEK) / 1] [Xslt] Task finished.
2020-05-19 15:36:03,271  INFO [7] - [OIOXML til OIOUBL (SEK) / 1] [FilesMover] Moving files...
2020-05-19 15:36:03,271  INFO [7] - [OIOXML til OIOUBL (SEK) / 1] [FilesMover] Task finished.
2020-05-19 15:36:03,271  INFO [7] - [OIOXML til OIOUBL (SEK) / 1] [FilesRemover] Removing files...
2020-05-19 15:36:03,271 ERROR [7] - [OIOXML til OIOUBL (SEK) / 1] [FilesRemover] An error occured while deleting the file e:\C5\C52010\OIOXML\SEK\OIOXML\4014396_7350076370006.xml
System.IO.IOException: The process cannot access the file 'e:\C5\C52010\OIOXML\SEK\OIOXML\4014396_7350076370006.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Wexflow.Tasks.FilesRemover.FilesRemover.RemoveFiles(Boolean& atLeastOneSucceed)
```

Any suggestions ?

**Comment by aelassas** [comment]
@janborup Can I see your XML workflow definition with FileSystemWatcher task?

**Comment by aelassas** [comment]
@janborup The problem of FileSystemWatcher in .net is that if a new file is created in the watched folder it raises onCreate one time and onChange multiple times in parallel. That's why you're getting this error. The workaround is to either use onCreate event only or use the .net core version. With the .net core version, you will not get this error because PollingFileSystemWatcher only raises one onCreate event if a new file is created in the watched folder. The onChange event is only triggered when a file in the watched folder is getting modified.

**Comment by janborup** [comment]
**Hi @aelassas** 

Here is the WorkFlow.  It's a Wexflow Windows Service Ver. 5.6

`<Workflow xmlns="urn:wexflow-schema" id="201" name="OIOXML to OIOUBL (SEK)" description="Converts OIOXML to OIOUBL (SEK)">
	<Settings>
		<Setting name="launchType" value="startup" />
		<Setting name="enabled" value="true" />
		<Setting name="approval" value="false" />
		<Setting name="enableParallelJobs" value="false" />
	</Settings>
	<LocalVariables />
	<Tasks>
		<Task id="1" name="FileSystemWatcher" description="Scan for files" enabled="true">
			<Setting name="folderToWatch" value="e:\C5\C52010\OIOXML\SEK\OIOXML\" />
			<Setting name="onFileFound" value="2,3,4,5,6" />
			<Setting name="onFileCreated" value="2,3,4,5,6" />
		</Task>
		<Task id="2" name="Wait" description="Wait for file to finished" enabled="true">
			<Setting name="duration" value="00.00:00:02" />
		</Task>
		<Task id="3" name="FilesCopier" description="Kopier filer" enabled="true">
			<Setting name="selectFiles" value="1" />
			<Setting name="destFolder" value="e:\C5\C52010\OIOXML\SEK\ProcessedOIOXML\" />
		</Task>
		<Task id="4" name="Xslt" description="XSLT Converter" enabled="true">
			<Setting name="selectFiles" value="1" />
			<Setting name="xsltPath" value="e:\C5\C52010\OIOXML\PIE_2_OIOUBL.xsl" />
		</Task>
		<Task id="5" name="FilesMover" description="Move converted XSL files" enabled="true">
			<Setting name="selectFiles" value="4" />
			<Setting name="destFolder" value="e:\C5\C52010\OIOXML\Sendes\" />
		</Task>
		<Task id="6" name="FilesRemover" description="Deletes Source XML" enabled="true">
			<Setting name="selectFiles" value="1" />
		</Task>
	</Tasks>
</Workflow>`

**Comment by janborup** [comment]
> .... a new file is created in the watched folder it raises onCreate one time and onChange multiple times in parallel. ...The onChange event is only triggered when a file in the watched folder is getting modified.

If I understand you correctly, I should not use the OnChange... ""

I try change this WF, and give you a reply, if it solves the problem.

/Cheers

**Comment by aelassas** [comment]
@janborup The bug seems to be fixed in the latest version. Can you pull the latest version and test the .net version. I have setup your workflow in Wexflow and tested it. It works fine on my side without any exception.

**Comment by aelassas** [comment]
@janborup I released the [v5.7](https://github.com/aelassas/Wexflow/releases/tag/v5.7) today. Can you please check that this bug is fixed in this version and that your workflow runs without throwing the exception?

**Comment by aelassas** [comment]
@janborup Did you test the v5.7?

**Comment by janborup** [comment]
sorry not tested yet.

Have been on vacation

I will return.

Med venlig hilsen

Jan Borup Coyle

**Comment by aelassas** [comment]
@janborup Are you still facing this issue in the v5.7?

**Comment by janborup** [comment]
Hi @aelassas 

Yes,,, there is still a issue, but i'm not sure precisely how it fails.

I have installed the newest Wexflow Windows.net v.5.7, and
I have a simple... 1.FileWatch.. 2. Wait 3 sec... 3. Copy files.

In some cases when the files are copied, the files copied contains blank, and this is visible to see this is an error, but even sometimes, the files are cut in half, so only half of the filecontent is copied, and this is even worse, because you then got incomplete files copied.

![image](https://user-images.githubusercontent.com/6866443/83119350-e5a9b400-a0cf-11ea-9e33-cb6a3e8fbea6.png)

I think it's maybe a file delay problem, but the file is open for write at the point the FileWatcher detect the file, but it should not handle the file before it's closed.

Does it makes sense ?

**Comment by aelassas** [comment]
@janborup Try to increase the wait timeout and see if it solves your issue.

**Comment by janborup** [comment]
@aelassas 

I'm using this in a production enviroment, so to make sure the files is working, I had to break the workflow into two, so first indentity the files with FileWatcher, copy them, and then move the files, and it it fails moving, I try doing the same again, but there is still no backstop to ensure the file are finished an closed by the other process.

If the FileWatcher could have a "ContinueOnlyOnNotOpenFiles" - I would be GREAT.

/Cheers

**Comment by aelassas** [comment]
@janborup I reproduced the issue and fixed it. I added some updates to your pull request. Now, FSW will wait until the file is not locked in order to trigger the event. Can you try again and let me know if it is fixed on your side too?

**Comment by janborup** [comment]
@aelassas 

Testet lasted source, at it still works fine with the SafeMode in both Windows.Net and .Net Core.

Case closed
