### ISSUE TITLE
WexFlow

### ISSUE THREAD

**Issue by ThinkDevSteve** [aelassas/Wexflow#253]
Hi there,
Two issues:

I don't seem to be able to disable a workflow at all.

In the designer how do I edit an existing Workflow - if I export a workflow I can import it back, but I can't import a workflow that I have saved using Ctrl+S

One Question:

Can I create 1 dll with a load of tasks in it, rather than a dll per task.

Steve

**Comment by aelassas** [comment]
@ThinkDevSteve To disable a workflow, uncheck 'Enabled' checkbox in workflow settings panel on the right side of the designer then press Ctrl+S to save the changes. Regarding the import, I will check it later today but if you save your workflow then export it then import it, it should work. Even if you change your workflow and don't save it, if you export it then import it it should work too. Regarding task dlls, no you cannot put multiple tasks in the same dll. Only one dll per task is possible for the moment.

**Comment by ThinkDevSteve** [comment]
Thanks for the prompt response appreciated.
Straight after I sent the question, I found the Browse button, and from there things started working Ok.
The Export then Import works for me, but not the Save then Import.
