### ISSUE TITLE
API - Workflow Start

### ISSUE THREAD

**Issue by clvnong** [aelassas/Wexflow#254]
**Describe the bug**
The return instance Id always is the previous Id.

**To Reproduce**
1. Go to 'API - Start'
2. Provide Workflow Id '170'
3. Click on 'Execute'
4. Record the instance Id
5. Go to 'API - Jobs'
6. Provide Workflow Id '170'
7. Repeat 1 to 6
8. Will see the error

**Screenshots**
![image](https://user-images.githubusercontent.com/48722009/82405333-26814780-9a96-11ea-8c22-8166b6d86fea.png)

**Comment by clvnong** [comment]
Hi @aelassas,
Correction:-
The response instance Id always not returned the current executed workflow instance when using API-Workflow Start. It always getting previous instance Id randomly.

**Comment by aelassas** [comment]
@clvnong I reproduced the bug and fixed it. The fix will be available in the v5.7. Thank you for reporting this.

**Comment by aelassas** [comment]
@clvnong I released the [v5.7](https://github.com/aelassas/Wexflow/releases/tag/v5.7) today. Can you please check that the bugs that you reported are fixed in this version.

**Comment by clvnong** [comment]
Hi @aelassas, 
It is working fine with version 5.7. Thanks
