### ISSUE TITLE
Enable Parallel jobs in Workflow scalable

### ISSUE THREAD

**Issue by Chengal1207** [aelassas/Wexflow#255]
Is there any limit with the number of jobs we are creating i.e trigger the same approval workflow for 100K users at the same time. How scalable it is to use for production with these many requests at the same time? Any analysis details we have.

Another question, we are using the Thread.Sleep(500) in the approval task. will there be any issues if the workflow is not approved for several days? and what if, we have triggered multiple jobs for the same approval and all are waiting for approval for several days? Is there any performance impact with this?

**Comment by aelassas** [comment]
> Is there any limit with the number of jobs we are creating i.e trigger the same approval workflow for 100K users at the same time. How scalable it is to use for production with these many requests at the same time? Any analysis details we have.

@Chengal1207 No, there is no limit. If you trigger an approval workflow for 100K, there will be a dedicated thread for each user.

Regarding Thread.Sleep, It should do the job even if the approval flow last several days.
