### ISSUE TITLE
while stating the Workflow, how to send the update the settings value inside the tasks dynamically 

### ISSUE THREAD

**Issue by Chengal1207** [aelassas/Wexflow#256]
Steps to reproduce:
I have created a workflow with FilesLoader task as below 
 {
            "Id": 1,
            "Name": "FilesLoader",
            "Description": "Loading mails",
            "IsEnabled": true,
            "Settings": [
                {
                    "Name": "file",
                    "Value": "$mailPath",
                    "Attributes": []
                }
            ]
        }

I have the placeholder for mailPath, this I have to replace while I start workflow with variables like below 
{
  "WorkflowId": 7,
  "Variables": [
    {
      "Name": "mailPath",
      "Value": "C:\\Wexflow-netcore\\WexflowTesting\\Mails\\mails.xml"
    }
  ]
}

But the value of the setting is not not update to "C:\\Wexflow-netcore\\WexflowTesting\\Mails\\mails.xml" it is still mailPath. 

Is it possible to send the value of the setting while starting the workflow with variables

**Comment by aelassas** [comment]
@Chengal1207 If you start your workflow with http://localhost:8000/wexflow/startWithVariables it should work. You can start it from Swagger by opening http://localhost:8000 in a browser.

**Comment by aelassas** [comment]
@Chengal1207 can I close this issue?
