### ISSUE TITLE
Approval Record

### ISSUE THREAD

**Issue by clvnong** [aelassas/Wexflow#257]
**Describe the bug**
Show the wrong approver

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as 'wexflow' user, then create new record and new workflow for ApprovalRecord.
2. Assigned to 'admin' user. Navigate to Approval tab and start the workflow.
3. Logout from 'wexflow', then login as 'admin'.
4. Navigate to Approval tab and make approval.
5. Login back as 'wexflow', then open the record.
6. Will see the approver as 'wexflow'.

**Expected behavior**
Should be shown as 'admin'

**Screenshots**
![image](https://user-images.githubusercontent.com/48722009/82666053-9c88d880-9c67-11ea-91dc-2d10869e76e8.png)

Wexflow Version 5.7

**Comment by aelassas** [comment]
@clvnong Thank you for reporting this. I reproduced the bug and fixed it. The fix will be available in the v5.8.

**Comment by clvnong** [comment]
Thanks @aelassas
