### ISSUE TITLE
API - Start Workflow with variables

### ISSUE THREAD

**Issue by clvnong** [aelassas/Wexflow#258]
Hi @aelassas, 
I had done 2 test on Local Variables.
First test with setup the variable value at designer (hardcoded the value). When run the workflow and it works as expected.
![image](https://user-images.githubusercontent.com/48722009/82753213-83626200-9df6-11ea-8fb8-8854321549e5.png)

Second test I was trying to use API - Start Workflow with Variables. However, I get file not found error.
![image](https://user-images.githubusercontent.com/48722009/82753231-b573c400-9df6-11ea-8358-8090aa7d6446.png)

![image](https://user-images.githubusercontent.com/48722009/82753244-d0decf00-9df6-11ea-9327-71ec9e360ac2.png)

I am not sure what caused this error. Is it due to the incorrect JSON format?

**Comment by aelassas** [comment]
@clvnong No, it is not due to invalid JSON. You must remove the local variables from the workflow settings panel if you want to use REST variables. Once you remove them, it should work as expected.

**Comment by clvnong** [comment]
Hi @aelassas,
Yes, it is working as described. Thanks
