### ISSUE TITLE
Designer - MailSender

### ISSUE THREAD

**Issue by clvnong** [aelassas/Wexflow#259]
Hi @aelassas,
I found the below minor issue on MailSender task:- 
By default if not checked the 'EnableSsl' will hits error when clicked save (Ctrl+S).
If I were checked and un-checked the 'EnableSsl', then the save function will works fine.

**Comment by aelassas** [comment]
@clvnong Thank you for reporting this. I reproduced the issue and fixed it.

**Comment by clvnong** [comment]
Hi @aelassas, Thanks
