### ISSUE TITLE
Designer XML/JSON not Autosaved.

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#260]
If you make changes in XML or JSON view, and just click the [Diagram] button, and click back to XML, all your changes is lost.
Please prompt for Auto save, when doing this.

**Comment by aelassas** [comment]
@janborup All fixed. Can you pull the latest version and test it please? Here are the use cases to test:
1. Edit Xml switch to diagram
2. Edit Xml switch to graph
3. Edit Xml switch to json
4. Edit Json switch to diagram
5. Edit Json switch to graph
6. Edit Json switch to xml

**Comment by janborup** [comment]
Perfect. 🗡️  👌
