### ISSUE TITLE
Docker Hub doc missing a command

### ISSUE THREAD

**Issue by mielune** [aelassas/Wexflow#261]
**Describe the bug**
Looking for the Docker doc on DockerHub, some instructions are missing
Copy of the interne folders failed.

**To Reproduce**
Read the doc and follow instructions.

**Expected behavior**
Copy of the interne folder is working.

**Screenshots**
![image](https://user-images.githubusercontent.com/8350742/83242196-48688180-a19c-11ea-95e1-11a2fabd518a.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: N/A
 - Version: Docker

**Additional context**

**Comment by aelassas** [comment]
@mielune I updated the [instructions](https://hub.docker.com/r/aelassas/wexflow). Thank you for reporting this.

**Comment by mielune** [comment]
After step 3, I think it will be a good practice to add
```
docker stop wexflow
docker rm wexflow
```

**Comment by aelassas** [comment]
@mielune All fixed. I updated Docker Hub instructions.
