### ISSUE TITLE
Is it possible to create a custom task in order to copy a value to a following task?

### ISSUE THREAD

**Issue by rocaseres** [aelassas/Wexflow#262]
Hello,
I tried to download a .zip file using Wexflow.  I didn't have any trouble so far, but I was wondering if it's possible to code this idea I have. Here is what I did:
First, I get the name of the file from an URL. Then, I want to assign that name to an http task, so I can download the file. Is it possible to assign a value (the URL I'm tying to download) from a previous custom task to an http post task? Can I change the hard coded URL variable in the custom task so the following http task can use it? I hope I'm being clear. 
XML FILE (WORKFLOW)
<Workflow xmlns="urn:wexflow-schema" id="151" name="Descarga ZIP" description="Descarga ZIP">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
		<Setting name="approval" value="true" />
		<Setting name="enableParallelJobs" value="true" />
	</Settings>
	<LocalVariables>
		<Variable name="urldelZIP" value="https://s3.amazonaws.com/isv-api/rb_ar/Diaria+-+Dato+Fuente+RB+Argentina+2020-05-30+15.28.01.zip" />
	</LocalVariables>
	<Tasks>
		<Task id="10" name="HttpPost" description="Descarga desde InStoreView" enabled="true">
			<Setting name="url" value="https://api.instoreview.cl/api/v2/download-zone/sales/" />
			<Setting name="authorizationScheme" value="ISVToken" />
			<Setting name="authorizationParameter" value="d2ddfabcd2d742d4bedac86cb12e5a7f" />
			<Setting name="type" value="application/json" />
			<Setting name="payload" value="{  &quot;view_type&quot;: &quot;diario&quot;,      &quot;dates&quot;: [&quot;2020-05-01&quot;, &quot;2020-05-02&quot;, &quot;2020-05-03&quot;, &quot;2020-05-04&quot;, &quot;2020-05-05&quot;, &quot;2020-05-06&quot;, &quot;2020-05-07&quot;, &quot;2020-05-08&quot;, &quot;2020-05-09&quot;, &quot;2020-05-10&quot;, &quot;2020-05-11&quot;, &quot;2020-05-12&quot;, &quot;2020-05-13&quot;, &quot;2020-05-14&quot;, &quot;2020-05-15&quot;, &quot;2020-05-16&quot;, &quot;2020-05-17&quot;, &quot;2020-05-18&quot;, &quot;2020-05-19&quot;, &quot;2020-05-20&quot;, &quot;2020-05-21&quot;, &quot;2020-05-22&quot;, &quot;2020-05-23&quot;, &quot;2020-05-24&quot;, &quot;2020-05-25&quot;, &quot;2020-05-26&quot;, &quot;2020-05-27&quot;, &quot;2020-05-28&quot;, &quot;2020-05-29&quot;, &quot;2020-05-30&quot;, &quot;2020-05-31&quot;],      &quot;views&quot;: [&quot;Unidades&quot;, &quot;Ventas B2B&quot;],      &quot;chain_codes&quot;: [],      &quot;hierarchy&quot;: {            &quot;Canal&quot;: [],            &quot;Cadena&quot;: [],            &quot;Sub Cadena&quot;: [],            &quot;Región&quot;: [],            &quot;Local&quot;: [],            &quot;Descripción Producto&quot;: [],            &quot;EAN&quot;: [],            &quot;SKU&quot;: [],            &quot;Outlet Unique Code&quot;: [],            &quot;Outlet Name&quot;: [],            &quot;Marca&quot;: []            }   }" />
		</Task>
		<Task id="21" name="ISVNombreZIP" description="" enabled="true">
			<Setting name="selectFiles" value="10" />
		</Task>
		<Task id="20" name="Http" description="Descarga desde InStoreView" enabled="false">
			<Setting name="url" value="$urldelZIP" />
		</Task>
	</Tasks>
</Workflow>
CUSTOM TASK 
     public override TaskStatus Run()
        {
            try
            {
                string Pattern = ".zip";
                bool noLeyoArchivos = true;
                foreach (var file in SelectFiles())
                {
                    noLeyoArchivos = false;
                    // Busca el nombre del archivo ZIP 
                    {
                        // Lee todo el contenido del archivo encontrado
                        string contenidoarchivo = File.ReadAllText(file.Path);
                        if (!string.IsNullOrEmpty(file.Path))
                        {
                            bool encontro = Regex.Match(contenidoarchivo, Pattern, RegexOptions.Multiline).Success;
                            if (encontro)
                            {
                                InfoFormat("hay un archivo {0} que tiene el nombre de un {1}.", file, Pattern);
                                var definition = new { download_url = "" };
                                var urlarchivonombreZIP = Newtonsoft.Json.JsonConvert.DeserializeAnonymousType(contenidoarchivo, definition);
                                InfoFormat("La URL del archivo a descargar es {0} .", urlarchivonombreZIP);
                            }
                            else
                            {
                                InfoFormat("No contiene el patron de busqueda {0} en el archivo {1}.", Pattern, file);
                            }
                        }
                    }
                }
                if (noLeyoArchivos == true) // Lista vacia
                {
                    Info("No hay ningun archivo seleccionado en la lista.");
                    return new TaskStatus(Status.Warning);
                }
                else
                {
                    return new TaskStatus(Status.Success);
                }
            }
            catch (ThreadAbortException e)
            {
                Error("Error en tarea de Busqueda de nombre ZIP de ISV", e);
                return new TaskStatus(Status.Error);
            }

**Comment by aelassas** [comment]
@rocaseres No, it's not possible to do that but what you can do is to download your file in your custom task. You can see the source code of HttpPost task to help you do that.

**Comment by rocaseres** [comment]
Ok! Thank you very much
