### ISSUE TITLE
[Request] Add "Run Powershell Script" - Usability feedback

### ISSUE THREAD

**Issue by MostHated** [aelassas/Wexflow#264]
**Is your feature request related to a problem? Please describe.**
Similar to the "Run C# Script", it would be nice to be able to just pop in the path of the Powershell script you want to run and that is that. I still can't seem to get one to run using ProcessLauncher.

Trying to get a script to run in the gui feels very unintuitive. I kept getting errors when trying to save as well, but with no hint of what was wrong. It was not until I looked at the JSON and saw that there were fields that were required it seems, but with no default value, and weren't actually displayed in the GUI.

The process of trying to test your new workflow quickly burns you out due to all of the steps. Having to save, leave the designer to go to manage, scroll all the way to the bottom, select it, hit start, then go to the dashboard, click on the running process to see if there is any log message, repeat, etc. After 4-5 times, I just didn't feel like going through the hassle anymore. It definitely feels like there should be a way to run the process right from the designer and view the log messages all right there. 

Don't get me wrong, this system has amazing potential to do great things. It just feels like there is a good amount of "little things", such as more appropriate feedback on what is wrong, tooltips for the fields as to what is actually supposed to go in there, etc, that are necessary for a solid and intuitive user experience. 

Thanks,
-MH

**Comment by aelassas** [comment]
@MostHated You can run PowerShell scripts using ProcessLauncher task as follows:

```xml
<Workflow xmlns="urn:wexflow-schema" id="214" name="Workflow_PowerShell" description="Workflow_PowerShell">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
		<Setting name="approval" value="false" />
		<Setting name="enableParallelJobs" value="true" />
	</Settings>
	<LocalVariables />
	<Tasks>
		<Task id="1" name="ProcessLauncher" description="Running PowerShelll script" enabled="true">
			<Setting name="processPath" value="powershell.exe" />
			<Setting name="hideGui" value="true" />
			<Setting name="generatesFiles" value="false" />
			<Setting name="processCmd" value="C:\WexflowTesting\PowerShell\script.ps1" />
			<Setting name="selectFiles" />
		</Task>
	</Tasks>
</Workflow>
```

For the manager, just search for your workflow by name or id then select it then click on start to kick it off.
