### ISSUE TITLE
Possible solution 

### ISSUE THREAD

**Issue by rocaseres** [aelassas/Wexflow#265]
Last week, I had an issue. I tried to pass a variable from a task to another one, but @aelassas told me that this was not possible.
So, I kept on trying to solve this and I found a solution.
What I did was to create two workflows. So the first workflow could change a variable from the second one. Here is what I coded:
[ISVConvierteCSV.txt](https://github.com/aelassas/Wexflow/files/4725874/ISVConvierteCSV.txt)

[

](url)
 This is just  a suggestion since it may help somebody.

**Comment by aelassas** [comment]
@rocaseres Thanks for your feedback.
