### ISSUE TITLE
Nested flowchart tasks

### ISSUE THREAD

**Issue by slav-petkov-saorsa** [aelassas/Wexflow#267]
Hi, I have a question. Is it possible to have nested flowchart tasks? For example:

![image](https://user-images.githubusercontent.com/63452375/84042803-36fa5300-a9ae-11ea-9ea7-422e90125b6f.png)

**Comment by aelassas** [comment]
@slav-petkov-saorsa Yes it is possible. You can put a nested flowchart node in another flowchart node but you must do that in the XML definition of the workflow. The JSON definition of a workflow does not support nested flowchart nodes yet. You can also put nested flowchart nodes in workflow events OnSuccess, OnError, OnWarning and OnRejected.

**Comment by slav-petkov-saorsa** [comment]
Thanks for the answer. I'll close the issue now.
