### ISSUE TITLE
I Cant find soure code of Sync Wexflow.Tasks.Sync

### ISSUE THREAD

**Issue by haseres** [aelassas/Wexflow#271]
![captura](https://user-images.githubusercontent.com/63476765/84605966-07e55500-ae78-11ea-90c5-967b4c634411.png)
I tried to look for the file that contains the code which allows Wexflow to Sync, but I could not find it. I am interested in how is this done.

**Comment by aelassas** [comment]
@haseres Sync task was removed since v5.6. [Here](https://github.com/aelassas/Wexflow/tree/865a561b290321d6d562b7da56874c17baf8c40c/src/dotnet/Wexflow.Tasks.Sync) is its source code.

**Comment by haseres** [comment]
Thanks
