### ISSUE TITLE
Setting values not replaced by Rest API JSON object when running multiple instances of same workflow

### ISSUE THREAD

**Issue by allabhanuprakashreddy** [aelassas/Wexflow#272]
Hi @aelassas,

I see Issue when I am running Multiple instances of same workflow.

------------------------------------
1. Created simple Workflow with one task.
2. Override Run method. (I have some computational work which takes time)
3. I have started second instance before first one completed.
4. I see none of the settings values are replaced from Rest API if the first instance is not yet completed.

**Comment by aelassas** [comment]
@allabhanuprakashreddy Where do you update the setting values? and how do you update them?

**Comment by allabhanuprakashreddy** [comment]
Thanks for the quick reply. Below is the sample Workflow I have provided. This is triggered from Swagger (StartWorkflowWithVariables).

<?xml version="1.0" encoding="utf-8"?>
<Workflow id="1232" name="Workflow_Order" description="Workflow_Order" xmlns="urn:workflow-schema">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
    <Setting name="approval" value="false" />
    <Setting name="enableParallelJobs" value="true" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="1" name="Order" description="Order" enabled="true">
      <Setting name="orderID" value="$orderID" />
    </Task>
  </Tasks>
</Workflow>

**Comment by allabhanuprakashreddy** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Workflow id="1232" name="Workflow_Order" description="Workflow_Order" xmlns="urn:workflow-schema">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
    <Setting name="approval" value="false" />
    <Setting name="enableParallelJobs" value="true" />
  </Settings>
  <LocalVariables />
  <Tasks>
    <Task id="1" name="Order" description="Order" enabled="true">
      <Setting name="orderID" value="$orderID" />
    </Task>
  </Tasks>
</Workflow>

**Comment by aelassas** [comment]
@allabhanuprakashreddy you mean that $orderId does not get updated until the first instance finishes. Right?

**Comment by allabhanuprakashreddy** [comment]
@aelassas  Yes you are right.

**Comment by aelassas** [comment]
@allabhanuprakashreddy I reproduced the issue and fixed it. The fix will be available in the v5.8.

**Comment by allabhanuprakashreddy** [comment]
@aelassas Thanks for the update and quick fix

**Comment by aelassas** [comment]
@allabhanuprakashreddy If you are using the .NET version, you can deploy the fix as follows:
1. Stop Wexflow Windows Service
2. Go to C:\Program Files\Wexflow\\
3. Backup Wexflow.Core.dll
4. Copy the new [Wexflow.Core.dll](https://github.com/aelassas/Wexflow/files/4787295/Wexflow.Core.dll.zip) in C:\Program Files\Wexflow\\
5. Start Wexflow Windows Service
