### ISSUE TITLE
Exec Graph  disappears

### ISSUE THREAD

**Issue by haseres** [aelassas/Wexflow#273]
Designer. The Execution Graph, disappears in diagram tab

1. Open Workflow
2. Goto to XML tab view (The Exec Graph dissapeared)
3. Put Execution Graph. Save ok
4. Goto Diagram tab view (I cant save)
5. Return XML tab view. (The Exec Graph dissapeared)
![2_Goto Diagram i cant save](https://user-images.githubusercontent.com/63476765/85289949-92c4e180-b46e-11ea-9476-e193c115fdde.PNG)
![3_Dissapears Exec graph](https://user-images.githubusercontent.com/63476765/85289957-93f60e80-b46e-11ea-8ad9-5c5b1f648c12.PNG)
![1_Added Exec Graph](https://user-images.githubusercontent.com/63476765/85289960-948ea500-b46e-11ea-99ac-ffd7ecccc74f.PNG)

[Workflow_154.txt](https://github.com/aelassas/Wexflow/files/4813288/Workflow_154.txt)

**Comment by aelassas** [comment]
@haseres I reproduced the bug and fixed it. The fix will be available in the v5.8.

**Comment by haseres** [comment]
Thks
