### ISSUE TITLE
If I run this program in non-docker mode, it will cause a series of security problems

### ISSUE THREAD

**Issue by happyqq** [aelassas/Wexflow#274]
Hello，Wexflow
If I run this program in non-docker mode, it will cause a series of security problems
For example, many tasks like “FileMover” that perform file operations on the system. How can I make these tasks run in multi-user mode well?
Is there a safer way to run in multi-user mode?
Thanks。

**Comment by aelassas** [comment]
Are you using the .net or the .net core version? Which security problems are you talking about? What do you mean by multi-user mode?

**Comment by happyqq** [comment]
> Are you using the .net or the .net core version? Which security problems are you talking about? What do you mean by multi-user mode?
I use .net core in Linux。
Suppose an ordinary user uses "FileMover to delete /usr/bin", is this a security issue? What I mean is whether there is a security solution for multi-user mode.
Do you understand what I mean?

**Comment by aelassas** [comment]
Wexflow does not run under sudo in Linux so there are no security problems. If a user wants to delete /usr/bin with Wexflow this is not possible because it requires privileges to delete the content of that folder.

**Comment by happyqq** [comment]
![msedge_hWxqtnlP43](https://user-images.githubusercontent.com/29003131/87304395-56554480-c547-11ea-99a7-4d368efbb76e.png)

If Wexflow is running in the root environment, the system does not perform security checks on root permissions and the environment, he will directly delete a test file under /usr/bin/.

**Comment by aelassas** [comment]
Yes, there might be a security issue if you install Wexflow on Linux as root. For the moment, there are no security checks but what I advise you to do for the moment is to install Wexflow on Linux as non-root user to avoid security problems.

**Comment by happyqq** [comment]
Ok, thanks!
But I hope to see that you can improve the security check of the root environment in the next version. Or now you can explain it in the help document:
  When setting the permissions of /opt/Wexflow, tell the user to log in with a non-root account,
Or create a user with non-root permissions and give this directory non-root permissions.
