### ISSUE TITLE
Build and Debug instructions

### ISSUE THREAD

**Issue by rkramer1964** [aelassas/Wexflow#282]
Are there current, up-to-date instructions on building .net core versions from source and debugging them?  The instructions in Debug Wexflow contain references to c:\ and folders that don't appear in the source tarball.

Thanks!

**Comment by aelassas** [comment]
You only need to copy Wexflow-netcore and WexflowTesting in c:. You can download them from releases page. Make sure that you run Wexflow in Debug mode and not in Mixed mode.

**Comment by rkramer1964** [comment]
So - if you download the wexflow-5.8.zip - at the top level there is a Wexflow-5.8 folder, under that is the folder structure shown on github (samples, setup, src, etc) - there is no Wexflow-netcore nor WexflowTesting,  are you using '-' to separate folders rather than / or \ in your comment?

**Comment by aelassas** [comment]
You should download wexflow-5.8-windows-netcore.zip.

**Comment by rkramer1964** [comment]
Thank you for your help, but that doesn't help me build from the source.  I'd like to be able to use this in a project that requires all open source modules to be buildable from source.  Specifically, I need to build the .net core version and preferably using dotnet build commands instead of VS since VSCode is the preferred editor.

**Comment by aelassas** [comment]
You can be build from source using [dotnet](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build) command on the main project [Wexflow.Server](https://github.com/aelassas/Wexflow/blob/master/src/netcore/Wexflow.Server/Wexflow.Server.csproj).

**Comment by rkramer1964** [comment]
thank you
