### ISSUE TITLE
Unable to save workload with custom task.

### ISSUE THREAD

**Issue by xavidram** [aelassas/Wexflow#296]
I created a custom Task using the Wexflow package in a separate project solution as seen below. I set up the TasksNames.Json as instructed, as well as the TasksSettings.json. I can create a new Workflow and save it without any tasks. But when I add this task into the workflow. The settings fields populate correctly, but upon saving I get an error that the workflow could not be saved.

![image](https://user-images.githubusercontent.com/1348719/99120222-1b7c1f80-25c0-11eb-84d2-8e5572fbaa4b.png)

**The server response is 200 and returns the following payload:**

![image](https://user-images.githubusercontent.com/1348719/99120403-6bf37d00-25c0-11eb-8d99-ca32003af6ec.png)

**The Request payload is as follows:**

![image](https://user-images.githubusercontent.com/1348719/99120497-98a79480-25c0-11eb-93e2-8dc26c71908c.png)

**When I query the logs from the docker container I get the following:**

![image](https://user-images.githubusercontent.com/1348719/99120675-e0c6b700-25c0-11eb-969e-50e02d234047.png)

I named the namespace for the notification Wexflow.Tasks.SendNotification to follow the naming convention specified in the wiki. Any idea as to why the Task can not be loaded? I restarted the docker container that runs the backend when I added the new DLL file for the SendNotification task. The task targets the netcoreapp3.1 TargetFramework

**OS Specifications:**

- Ubuntu server 20.04
- Docker v19.03.13

Containers were set up similarly to docker instructions found [Here](https://github.com/aelassas/Wexflow/wiki/Docker)
All paths work as desired. I set up a separate virtual server following the Docker container instructions to the T and I got the same result. So I am wondering if I missed something at some point.

**Comment by aelassas** [comment]
Did you copy paste the DLL Wexflow.Tasks.SendNotification.dll in ./Wexflow/Tasks/ ?

**Comment by xavidram** [comment]
Yes. I did copy the dll file and then restarted the docker container running the backend just in case.

**Comment by aelassas** [comment]
Ok. You don't need to restart the container. Did you copy the backend and the configuration files and folders from the container to the current folder?

```
$ docker cp wexflow:/opt/wexflow/Backend Backend
$ docker cp wexflow:/opt/wexflow/Wexflow.Server/appsettings.json appsettings.json
$ docker cp wexflow:/opt/wexflow/Wexflow Wexflow
$ docker cp wexflow:/opt/wexflow/WexflowTesting
```

**Comment by xavidram** [comment]
I used a docker compose to spin up the docker containers. For the wexflow server I mounted the volume and pointed it to the `/opt/wexflow` folder. The `Wexflow.Tasks.SendNotifications` was copied into the local file system `/opt/wexflow/Wexflow/Tasks`  folder which the Wexflow.xml looks at. The docker container seems to recognize the files being added because upon doing `docker cp opt_wexflow_1:/opt/wexflow/Wexflow Wexflow` the `Wexflow.Tasks.SendNotifications.dll` file is present in the `Tasks` folder upon copying from the docker container file system.

This is the docker compose:

![image](https://user-images.githubusercontent.com/1348719/99123429-c80cd000-25c5-11eb-89c1-63025ccccc36.png)

**Comment by xavidram** [comment]
So I did some more testing. The issue seems to be with version ` 5.7` and my Custom task. I created a Blank task and added it into the Tasks folder and version 5.7 wouldn't pick it up. It would throw the same error. Then I purged the wexflow docker containers, recreated them with version `5.8` and the blank custom task now gets picked up and is able to be saved in the workflow. My `SendNotifications` tasks does not however, so I think there is something wrong with my task, but now I feel that if I fixed my custom tasks' underlying issue, the Wexflow server should pick it up now as it picked up the blank task. 

I will close this for now. Thank you!

**Comment by xavidram** [comment]
So I added my custom task `Wexflow.Tasks.SendNotifications` into the wexflow-net-core folder under the C drive in order to catch any errors. The task ran successfully without any issues, so now I am looking into why it can't load the Task on the live server.
