### ISSUE TITLE
What is the difference between it and WF?

### ISSUE THREAD

**Issue by 564064202** [aelassas/Wexflow#3]
What is the difference between it and WF?

**Comment by aelassas** [comment]
Hi,

WF is a proprietary solution and comes with a limited number of built-in activities.

What I want to do is to bring an open source alternative with a bunch of built-in tasks that can be used within a workflow.

Here are the strengths of Wexflow vs WF:

- Open source.
- Comes with 29 built-in tasks.
- Worklow events (OnSuccess, OnWarning and OnError).
- Will be possible to add DoIf in DoIf, DoIf in DoWhile, DoWhile in DoIf and DoWhile in DoWhile.
- Will work under Linux and Android (.NET Core/Mono).
- Will be possible to manage workflows in any website through Wexflow Web Manager.

Kind regards,

**Comment by Eliakos** [comment]
Interesting.
What is the current status of the "Will" ? and Is the work still in progress? (as no release in 2018)
