### ISSUE TITLE
Docker Support?

### ISSUE THREAD

**Issue by mrinc** [aelassas/wexflow#3]
Hey guys,

Just stumbled on this project and it looks pretty cool.

You're using net core so could we do a docker image of this?

Instead of having to install the services on a machine, we can just spin up a single or multiple containers and be OS independent.

**Comment by aelassas** [comment]
@mrinc Docker is supported. You can follow these [instructions ](https://github.com/aelassas/wexflow/wiki/Docker) to build and run Wexflow Docker image.
