### ISSUE TITLE
how to debug custom task

### ISSUE THREAD

**Issue by dibugreen** [aelassas/Wexflow#30]
pls help me.. how to debug custom task .
thx for any  #help

**Comment by aelassas** [comment]
Hi,

To debug custom tasks, you can use [logging](https://github.com/aelassas/Wexflow/wiki/Custom-tasks#logging).

You can also fork and clone this repository and open Wexflow.vs2017.sln or Wexflow.vs2010.sln in Visual Studio and follow these [guidelines](https://github.com/aelassas/Wexflow/wiki/Debug) to debug Wexflow Windows Service. Then, you can create your custom task in the solution and debug it. Of course, to debug it you have to proceed as follows:

1. Create your custom task
2. Reference your custom task in Wexflow.Clients.WindowsService
3. Create a workflow using your custom task (see the [documentation](https://github.com/aelassas/Wexflow/wiki/Custom-tasks#general))
4. Place your workflow in C:\Wexflow\Workflows
5. Open Wexflow Manager or Wexflow Web Manager and trigger your workflow from there

Regrads,

**Comment by dibugreen** [comment]
i'm newbie in c#
thx for help sir

**Comment by aelassas** [comment]
Hi,

Did you succeed debugging your custom task? can I close this issue?

Regards,
