### ISSUE TITLE
API architecture to trigger workflows

### ISSUE THREAD

**Issue by ankurmalhotra89** [aelassas/Wexflow#33]
i just scrolled through the documentation. Couldn't find any ways to integrate workflows through api's.

I intend to trigger certain workflows from my custom screens, i dont want to use the wexflow html web designer.

**Comment by aelassas** [comment]
Hi,

Here is the REST API:

Get the list of workflows (GET): http://localhost:8000/wexflow/workflows
Start a workflow (POST): http://localhost:8000/wexflow/start/{id}
Stop a workflow (POST): http://localhost:8000/wexflow/stop/{id}
Suspend a workflow (POST): http://localhost:8000/wexflow/suspend/{id}
Resume a workflow (POST): http://localhost:8000/wexflow/resume/{id}
Get a workflow (GET): http://localhost:8000/wexflow/workflow/{id}

Refards,

**Comment by ankurmalhotra89** [comment]
Thanks, any link of documentation would be really helpful.
Although, your answer is really helpful. I was also looking for fetching the current completion percentage of a workflow( as in the tasks in a workflow that are currently running/waiting along with the tasks that have completed .

thanks

**Comment by ankurmalhotra89** [comment]
Is there a way to fetch the current progress and status of the individual tasks in a workflow through APIs ?

**Comment by ankurmalhotra89** [comment]
Is there a way to fetch the current progress and status of the individual tasks in a workflow through APIs ?

**Comment by janborup** [comment]
[](https://docs.microsoft.com/en-us/aspnet/web-api/overview/older-versions/build-restful-apis-with-aspnet-web-api)

Hi Zouzbil

Tak a look at above MS link, at go trough the exercises, it shuold help you, and then use above ApiCalls to activate your Wexflow.

/Chears

**Comment by slega** [comment]
Hi @aelassas, do you have OpenAPI / RAML specification for these APIs: https://github.com/aelassas/Wexflow/wiki/RESTful-API ?

**Comment by aelassas** [comment]
@slega No I don't have RAML specification of Wexflow RESTful API.
