### ISSUE TITLE
Are converging tasks possible?

### ISSUE THREAD

**Issue by ankurmalhotra89** [aelassas/Wexflow#35]
Task 3 will run when Task1 and Task2 are completed(successfully)
Is this possible?

Also, why are parallel tasks not possible. Any specific design limitation?

![image](https://user-images.githubusercontent.com/6507285/32855097-d56cfc92-ca66-11e7-88f8-8aae04166270.png)

**Comment by HaMster21** [comment]
Task 3 running after successful execution of task 1 and 2 can be modeled with Flowchart workflows. With the `If` structures in the workflow you can state your intent. See also [the docs here](https://github.com/aelassas/Wexflow/wiki/Samples#if)

Also: the image you posted is describing the execution graph of a workflow that would run task 2 and 3 in parallel. You can do that by setting the parent of both tasks to task 1 in the execution graph. Your parallel tasks workflow is described as the last example [here](https://github.com/aelassas/Wexflow/wiki/Samples#execution-graph)

**Comment by ankurmalhotra89** [comment]
I asked because there is mentioned that Parallel tasks are prohibited.(https://github.com/aelassas/Wexflow/wiki/Samples#execution-graph)

Also, just to verify, Both my above use cases are not possible from the web manager provided. Right?

**Comment by aelassas** [comment]
Hi,
Task 3 will run when Task1 and Task2 are completed(successfully):

```xml
<ExecutionGraph>
	<Task id="1"><Parent id="-1" /></Task>
	<Task id="2"><Parent id="1" /></Task>
	<OnSuccess>
		<Task id="3"><Parent id="-1" /></Task>
	</OnSuccess>
</ExecutionGraph>
```

Parallel tasks not possible by design. I did not implement this feature. Maybe, I'll do it in a future version.

Regards,

**Comment by ankurmalhotra89** [comment]
So it means that the other comment **"You can do that by setting the parent of both tasks to task 1 in the execution graph"** is incorrect right?

Also, **Task 3 will run when Task1 and Task2 are completed(successfully)** -> this not possible from the Web designer ryt?

**Comment by aelassas** [comment]
> So it means that the other comment "You can do that by setting the parent of both tasks to task 1 in the execution graph" is incorrect right?

Yes.

> Also, Task 3 will run when Task1 and Task2 are completed(successfully) -> this not possible from the Web designer but only possible by changing the xml right?

Yes, you have to edit the workflow XML file for this.
