### ISSUE TITLE
FTP Task Issue

### ISSUE THREAD

**Issue by mpalladi** [aelassas/Wexflow#38]
I am trying to upload to the file service Box - which provides an ftp service, ftp.box.com
Via the windows command line - works fine

i.e standard ftp , clear username and password
C:\Users\mark>ftp ftp.box.com
Connected to ftp.box.com.
220 Service ready for new user.
530 Access denied.
User (ftp.box.com:(none)): it.admin@Optimate.net.au
331 User name okay, need password for it.admin@Optimate.net.au.
Password:
230 User logged in, proceed.
ftp> cd "/R&D/Software Source/FORGE/FORGE-DEVELOPMENT-PRJ Backups/"
250 Directory changed to /R&D/Software Source/FORGE/FORGE-DEVELOPMENT-PRJ Backups
ftp>

I have configured the task to replicate this

    <Task id="160" name="Ftp" description="FTP to Box" enabled="true">
      <Setting name="selectFiles" value="150" />
      <Setting name="command" value="upload" />
      <Setting name="protocol" value="ftp" />
      <Setting name="server" value="ftp.box.com" />
      <Setting name="port" value="22" />
      <Setting name="user" value="it.admin@optimate.net.au" />
      <Setting name="password" value="xxxxxxx" />
      <Setting name="path" value="&quot;/R&amp;D/Software Source/FORGE/FORGE-DEVELOPMENT-PRJ Backups/&quot;" />
      <Setting name="retryCount" value="2" />
      <Setting name="retryTimeout" value="10" />
    </Task>

Here is the error

2017-11-19 19:00:44,135  INFO [18] - [Copy FRG files to Temp the Box / 1] [Ftp] Processing files...
2017-11-19 19:00:59,249  INFO [18] - [Copy FRG files to Temp the Box / 1] [Ftp] An error occured while processing the file E:\Temp\BoxTransfer\_AllProjects.170713.165050.Frg. Error: Timed out trying to connect!. The task will tray again.

**Comment by mpalladi** [comment]
Here is the further transcript of the manual ftp put
230 User logged in, proceed.
ftp> put _AllProjects.170213.102335.Frg
200 Command PORT okay.
150 File status okay; about to open data connection.
226 Transfer complete.
ftp: 36546 bytes sent in 0.41Seconds 88.28Kbytes/sec.
ftp>

**Comment by HaMster21** [comment]
Can you make sure that your manual connection uses ftp and not ftps or sftp? Those would require different ports. Most clients would upgrade connections to higher security if possible, Wexflow doesn't as far as I know.

**Comment by mpalladi** [comment]
I have tried - with the same problem, the public domain ftp server speedtest.tele2.net, path /upload
user anonymous.

Can someone else try this - it's also not working for me.

**Comment by mpalladi** [comment]
I am going to close this - just something with the Box ftp service. I tested it with https://dlptest.com/ftp-test/ and works. It does not work with tele2, as they auto delete uploaded files.

**Comment by HaMster21** [comment]
@aelassas 
Maybe this is an issues with active/passive mode?

**Comment by mpalladi** [comment]
Not wanting this to get the better of me I identified the following bug

When using command line ftp - the upload directory needs to be quoted i.e "R & D" but whilst accepted in the designer, it's incorrect syntax for WEX. Consider Trim("""") in the code
