### ISSUE TITLE
Workflow Cron Scheduling

### ISSUE THREAD

**Issue by mpalladi** [aelassas/Wexflow#39]
Would it be possible to integrate the Quartz.Net Cron Scheduler to allow for more flexible scheduling options.

https://www.quartz-scheduler.net/index.html

Would also allow for simplification of workflows that currently have to switch based on day, for exmple

**Comment by aelassas** [comment]
Hi,

I've used Quartz.NET in the new [version 2.7](https://github.com/aelassas/Wexflow/releases/tag/v2.7) and added cron scheduling.

Kind regards,
