### ISSUE TITLE
Documents Approval Workflow

### ISSUE THREAD

**Issue by JTrotta** [aelassas/Wexflow#4]
Hello
this question is not related to any issues. I just need to know if it is possible to create a Documental workflow, something like: 
Create a Doc -> First Doc Approve -> Second Doc Approve -> Doc Approved 
or
Create a Doc -> First Doc Approve -> Second Doc Reject-> Doc restart process -> First doc Approve ->  Second Doc Approve -> Doc Approved

Thank you
JJ

**Comment by aelassas** [comment]
Hi,
There are no built-in tasks for documents approval but you can create your own custom tasks where you can put the logic that you want for documents approval.
Regards,
