### ISSUE TITLE
About MailSender

### ISSUE THREAD

**Issue by atimhome** [aelassas/Wexflow#44]
Sometimes I don't need to cc to others , but the code have to do that.
If I remove the cc tag, it will return the error.

**Comment by bryanvam** [comment]
also add a bcc option. make cc and bcc optional

**Comment by aelassas** [comment]
If you add the cc tag and leave it empty, do you still have the error?

**Comment by aelassas** [comment]
I've fixed the issue in the new version [2.5](https://github.com/aelassas/Wexflow/releases/tag/v2.5).
