### ISSUE TITLE
How to use If inside If into the ExecutionGraph

### ISSUE THREAD

**Issue by arashbahreini** [aelassas/Wexflow#45]
Hi, I have Several Tasks which all of them are condition ( return true of false )
I created my Tasks using custom Task guid and they are working without any error.
The problem is I don't know how to create its execution graph. Whatever I am trying to do is as below.

```
  <ExecutionGraph>
	<If id="100" parent="-1" if="10">
		<Do>
			<If id="101" parent="-1" if="2">
				<Do>
					
				</Do>
				<Else>
				
				</Else>
			</If>
		</Do>
		<Else>
			<Task id="3"><Parent id="-1"/></Task>
		</Else>
	</If>
  </ExecutionGraph>
```

Error : System.Exception: 'Startup node with parentId=-1 not found in DoIf>Do execution graph.'

**Comment by benjstern** [comment]
What was the solution for this? I was wondering the same thing.
