### ISSUE TITLE
No 64-bit version of Wexflow

### ISSUE THREAD

**Issue by NicoleTedescoCalvIO** [aelassas/Wexflow#47]
I assume that small IoT devices are running 64-bit processors these days.  Wexflow is not built for 64-bit operating systems.  Should it be?

**Comment by aelassas** [comment]
The version available for download is a 32 bit version. If you want a 64 bit version, you'll need to download the source code, compile it in 64 bit mode in visual studio then generate the setup file with inno setup.

**Comment by aelassas** [comment]
I'll create an x64 installer it in the upcoming version 2.6.

**Comment by aelassas** [comment]
I've created a 64 bit version of Wexflow and a 64 bit installer in the new version [2.6](https://github.com/aelassas/Wexflow/releases/tag/v2.6).
