### ISSUE TITLE
WebService

### ISSUE THREAD

**Issue by IYoni** [aelassas/Wexflow#5]
Wexflow webservice couldn't connect from my phone while I am testing.

**Comment by aelassas** [comment]
Hi,

Could you please proceed as follows:

1. Open the port 8000 in your firewall
2. Open the following address in a browser on your phone: http://your-windows-machine-name:8000/wexflow/workflows (If the result is a JSON array then the webservice is working.)
3. Set the address http://your-windows-machine-name:8000/wexflow/ as the webservice uri in the android app settings. (this is described in the [documentation](https://github.com/aelassas/Wexflow/wiki/Installation#android))
4. Close Wexflow android app then start it again.

Regards,
