### ISSUE TITLE
Xml agnostic

### ISSUE THREAD

**Issue by dazinator** [aelassas/Wexflow#58]
Consider decoupling tasks from XML, and instead, use some provider model, of which their could be implementations for other backing stores. For example, perhaps workflows could be persisted to mongodb via a mongo provider etc. This provider could be configured.

**Comment by aelassas** [comment]
Nice feature. I'll think about that in future versions.

**Comment by aelassas** [comment]
Workflows are now stored in [DB](https://github.com/aelassas/Wexflow/wiki/Databases) (MongoDB is supported). JSON format is now supported as well.
