### ISSUE TITLE
SqlToCsv -> Oracle Dependency (Even using Sql Server)

### ISSUE THREAD

**Issue by iquirino** [aelassas/Wexflow#59]
Hi guys!

I'm using SqlServer and i dont have the Oracle Client installed on execution machine.

I can suggest you to replace Oracle.DataAccess with Oracle.ManagedDataAccess:
https://www.nuget.org/packages/Oracle.ManagedDataAccess/

The managed driver does not need any installation and other dependencies.
So you can only install wex and run oracle without needs of installing oracle client driver.

If you agreed with this, i can help you to change it to Managed Driver.
I'm very interested on your project, i'm working on a software like this for 5 years on my work company (closed solution).

[SqlToCsv] An error occured while executing sql script. Error: Could not load file or assembly 'Oracle.DataAccess, Version=4.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. An attempt was made to load a program with an incorrect format.

    <Task id="1" name="SqlToCsv" description="SQL Server" enabled="true">
      <Setting name="type" value="sqlserver" />
      <Setting name="connectionString" value="Data Source=sqlserver01;Initial Catalog=IntegrationServices;Integrated Security=True" />
      <Setting name="sql" value="select IdStatus, count(*) from Table01 group by IdStatus" />
    </Task>

Regards,
Igor Quirino

**Comment by aelassas** [comment]
Check out the [v2.7](https://github.com/aelassas/Wexflow/releases/tag/v2.7). Thanks for the pull request!

**Comment by aelassas** [comment]
Hi,

Can I close this issue?

Regards,
