### ISSUE TITLE
Add some label to issues.

### ISSUE THREAD

**Issue by iquirino** [aelassas/Wexflow#63]
I recommend you to add some label issues like:
 - Bug
 - Feature

I recommend this article:
https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

I have some feature requests to add, like:
 - Replace XElement xml reading with Xml Deserialization
    - This will allow us to create Wexflow Storage plugins and persist its workflows to database or cloud repositories
      - This will allow create a SaaS product of WexFlow
 - Choose/define csv output filename format
 - Choose/define output artefacts filename format
 - Create a template defined system to generate artifacts, like: Read a csv and translate it to a SQL statement execution and then execute each rows generated.
 - Read Csv rows and cells and use it on another tasks as execution variables.
 - Create a interchangeable memory to pass objects to another tasks (not using files, only memory)
    - This will enable Map/Reduce tasks
 - Create AutoHotkey like tasks (https://autohotkey.com/)
 - Replace Workflow Thread to a System.Threading.Task and then return it to Workflow.Start
    - This will enable wait Workflow for finish on tests without waiting it status get !IsRunning waiting 100 miliseconds

If you are agreed, i will help you to develop this features requested, ok?

I'm happy to use your software, thank you!
Nice implementation idea!

Regards,
Igor Quirino

**Comment by iquirino** [comment]
If you are agreed, i will open this features requests separated to start develop.
Please mention which you are agreed or not, okay?

Thank you!

**Comment by aelassas** [comment]
Hi,

I'm open to feature requests. I recommend you to play with Wexflow and read some parts of the code so you can contribute to improve it. Don't hesitate to ask me questions about the code or feature requests.

Also, I suggest you open a new issue for each feature so we can discuss about it and how you can contribute through pull requests.

Thank you.

**Comment by aelassas** [comment]
Hi,

Here are my answers:

**Replace XElement xml reading with Xml Deserialization**
-> I'll work on this.

**Choose/define csv output filename format**
-> What do you suggest?

**Choose/define output artefacts filename format**
-> What do you suggest?

**Create a template defined system to generate artifacts, like: Read a csv and translate it to a SQL statement execution and then execute each rows generated.**
-> I think I will create a new task named CsvToSql that will support sql server synthax only. Do you agree?

**Read Csv rows and cells and use it on another tasks as execution variables.**
-> How will you this?

**Create a interchangeable memory to pass objects to another tasks (not using files, only memory)**
-> There is already a [hashtable<string, object>](https://github.com/aelassas/Wexflow/wiki/Custom-tasks#hashtable) as memory for tasks. Is this what you want?

**Create AutoHotkey like tasks (https://autohotkey.com/)**
-> Please explain what and how.

**Replace Workflow Thread to a System.Threading.Task and then return it to Workflow.Start**
-> will suspend, stop and resume still work?

**Comment by aelassas** [comment]
Hi,

I created a new task named [CsvToSql](https://github.com/aelassas/Wexflow/wiki/CsvToSql) that converts CSV files to SQL scripts (Insert - SQL server only).

[Here](https://github.com/aelassas/Wexflow/commit/d5c5ddb56cc21ec2e1317cbd37bb7154df04d435) is the commit.

If you want to test it, you'll have to update your repository and create the workflow in C:\Wexflow\Workflows and add a CSV file in C:\WexflowTesting\CsvToSql. You'll find them in the documentation of the task.

Is this one of the feature you wanted to add in Wexflow?

Regards,
