### ISSUE TITLE
Task timeout and Task retries

### ISSUE THREAD

**Issue by vsiddu** [aelassas/wexflow#64]
Hi,

Currently trying to use Wexflow for automation of some tasks which runs frequently.
But have few questions with implementing below functionality.Hope anyone can help me. 
1. Timing out running task if it doesnt complete in certain time limit.
2. Retrying same task if it fails 
3. how to create a lock on a resource, so that only one task work on the resource. 

Thank you

**Comment by aelassas** [comment]
Retries are only available in [Ftp](https://github.com/aelassas/wexflow/wiki/Ftp) task. Retries and timeouts are not available in other tasks. For which other tasks do you need retries and timeouts?

Regardings resource locks, can you provide an example so I can understand what you need?

**Comment by vsiddu** [comment]
Thanks for your reply. 
Sorry if I'm not clear on my requirements.
Instead of specific tasks, it would be better, if it is a basic functionality of Task. If a task fails retry it for a certain number of times( default 1).  Also same with time out, if a task is not completed within the timeout value(if specified), fail the task.
2. Regarding Locks, what I meant is like locks we use in threads. For example, when a workflow is started, we acquire (create if it does not exist) a lock with a name. if someone else triggers the same workflow, it will try to acquire the same lock, since the lock is already acquired, the second instance of the workflow will wait till the first workflow completes or it will time out

**Comment by aelassas** [comment]
I added these features to the roadmap. I will try to add them later.

**Comment by vsiddu** [comment]
Great. Thank you.

**Comment by aelassas** [comment]
@vsiddu I have just released the [v7.7](https://github.com/aelassas/wexflow/releases/tag/v7.7) with task retries feature. Now, you can find this feature in the designer for retrying tasks in case of failure. When you create or open a workflow in the designer you will find  the options `Task Retries` and `Task Retries Timeout (ms)` on the right panel.

For resource lock and task timeout, I will to try to add them later.
