### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by aelassas** [aelassas/Wexflow#64]
Hello,

I need new feature ideas in order to improve and enhance Wexflow. Whether, It's about the architecture, Wexflow Server, Wexflow Engine, Wexflow Manager, Wexflow Web Manager, Wexflow Android Manager, Wexflow Web Designer or the built-in tasks.

If you have any brand new idea please leave a comment in this issue.

Best regards,
Akram.

**Comment by huzhiguan** [comment]
Hi! I'm not sure if this is already been done or not, but is there a way we can distribute tasks to multiple machines?

**Comment by wexflow** [comment]
Hi,

Wexflow does not support this feature at the moment but it's a good feature request.

Thank you for your feedback,
Akram.

**Comment by aelassas** [comment]
Hi,

Wexflow does not support this feature at the moment but it's a good feature request.

Thank you for your feedback,
Akram.

**Comment by rvs76** [comment]
Hi,
My Ideas :
- Mandatory for business use : SECURITY (log in, profiles,...)
- A SQL Connection task reusable for the others SQL tasks
- Global variables at server level for multiple platform (Dev,Test, Prod) 
- Possibilty to reuse task in another workflow in designer (buttons save and load in the task ?)
- A version .NET Core for Linux, even a limited one.

Mes Idées :
 - Obligatoire pour une utilisation en entreprise : SÉCURITÉ (Connexion, profils,...)
- Une task SQL Connexion pouvant être réutilisée par les autres tasks SQL
- Des variables globales au niveau serveur afin de permettre un déploiement sur plusieurs serveur (Dev, Test, Prod par exemple)
- La possibilité de réutiliser une task dans un autre workflow dans le designer (boutons Save et Load dans la tâche ?)
- Une version .NET Core pour Linux, même limité.

Best Regards,
Hervé.

**Comment by aelassas** [comment]
Bonjour Hervé,

Voici mon retour sur vos idées:

- En ce qui concerne la sécurité (connexions, utilisateur, profils...) : Cette fonctionnalité sera implémentée dans la version 3.0. Je vous tiendrais au courant quand elle sortira.
- En ce qui concerne la task SQL, il est possible de créer des tasks customisées et utiliser dedans la [mémoire partagée](https://github.com/aelassas/Wexflow/wiki/Custom-tasks#hashtable) et passer dedans la SQL connection qui sera réutilisé par d'autres task customisées. Mais en ce qui concerne les task SQL créées par défaut, il n'est pas possible d'intégrer cette fonctionnalité.
- En ce qui concerne les variables globales au niveau serveur, est-ce que vous pouvez me donner des exemples pour comprendre comment ça pourrait être implémenté dans Wexflow.
- En ce qui concerne la possibilité de réutiliser une task dans un autre workflow dans le designer: peut-être dans une prochaine version.
- En ce qui concerne la version .NET Core: peut-être dans une prochaine version.

Bien cordialement,
Akram.

**Comment by rvs76** [comment]
- En ce qui concerne les variables globales au niveau serveur, est-ce que vous pouvez me donner des exemples pour comprendre comment ça pourrait être implémenté dans Wexflow.

Le principe est d'avoir un endroit ou on peut stocker des variables communes à plusieurs task et/ou plusieurs workflow (répertoires de destinations, chaines de connexions, par exemple) et que ces variables soit facilement changeable en cas de besoin. Un peu comme un fichier de config dans un site ASP.NET.

**Comment by aelassas** [comment]
Bonjour Hervé,

Ok, je vois. je vais probablement implémenter ce genre de fonctionnalités dans la version 3.1.

Pour info, la [version 3.0](https://github.com/aelassas/Wexflow/releases/tag/v3.0) est sortie. Elle introduit le nouveau [back office](https://github.com/aelassas/Wexflow/wiki/Usage#wexflow-back-office) de Wexflow.

Cordialement,
Akram.

**Comment by rvs76** [comment]
Bonjour Akram,

Je viens de tester très rapidement.

Le back office est vraiment très très bien, mais il y encore des manquements à la sécurité pour que je puisse le présenter comme une solution viable au sein de mon entreprise.
- il faudrait au moins deux profils, un profil admin (comme actuellement) et un profil permettant juste de voir les logs et l'history
- dans le dashboard, il faudrait une gestion des utilisateurs (et s'assurer qu'il y a toujours au moins un admin ;-) )
- il faudrait un login par défaut au premier lancement du dashboard et enlever le "sign up" (ou faire une task qui envoie une demande d'inscription par mail aux admins ;-)
- les interfaces de management doivent aussi se connecter !

Je gère un référentiel, CàD que je reçois et j'envoies des données en csv. Cela représenterai beaucoup de tasks et de données répétitive (mêmes serveurs, mêmes répertoires, mêmes partenaires CFT,...) sur trois environnement (Dev, Test, Prod), La souplesse que pourrai apporter les "variables globales" et la réutilisation de tasks serait un gros plus.

Cordialement,

Hervé.

**Comment by aelassas** [comment]
Bonjour Hervé,

Voici les modification que je vais apporter à la version 3.1:

1. Créer deux profils utilisateur: 
  - Un admin qui aura accès à tout en plus à une nouvelle page à partir de laquelle il pourra gérer les utilisateurs.
  - Un profil au droits restreints qui aura accès au dashboard et au logs seulement.

2. Enlever le "Sign up" et créer un utilisateur admin (Username: admin et Password: wexflow2018) par défaut qui après la connexion la première fois pourra changer son mot de passe. 

3. Ajouter la connexion à l'interface de management qui ne sera accessible qu'aux admins.

4. Ajouter un fichier de variables globales qui sera par défaut dans C:\Wexflow\GlobalVariables.xml. Son chemin pourra être changé en modifiant le fichier de configuration C:\Wexflow\Wexflow.xml. Le format du fichier sera le suivant:

```xml
<GlobalVariables>
	<Variable name="variable1" value="value1" />
	<Variable name="variable2" value="value2" />
	<Variable name="variable3" value="value3" />
	...
</GlobalVariables>
```

En suite, les variables globales pourront être utilisées dans le fichier du workflow sous le format suivat: $variable1, $variable2, $variable3:

```xml
<GlobalVariables>
	<Variable name="monFichier" value="C:\WexflowTesting\file1.txt" />
</GlobalVariables>


<Workflow xmlns="urn:wexflow-schema" id="3" name="Workflow_FilesLoader" description="Workflow_FilesLoader">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
	</Settings>
	<Tasks>
		<Task id="1" name="FilesLoader" description="Loading files" enabled="true">
			<Setting name="file" value="$monFichier" />
		</Task>
		<Task id="2" name="ListFiles" description="Listing files" enabled="true">
		</Task>
	</Tasks>
</Workflow>
```
Voilà, j'espère que j'ai répondu à vos besoins. Si vous avez des remarques ou des améliorations à proposer n'hésitez pas.

Cordialement,
Akram.

**Comment by rvs76** [comment]
Re, 

Çà me va totalement.
Je n'ai pas regardé le code, mais il faut au moins que le mot de passe soit chiffré (déjà fait ?)

Cordialement,

Hervé.

**Comment by aelassas** [comment]
Oui bien sûr, tous les mots de passes sont chiffrés.

Cordialement,
Akram.

**Comment by aelassas** [comment]
Hervé,

Concernant la page de gestion des utilisateurs, je compte la développer comme suit:

- Un admin a le droit de changer son mot de passe mais avant il doit fournir son ancien mot de passe.
- Un admin a le droit de changer les mots de passes et les profils des utilisateurs ayant des droits restreints.
- Un admin n'a pas le droit de changer le mot de passe ou le profil d'un autre admin sans fournir l'ancien mot de passe de l'autre admin.

Est-ce que ça vous va comme ça?

Cordialement,
Akram.

**Comment by rvs76** [comment]
Akram,

Pour moi, ces règles sont appropriées.

Par contre, il faut toujours au moins un admin (dans mon entreprise, c'est même deux admins mais cela est impossible à imposer à tous utilisateurs de WF). Je propose qu'un admin ne peut pas supprimer et/ou désactiver son compte mais il y a peut-être d'autres solutions plus faciles pour toi.

Il faut pouvoir aussi réinitialiser un mot de passe perdu. Le mail me parait complexe (config de la passerelle mail, lien pour réinitialiser, etc). Un système question/ réponse me parait plus adapté.

Cordialement,
Hervé

**Comment by aelassas** [comment]
Hervé,

Je viens de mettre en ligne la [version 3.1](https://github.com/aelassas/Wexflow/releases/tag/v3.1) qui contient les nouvelles fonctionnalités suivantes:

- Pour se connecter la première fois, voici les credentials:
  - Username: admin
  - Password: wexflow2018
- Ensuite, vous pouvez modifier le mot de passe à partir de la nouvelle page "Users".
- Il y a 2 profils utilisateur: un admin qui a accès à tout et un restreint qui n'a accès qu'au dashboard et au logs.
- Un utilisateur admin a le droit de changer son nom d'utilisateur, son email et son mot de passe.
- Un utilisateur admin a le droit de changer le mot de passe d'un utilisateur ayant les droits restreints sans renseigner l'ancien mot de passe de l'utilisateur ayant les droits restreints.
- Un utilisateur admin a le droit de changer le nom, l'email et le profil d'un utilisateur ayant des droits restreints.
- Un utilisateur admin peut voir les autres utilisateurs admin mais il n'a pas accès à l'édition de leurs informations confidentielles. Pour qu'un admin modifie ses infos, il faut qu'il se connecte au back office puis il peut les modifier à partir de la page des utilisateurs.
- J'ai rajouté l'authentification dans le manager aussi.
- J'ai rajouté les [variables globales](https://github.com/aelassas/Wexflow/wiki/Global-variables) comme convenu.

Cordialement,
Akram.

**Comment by aelassas** [comment]
Hervé,

Je viens de mettre en ligne la [version 3.2](https://github.com/aelassas/Wexflow/releases/tag/v3.2) dans laquelle j'ai rajouté la page d'oubli de mot de passe.

La configuration du serveur SMTP doit se faire dans le fichier de configuration du serveur de workflows: C:\Program Files\Wexflow\Wexflow.Clients.WindowsService.exe.config

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net"/>
  </configSections>
  <appSettings>
    <add key="WexflowSettingsFile" value="C:\Wexflow\Wexflow.xml"/>
    <add key="Smtp.Host" value="smtp.gmail.com"/>
    <add key="Smtp.Port" value="587"/>
    <add key="Smtp.EnableSsl" value="true"/>
    <add key="Smtp.User" value="user"/>
    <add key="Smtp.Password" value="password"/>
    <add key="Smtp.From" value="user"/>
  </appSettings>
  ...
 </configuration>
```

Vous trouverez plus de détails dans la [documentation](https://github.com/aelassas/Wexflow/wiki/Usage#wexflow-back-office) du back office que je viens de mettre à jour.

J'ai aussi rajouté un lien d'oubli de mot de passe dans le manager.

Si vous avez des questions ou des améliorations à proposer n'hésitez surtout pas.

Cordialement,
Akram.

**Comment by rvs76** [comment]
Bonjour Akram,

Question (bête ?) :
Comment se sert-on de la mémoire partagé ? j'ai mis le répertoire de base de réception des fichier dans les variables globale mais j'ai besoin du nom du sous répertoire au niveau du workflow. Ce nom sert de plus pour nommer la requete d'import et pour l'archivage

**Comment by aelassas** [comment]
Bonjour Hervé,

Voici un exemple d'utilisation de la mémoire partagée:

Dans une première task customisée, j'ajoute une SqlConnection à la mémoire partagée:

```csharp
namespace Wexflow.Tasks.MyTask1
{
    public class MyTask1 : Task
    {
        public MyTask1(XElement xe, Workflow wf) : base(xe, wf)
        {
            // Task settings goes here
        }

        public override TaskStatus Run()
        {
            try
            {
                SqlConnection conn = new SqlConnection("connectionString");
				
		// Ajout de la connexion dans la mémoire partagée
		this.Hashtable.Add("conn", conn);

		// ...
				
                return new TaskStatus(Status.Success);
            }
            catch (ThreadAbortException)
            {
                throw;
            }
        }
    }
}
```

Dans une deuxième task, je récupère la connexion depuis la mémoire partagée comme suit:

```csharp
namespace Wexflow.Tasks.MyTask2
{
    public class MyTask2 : Task
    {
        public MyTask2(XElement xe, Workflow wf) : base(xe, wf)
        {
            // Task settings goes here
        }

        public override TaskStatus Run()
        {
            try
            {
               // Récupération de la connexion depuis la mémoire partagée
                SqlConnection conn = (SqlConnection)this.Hashtable["conn"];

		// ...
				
                return new TaskStatus(Status.Success);
            }
            catch (ThreadAbortException)
            {
                throw;
            }
        }
    }
}
```

Cordialement,
Akram.

**Comment by rvs76** [comment]
Re,
Il n'y a pas d'autre moyen d'avoir une variable au niveau Workflow ?

J'ai bien des custom tasks à faire mais je ne me vois pas refaire toutes les tasks (fileexist, filecopier, etc) que j'ai besoin pour qu'ils utilisent la mémoire partagée.

Ou alors faire une custom task dummy qui renvoie en value, son paramètre !

Autre question, peut-on concatener des strings dans les settings d'une task ?

**Comment by aelassas** [comment]
> Il n'y a pas d'autre moyen d'avoir une variable au niveau Workflow ?

je comprends ce que vous essayez de faire: vous voulez entrer dans le paramètre d'une task une valeur puis la récupérer dans une autre task.

La seul façon de faire cela c'est d'utiliser les task customisée en ajoutant le couple (clé,valeur) dans la mémoire partagée puis le réutiliser dans une autre task customisée.

> Autre question, peut-on concaténer des strings dans les settings d'une task ?

Voulez-vous concaténer des variables globales dans les settings?

Akram.

**Comment by rvs76** [comment]
Disons que j'ai plusieurs répertoire de base dans les variables globales (flux, logs, archivage,...). chacun de ces répertoire est composé de sous répertoires ayant les même noms (flux\\ERP ; logs\\ERP ; Archives\\ERP dans le cas de ce matin).
Comment utiliser ce sous repertoire (en gros le path.combine de la variable globale et de "ERP) pour plusieurs tasks d'un même workflow.

Pour info, voici ce que je veux faire:

$Flux -> repertoire de base des fichiers
$Log -> repertoire de base pour les logs
$Archive

1. Vérifier si le fichier xxx existe dans le répertoire $Flux+ **"\\ ERP"**
2. Renommer le fichier en contrat.txt ($Flux+ **"\\ ERP"** + "\\contrat.txt")
3. Import dans la base de données avec SQLLoader (task custom mais logs dans $Log )
4. Suppression des anciens fichiers exportées
5. Export fichiers vers différentes applications (task custom SQLPlus + task custom CFT)
6. Supprimer les fichiers dans $Archive + **"\\ERP"** + "\\J-3"
7. Copier les fichiers de $Archive + " + "\\J-2" vers $Archive + **"\\ERP"** + "\\J-3"
8. Copier les fichiers de $Archive + **"\\ERP"** + "\\J-1" vers $Archive + **"\\ERP"** + "\\J-2"
9. Copier le fichier $Flux+ **"\\ ERP"** + "\\contrat.txt"  vers $Archive + **"\\ERP"** + "\\J-1"
10. Copier les fichiers de $Archive + **"\\ERP"** + "\\J-2" vers $Archive + **"\\ERP"** + "\\J-3"
12. Supprimer les répertoires BAD et DSC dans $Archive + **"\\ERP"** + "\\J-3"
13. Copier les répertoires BAD et DSC de $Archive + **"\\ERP"** + "\\J-2" vers $Archive + **"\\ERP"** + "\\J-3"
14. Copier les répertoires BAD et DSC de $Archive + **"\\ERP"** + "\\J-1" vers $Archive + **"\\ERP"** + "\\J-2" 
15. Copier les répertoires BAD et DSC de $Log vers $Archive + **"\\ERP"** + "\\J-1"
16. CFT (Custom task pour envoyer les fichiers avec CFT)

C'est le cas le plus simple que j'ai (un seul fichier en import et un seul export, par de compression et pas de fichier incrémentiel) ! Donc ça serait bien que "ERP" soit dans une variable.

NB : AHMA, je ferais surement l'archivage (6 à 15) dans une Task custom.

**Comment by aelassas** [comment]
Ok, je vois.

La concaténation de settings devrait marcher, car dans le parsing des settings de workflows je remplace les variables globales par leurs valeurs respectives donc voici un exemple qui devrait marcher:

Variables globales:
```xml
<GlobalVariables>
  <Variable name="Flux" value="..." />
  <Variable name="Log" value="..." />
  <Variable name="Archive" value="..." />
</GlobalVariables>
```

Concaténation (simple exemple de suppression de fichiers):

```xml
<Workflow xmlns="urn:wexflow-schema" id="5" name="Workflow_FilesRemover" description="Workflow_FilesRemover">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
	</Settings>
	<Tasks>
		<Task id="1" name="FilesLoader" description="Loading files" enabled="true">
			<Setting name="folder" value="$Archivage\ERP\J-3" />
		</Task>
		<Task id="2" name="FilesRemover" description="Deleting files" enabled="true">
			<Setting name="selectFiles" value="1" />
		</Task>
	</Tasks>
</Workflow>
```

Je pense que cette solution répond à votre besoin.

Akram.

**Comment by rvs76** [comment]
Bonsoir Akram,

J'ai implémenté les variables locales pour un worflow. J'ai ajouté un section LocalVariables dans le xml d'un workflow et j'ai modifié le  "void Parse(string src, string dest)" dans "Workflow.cs". Je parse les variables globales comme actuellement (on peut donc utiliser des variables globales dans les variables locales) puis je récupère les variables locales, je supprime la section LocalVariables et enfin je parse les variables locales.

C'est peut-être pas très propre mais je voulais modifié à minima et être le plus transparent pour le reste du code (une seule fonction de modifié, xml de sortie identique à l'ancien code).

Cordialement,

Hervé.

**Comment by rvs76** [comment]
Bonjour,

J'ai fait ma première Task custom. J'ai commencé très simple mais je pense qu'elle pourrait être utile. Elle entièrement calqué sur la Task Now, elle permet de récupérer un variable d’environnement.

`
using System;
using System.Threading;
using System.Xml.Linq;
using Wexflow.Core;

namespace Wexflow.Tasks.GetEnvVariable
{
    class GetEnvVariable : Task
    {
        public string VariableName { get; private set; }
        protected GetEnvVariable(XElement xe, Workflow wf) : base(xe, wf)
        {
            VariableName = GetSetting("name");
        }

        public override TaskStatus Run()
        {
            Info("Getting Environment variable...");
            string value = string.Empty;
            bool succeeded = false;
            try
            {
                value = Environment.GetEnvironmentVariable(VariableName);
                InfoFormat("The value is: {0}", value);
                if (!string.IsNullOrEmpty(value))
                    succeeded = true;
            }
            catch (ThreadAbortException)
            {
                throw;
            }
            catch (Exception e)
            {
                ErrorFormat("An error occured while retrieving environment variable. Error: {0}", e.Message);
            }
            Info("Task finished.");
            return new TaskStatus(succeeded ? Status.Success : Status.Error, value);
        }
    }
}

`

Elle **devrait** être compatible avec .Net Core

**Comment by rvs76** [comment]
Pour les variables locales, j'ai fait le même principe, sauf que j'utilise un MemoryStream au lieu d'un fichier intermédiaire .

```cs
        void Parse(string src, string dest)
        {
            Variable[] LocalVariables;
            MemoryStream ms = new MemoryStream();
            XDocument xdoc=new XDocument();

            using (StreamReader sr = new StreamReader(src))
            using (StreamWriter sw = new StreamWriter(ms))
            {
                string line;
                while ((line = sr.ReadLine()) != null)
                {
                    foreach (var variable in GlobalVariables)
                    {
                        line = line.Replace("$" + variable.Key, variable.Value);
                    }
                    sw.WriteLine(line);
                }
                sw.Flush();
                ms.Seek(0, SeekOrigin.Begin);
                xdoc = XDocument.Load(ms);
            }
       
            var lvs = xdoc.Root.Elements().Where (xe=> xe.Name.LocalName=="LocalVariables") ;
            List<Variable> variables = new List<Variable>();
            foreach (var xvariable in lvs.Elements())
            {
                Variable variable = new Variable
                {
                    Key = xvariable.Attribute("name").Value,
                    Value = xvariable.Attribute("value").Value
                };
                variables.Add(variable);
            }
            LocalVariables = variables.ToArray();
            xdoc.Root.Elements().Where(xe => xe.Name.LocalName == "LocalVariables").Remove();
            ms = new MemoryStream();
            xdoc.Save(ms);
            ms.Seek(0, SeekOrigin.Begin);
            using (StreamReader sr = new StreamReader(ms))
            using (StreamWriter sw = new StreamWriter(dest))
            {
                string line;
                while ((line = sr.ReadLine()) != null)
                {
                    foreach (var variable in LocalVariables)
                    {
                        line = line.Replace("$" + variable.Key, variable.Value);
                    }
                    sw.WriteLine(line);
                }
            }
        }
```

**Comment by aelassas** [comment]
Oui je vois, mais vous avez oublié de modifier l'XSD C:\Wexflow\Workflow.xsd pour autoriser les nœuds LocalVariables dans les fichiers de workflows.

Akram.

**Comment by aelassas** [comment]
Hervé,

Concernant la task EnvironmentVariable, il faut que la classe et son constructeur soient publiques. Une variable d'environnement peut aussi retourner une valeur vide. Voici le code de la task modifié;


```cs
using System;
using System.Threading;
using System.Xml.Linq;
using Wexflow.Core;

namespace Wexflow.Tasks.EnvironmentVariable
{
    public class EnvironmentVariable : Task
    {
        public string VariableName { get; private set; }

        public EnvironmentVariable(XElement xe, Workflow wf) : base(xe, wf)
        {
            VariableName = GetSetting("name");
        }

        public override TaskStatus Run()
        {
            Info("Getting environment variable...");

            string value = string.Empty;
            bool succeeded = false;
            try
            {
                value = Environment.GetEnvironmentVariable(VariableName);
                InfoFormat("The value of the environment variable '{0}' is: {1}", VariableName, value);
                succeeded = true;
            }
            catch (ThreadAbortException)
            {
                throw;
            }
            catch (Exception e)
            {
                ErrorFormat("An error occured while retrieving environment variable. Error: {0}", e.Message);
            }

            Info("Task finished.");
            return new TaskStatus(succeeded ? Status.Success : Status.Error, value);
        }
    }
}
```

Voici un exemple de workflow de test de la task:

```xml
<Workflow xmlns="urn:wexflow-schema" id="116" name="Workflow_EnvironmentVariable" description="Workflow_EnvironmentVariable">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
	</Settings>
	<Tasks>
		<Task id="99" name="EnvironmentVariable" description="Getting OS environment variable" enabled="true">
		  <Setting name="name" value="OS" />
		</Task>
		<Task id="1" name="Wait" description="Waiting for 1 seconds..." enabled="true">
			<Setting name="duration" value="00.00:00:01" />
		</Task>
		<Task id="2" name="Wait" description="Waiting for 2 seconds..." enabled="true">
			<Setting name="duration" value="00.00:00:02" />
		</Task>
	</Tasks>
	<ExecutionGraph>
		<Switch id="100" parent="-1" switch="99">
		  <Case value="Windows_NT">
			<Task id="1"><Parent id="-1" /></Task>
		  </Case>
		  <Default>
			<Task id="2"><Parent id="-1" /></Task>
		  </Default>
		</Switch>
	</ExecutionGraph>
</Workflow>
```

Cordialement,
Akram.

**Comment by aelassas** [comment]
@rvs76 J'ai beaucoup réfléchi à l'intégration des variables locales dans le designer mais malheureusement c'est très compliqué à mettre en place vu la façon dont je parse les variables.

La seul modification que j'ai faite dans le designer ([version 3.5](https://github.com/aelassas/Wexflow/releases/tag/v3.5)) c'est afficher les variables locales des workflows qui contiennent des variables locales.

Pour l'instant, ce n'est pas possible de modifier les workflows qui contiennent des variables locales depuis le designer. La seul façon de faire c'est de mettre sa main dans le fichier XML du workflow.

Voilà et n'hésitez pas à me tenir au courant de votre avancement avec Wexflow.

Cordialement,
Akram.

**Comment by rvs76** [comment]
Bonsoir Akram,

Comment dire ... cette semaine, j'ai fait angine, côte cassé, gastro-entérite mais très peu de Wexflox ...
Personnellement, cela ne dérange pas que les variables locales ne soient accessibles qu'en éditant le XML. Wexflox est déjà très bien documenté et en étant très clair, ça passe.

Cordialement,
Hervé.

**Comment by aelassas** [comment]
Bonsoir @rvs76,

Ok, bon rétablissement.

Akram.

**Comment by aelassas** [comment]
@rvs76 

J'espère que vous allez mieux cette semaine. Pour info, j'ai réussi à intégrer l'édition des variables locales et globales dans le designer dans la [version 3.6](https://github.com/aelassas/Wexflow/releases/tag/v3.6) que je viens de publier. J'ai aussi corrigé quelques bugs.

Akram.

**Comment by mirkoarnold** [comment]
Hi Akram, 
I wonder about the feature long-running processes. Is there a feature to persist the state of a workflow and  continue it after an indefinite time? For example I'm sending a request to a partner to give me a quote for a product and after some time (even some server restarts between) I can continue the same workflow. Sorry I make the references to Workflow Foundation, but it had this feature in combination with appFabric: 
https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/how-to-enable-sql-persistence-for-workflows-and-workflow-services

If wexflow doesn't have this feature, would be a great one. 
Cheers and thanks for you work.
Mirko


"...aims to make automations, workflow processes, **long-running processes** and interactions between systems, applications and folks easy, straightforward and clean. "

**Comment by TriLogic** [comment]
Anything and everything blockchain.

**Comment by TriLogic** [comment]
Having worked with enterprise task management software (ActiveBatch) I found their concept of Execution Agents to be very powerful in that one machine is not responsible executing all jobs (workflows).  They were able to virtualize this concept to allow for failover and process scaling very effectively.

Does Wexflow support this concept and can you imagin adding this in the future?

**Comment by aelassas** [comment]
@TriLogic, 
Wexflow provides an event OnError in case of a workflow fails. In this event you can execute a set of tasks or relaunch the workflow for instance.
But if there is a power cut and the machine shuts down there is no failover yet. 
I'll think about adding these features in the future.
Thanks,

**Comment by iquirino** [comment]
What about write in english? i dont know french.

**Comment by xcellenceit** [comment]
Can we create a workflow involving talking with/to APIs or Web Services?

**Comment by u2mike** [comment]
a nice feature would be to enhance the user management in a follwing manner:
user **abc** have only the authority to lanch trigger who are "assito this user (group)

**Comment by tetrodoxin** [comment]
> Can we build a human workflow (e.g. approval processs) using WexFlow?

I totally second this one. Maybe workflows, that are started by submitting a web-form or leading through a series of webforms, where every step changes with the results of the preceding one.

I furthermore volunteer to help. Would you accept an PR for an LDAP-integration feature?

**Comment by gerwald** [comment]
It would be great, to host Wexflow on Azure (running it as a web job)

**Comment by datauduong** [comment]
> What about write in english? i dont know french.

I have the same problem.

**Comment by rSrkn** [comment]
> > Can we build a human workflow (e.g. approval processs) using WexFlow?
> 
> I totally second this one. Maybe workflows, that are started by submitting a web-form or leading through a series of webforms, where every step changes with the results of the preceding one.
> 
> I furthermore volunteer to help. Would you accept an PR for an LDAP-integration feature?

Same here. I could not find any Simple Approval example that can do below steps:
- A user creates a request. 
- Notification email sent to Management user
- Management user visit list of requests page
- Management user approve or reject
- Initial user receive notification email
...

If it is already possible could you please add or share a example.

**Comment by jeremycook** [comment]
Alternative authentication methods like OpenID Connect. User management would still be handled the way it is, but OpenID Connect (and potentially other methods) could be in addition to, or instead of username and password.

**Comment by alexhiggins732** [comment]
> Alternative authentication methods like OpenID Connect. User management would still be handled the way it is, but OpenID Connect (and potentially other methods) could be in addition to, or instead of username and password.

Use of Identity Server for this purpose would be great.

**Comment by zeusmos** [comment]
can you add editable xml right in designer ?
![image](https://user-images.githubusercontent.com/16844197/62489543-9f741480-b78c-11e9-973c-b9300ec9ec18.png)

**Comment by aelassas** [comment]
@zeusmos I'll add editable xml in the designer in the version 4.3 that I will release next week. I'll notify you once released. 

By the way, it's a nice feature idea.

**Comment by aelassas** [comment]
@zeusmos I added XML editing and validation of workflows in the version 4.3 that I will publish next week. I also created the new following flowchart tasks:
- [FolderExists](https://github.com/aelassas/Wexflow/wiki/FolderExists): This task checks whether a folder exists or not.
- [FileContentMatch](https://github.com/aelassas/Wexflow/wiki/FileContentMatch): This task checks whether the content of a file matches a regex pattern.

I also added a setting option in [SqlToCsv](https://github.com/aelassas/Wexflow/wiki/SqlToCsv) task to not generate the file if the result set is empty.

I also updated and enhanced the style and the design of designer:

![wexflow-v4 3](https://user-images.githubusercontent.com/1339626/62777434-6e098a80-baa5-11e9-85af-a735f1b0d112.PNG)

I'll notify you once I've released it.

**Comment by aelassas** [comment]
@zeusmos I've just published the brand new [version 4.3](https://github.com/aelassas/Wexflow/releases/tag/v4.3). Tell me how you find the brand new Web XML editor and the other new features.

**Comment by zeusmos** [comment]
> 
> 
> @zeusmos I've just published the brand new [version 4.3](https://github.com/aelassas/Wexflow/releases/tag/v4.3). Tell me how you find the brand new Web XML editor and the other new features.

looks and works great.  :+1:

**Comment by zeusmos** [comment]
when installing the newer/upgrade version there should be an installation option to check weather the samples should be installed or not.

**Comment by aelassas** [comment]
@zeusmos I added an option in the installer to whether install samples or not. This feature will be available in the version 4.4 and above.

**Comment by aelassas** [comment]
@zeusmos I've released the [version 4.4](https://github.com/aelassas/Wexflow/releases/tag/v4.4). It includes an option in the installer to whether install workflow samples or not. However, it is highly recommended to install workflow samples. Especially when new tasks are released.

**Comment by PlumbingWorldNZ** [comment]
Thanks for adding in the queue.  If it's not too difficult, it would also be useful to have the option to process jobs asynchronously, without waiting for the previous run of that workflow to complete.  Keep up the good work!

**Comment by kevalkothari** [comment]
Hi @aelassas 
Making the Task Settings Collapsible may give lot of comfort to work with and visualize. See example.

![Task Settings](https://user-images.githubusercontent.com/1439447/65370217-033a9a00-dc74-11e9-9640-6f5ef609d3ba.png)


Can be make like this:
https://www.jquery-az.com/boots/demo.php?ex=53.0_5

**Comment by aelassas** [comment]
Thank you for your feedback. I will add this feature in the v4.8. I will
notify you once released.

Le sam. 21 sept. 2019 à 09:01, kevalkothari <notifications@github.com> a
écrit :

**Comment by aelassas** [comment]
@kevalkothari I added expand/collapse feature to the designer:

![designer-expand-collapse](https://user-images.githubusercontent.com/1339626/65374253-ba88de00-dc7f-11e9-9ec0-bfad11f5d5f3.png)

This will be part of the v4.8.

**Comment by kevalkothari** [comment]
That looks great now @aelassas

**Comment by aelassas** [comment]
@kevalkothari I have just released the [v4.8](https://github.com/aelassas/Wexflow/releases/tag/v4.8).

**Comment by akleine01** [comment]
A feature would be that the workflow are versioned. 
A job would then always run a workflow of a specific version. 
So you could also develop a change to the workflow and at the same time the workflow is still running in the last productive version.

A.Kleine

**Comment by tematim** [comment]
@akleine01 I agree that versioning is a good feature.
And the possibility to make a backup in a network share and/or include github versioning
To switch from version or easily rollback.

**Comment by dentrazergit** [comment]
- Scalability by adding more servers.
- Parallel execution of workflows
- UI drag and drop designer - simmilar as it is in workflow foundation engine.
- Check current stage of execution of an workflow in UI. Task is highlighted in execution graph. 
- support callbacks from external systems to resume/pass parameters to next task in the workflow.  
- versioning - when we have a long running task that is executed using old workflow and we update existing workflow with new tasks etc...

**Comment by homam1** [comment]
Great job Akram!

**Comment by aelassas** [comment]
@dentrazergit Great feature requests. Thanks for your feedback.
