### ISSUE TITLE
.NET Core, url for back-office?

### ISSUE THREAD

**Issue by avenla-mlindman** [aelassas/Wexflow#65]
After installing Core version on Windows, I did install.bat and run.bat. Server is running on port 8000.

`Now listening on: http://[::]:8000`

yet localhost:8000\index.html, \backoffice\index.html, back-office\index.html give 404 result from Nancy. What is the correct url?

**Comment by aelassas** [comment]
Hi,

You open the back office by double-clicking on the file Back-office\index.html

The back office is not hosted on Nancy.

Kind regards,

**Comment by avenla-mlindman** [comment]
Thank you.
