### ISSUE TITLE
allow for custom dlls to be in a different folder from installation

### ISSUE THREAD

**Issue by bryanvam** [aelassas/Wexflow#66]

**Comment by aelassas** [comment]
Hi,

Why would you like to allow for custom dlls to be in a different folder from installation?

Regards,

**Comment by bryanvam** [comment]
i have some custom workflows (using your nuget package) specific to a project. when i deploy i dont want to have to copy the updates to the installation directory. i would like it to stay inside the deployed project

**Comment by aelassas** [comment]
Hi,

I added this feature in the [version 3.7](https://github.com/aelassas/Wexflow/releases/tag/v3.7).

Here is how it works:

You can put your custom dlls in the folder C:\Wexflow\Tasks. The path of the folder C:\Wexflow\Tasks can be configured through tasksFolder setting in the configuration file C:\Wexflow\Wexflow.xml.

Kind regards,

**Comment by aelassas** [comment]
@bryanvam Is this feature working as you expected?

**Comment by bryanvam** [comment]
I will update in the next day or 2 and let you know

**Comment by aelassas** [comment]
Can I close this issue?

**Comment by bryanvam** [comment]
yes thanks. all working
