### ISSUE TITLE
Does not compile under visual studio 2022

### ISSUE THREAD

**Issue by TechyGuy99** [aelassas/wexflow#66]
The wexflow.sln  does not compile.  It produces numerous errors and appears to be a mix of .net 4.8 and.net core projects.

How can i compile this with .net core only?

**Comment by aelassas** [comment]
Did you set Any CPU in build configuration instead of Mixed Platform?

**Comment by aelassas** [comment]
@TechyGuy99 I fixed some issues in Wexflow.sln and tested the compilation of the latest source code on the [main branch](https://github.com/aelassas/wexflow/archive/refs/heads/main.zip) on Visual Studio 2022 >= 17.8.0 and everything works fine on both .NET 4.8 and .NET 8.0.

Once you open Wexflow.sln, under `src` solution folder you have:
- `net` solution folder which contains the source code of the .NET 4.8 version
- `netcore` solution folder which contains the source code of the .NET 8.0 version (.NET Core)

You can compile with .NET Core only by compiling `netcore` solution folder only in Visual Studio 2022 >= 17.8.0.

For further information on how to run the solution from source code, check out this [documentation](https://github.com/aelassas/wexflow/wiki/Run-From-Source).

**Comment by TechyGuy99** [comment]
> @TechyGuy99 I fixed some issues in Wexflow.sln and tested the compilation of the latest source code on the [main branch](https://github.com/aelassas/wexflow/archive/refs/heads/main.zip) on Visual Studio 2022 >= 17.8.0 and everything works fine on both .NET 4.8 and .NET 8.0.
> 
> Once you open Wexflow.sln, under `src` solution folder you have:
> 
> * `net` solution folder which contains the source code of the .NET 4.8 version
> * `netcore` solution folder which contains the source code of the .NET 8.0 version (.NET Core)
> 
> You can compile with .NET Core only by compiling `netcore` solution folder only in Visual Studio 2022 >= 17.8.0.
> 
> For further information on how to run the solution from source code, check out this [documentation](https://github.com/aelassas/wexflow/wiki/Run-From-Source).

Ok, got latest and everything net core compiled. I  turned off the 4.8 and was fine.

Next, i added a workflow with zip files task. Not sure what i am supposed to enter in selected files. Seems to reject silently 
and when debugging, i see no selectedFiles Value in the xml
![image](https://github.com/aelassas/wexflow/assets/150186692/43b03e12-10f7-4206-a4bd-feffbc3faa6c)

**Comment by TechyGuy99** [comment]
Also, you might want to change your config to avoid the hardcoded C:\Wex* folder references.   I ran install.bat as workaround in meantime for debugging.

**Comment by aelassas** [comment]
You need to use FilesLoader task before Zip task to load the files you want to zip. Here is a sample Zip workflow: https://github.com/aelassas/wexflow/blob/main/samples/net/Wexflow/Workflows/Workflow_Zip.xml

In selectFiles you put the ID of the task that loads files: https://github.com/aelassas/wexflow/wiki/Getting-Started#how-tasks-communicate-between-each-other

You can find the doc of each task in the wiki.

For config files, you can change them as you want: https://github.com/aelassas/wexflow/wiki/Configuration
