### ISSUE TITLE
WexFlow 3.6 .Net Core Version Startup

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#67]
**Hi Akram**

Thanks for the nice update ind the 3.X version series.

I have tried to start the WF3.6 Windows Core version, and followed the install instruction strict, but no matter what i do when starting the browser at localhost:port eg. http://localhost:8000 I get an Nancy Webserver 404 error.

I the tried to change the port to others, but the same result.

![wexflow core](https://user-images.githubusercontent.com/6866443/49150648-d0eb3500-f30d-11e8-91a1-b16f2e2e9dba.png)

Hope there is a simple solution to this problem.

**Thanks :-)**

SUBNOTE: Is there any known instruction to start up the .Core application at Windows startup, like the Windows Services version ?

**Comment by aelassas** [comment]
Hi,

The backend is not stored on Nancy. To open the backend go to "Backend" folder and double click on "index.html" file.

Regarding Windows startup in the .NET Core version, the only option that I see is to use Windows Task Scheduler to start Wexflow at Windows startup like the Windows Service version.

Kind regards,
Akram.

**Comment by janborup** [comment]
Suuuure - My mistake :-)

Maybe a little change in Installation document:
[WF Installation](https://github.com/aelassas/Wexflow/wiki/Installation#windows-net-core)

>...
> 
> The port 8000 must be free. If you are already using the .NET version of Wexflow, you must stop Wexflow Windows service or change the port of the .NET Core version.
> If you have change the web-port to other than 8000, on the Engine .NET Core version, please edit following files:
> - file ..\Wexflow.Server\appsettings.json and change the value of the setting "WexflowServicePort" eg 8001.
> - file ..\Backend\js\settings.js, change the "Uri:" to port of the backend "Uri: "http://localhost:8001/wexflow/"
> 
> If you start the engine by http://localhost:8000/wexflow/ and your browser respond **"Hello from Wexflow workflow engine running on CoreCLR"**, now the engine is up an running. 
> 
>**Startup the Backend**
> Finally, you can open the backend by opening the web page ..\Backend\index.html on a browser:

Kind regards
Jan

**Comment by AdemAygun** [comment]
If I click double index.html in backend folder It's opened file:///D:/wexflow-3.8-windows-dotnet-core/Backend/index.html and it's not working
