### ISSUE TITLE
Getting my task to appear and add to designer.

### ISSUE THREAD

**Issue by TechyGuy99** [aelassas/wexflow#67]
Here is my task project.
I want to create a dummy task and be able to add it to a workflow, but it does not appear in the task search list.

I extracted .net core file to C:\wexflow-7.8-windows-netcore
I ran install.bat
I ran run.bat
I mapped IIS site to the backend folder under folder  C:\wexflow-7.8-windows-netcore\Backend

[SidekickArchiveReplyWF.zip](https://github.com/aelassas/wexflow/files/14289245/SidekickArchiveReplyWF.zip)

![image](https://github.com/aelassas/wexflow/assets/150186692/a44dfd2c-f517-40c1-a198-5e2adeed2a6c)

Task is not in the list

task files are in 
![image](https://github.com/aelassas/wexflow/assets/150186692/78ecc82d-6abb-4f0b-a509-d5cf53bb7b93)

**Comment by aelassas** [comment]
You need to add your task to the designer: https://github.com/aelassas/wexflow/wiki/Custom-Tasks#designer

You also need to add your task to wexflow engine: https://github.com/aelassas/wexflow/wiki/Custom-Tasks#net-core

**Comment by TechyGuy99** [comment]
Thanks, i got it to work.  One note though.  I found that if i made a mistake in setting up these files and subsequently created a workflow based on that task, that workflow had to be deleted and recreated as it would not load.

**Comment by TechyGuy99** [comment]
I think it would be simpler if the system just loaded the assemblies it found in the tasks folder and scanned the classes that implemented the Task base class. That base class should have all the information needed to setup the class, without the need to update json files and xml.  ANy class that does not derive from expected base or interface would be ignored.
