### ISSUE TITLE
How to use Http task using authorization header

### ISSUE THREAD

**Issue by DevNovela** [aelassas/Wexflow#68]
Hello, i need to call a rest api that need authorization header, how i can do that?

Best regards, Yoan

**Comment by aelassas** [comment]
Hello Yoan,

You'll have to create your own [custom task](https://github.com/aelassas/Wexflow/wiki/Custom-tasks) to do that. To help you do that, you can start by reading the code of Http and HttpGet tasks. 

In these tasks I'm using WebClient, but if you need authorization you'll have to use WebRequest.

Kind regards,
Akram.

**Comment by DevNovela** [comment]
Thank's for your rapid response. I will try creating my custom task.
Yoan
