### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TechyGuy99** [aelassas/wexflow#68]
If i have  a workflow where a task or tasks fail, 
how do i roll back to valid state?

Do you have a retry framework incorporated in such a case?

**Comment by aelassas** [comment]
Yes, If a task fails: 
```
- The retryCount option allows to retry a task a certain number of times in case of
  failure. Defaults to 0 (no retry).
- The retryTimeout option indicates the waiting time between two tries in milliseconds.
  Defaults to 1500ms.
```
If the workflow fails: https://github.com/aelassas/wexflow/wiki/Samples#workflow-events

but you need to edit the workflow from xml view for retry options and workflow events.
