### ISSUE TITLE
A few questions regarding Hosting of Wexflow

### ISSUE THREAD

**Issue by ericnewton76** [aelassas/Wexflow#69]
Does this have a REST API or any API that allwos for separate hosting of Wexflow from production app?

Can this run as Azure App Service? (App Service can self-host MySql but not LiteDB)

**Comment by aelassas** [comment]
Hi,

Yes, there is a [RESTful API](https://github.com/aelassas/Wexflow/wiki/RESTful-API).

I think that the .NET Core version of Wexflow can run as Azure App Service because It is a self-hosted web server in a console app.

Regards,
Akram.

**Comment by aelassas** [comment]
@iquirino 
I'm already using Owin, Kestrel and Nancyfx in the .NET Core version.

**Comment by CalosChen** [comment]
I downloaded the latest release on github, and used .net core setup, when I am running "run.bat", console says "Cannot find folder c:\wexflow-dotnet-core\database", the database folder does not exist, did I miss something? I totally refered the document. PLS, thanks.

**Comment by aelassas** [comment]
@CalosChen Did you run install.bat before? try do create the folder C:\Wexflow-dotnet-core\Database and see.

**Comment by CalosChen** [comment]
@aelassas Thanks, it works now, just created the Database folder in that path. 👍

**Comment by ericnewton76** [comment]
I hope that C:\wexflow directory is configurable. I doubt Asure will be letting us write to C:\

**Comment by aelassas** [comment]
@ericnewton76 Yes, C:\wexflow directory is [configurable](https://github.com/aelassas/Wexflow/wiki/Usage#general).
