### ISSUE TITLE
[Question] - Just wanted to confirm that the SFTP plugin handles incomplete Downloads (and uplaods)

### ISSUE THREAD

**Issue by jeffward01** [aelassas/wexflow#7]
Massively look app!! This is great! 

I reviewed the code for the `SFTP` and it looks like it **does** handle incomplete download and uploads by simply over-writing it?

I have a use-case where the machine that WexFlow will:

* Wexflow installed on` LocalComputerAAA`
* Connect to FTP `RemoteServer123`
* Wexflow downloads files from `RemoteServer123` and saves them to a NAS or Drive connected to `LocalComputerAAA`
* `LocalComputerAAA` is frequently restarted and shut down, so I just wanted to confirm its resiliency 

# Questions

1.) Just to confirm - incomplete files will be 'overwrited' (upload and downloaded
2.) The FTP downloads to the `/` of where wexflow is hosted on?  Where does the FTP task download files to?

* I understand that first the files are downloaded (one by one)
* Then the file mover when each task is complete, will move the file from the root `/` of wexflow to the destination folder.

Is this correct?

3.)  Can you clarify please what the `selectFiles` property does?

https://github.com/aelassas/wexflow/wiki/Ftp

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Tasks>
  <!--
    Ftp is a sequential task that allows to list, upload, download or delete files over FTP, FTPS or SFTP.
  -->
  <Task id="$int" name="Ftp" description="$string" enabled="true|false">
    <!--  The files loaded by the task having as id $taskId will be sent. -->
    <Setting name="selectFiles" value="$taskId" />
    <Setting name="selectFiles" value="$taskId" />
    <!-- You can add as many selecteFiles as you want.-->
    <!--- FTP command. Possible values: list|upload|download|delete-->
    <Setting name="command" value="list|upload|download|delete" />
    <!--- FTP Protocol. Possible values: ftp|ftps|sftp-->
    <Setting name="protocol" value="ftp|ftps|sftp" />
```

----

## Notes

I will have to do some testing of my own to better understand how these work:

> To understand how tagging and renaming files work, refer to the documentation of the ListFiles and Xslt tasks.

I read the documentation,  and this is still unclear to me.  It sounds like some sort of file / task monitor? I'm not quite sure.

## Wiki

I will get the Wiki updated with 'Error Handling' in the FTP area once this is confirmed and I understand it.

Thanks so much!

**Comment by aelassas** [comment]
1. Yes, incomplete files will be overwritten.
2. Files are saved in Wexflow's Temp folder (C:\Wexflow\Temp).
3. selectFiles works as [follows](https://github.com/aelassas/wexflow/wiki/Get-Started#how-tasks-communicate-between-each-other).
4. [Here](https://github.com/aelassas/wexflow/blob/main/samples/net/Wexflow/Workflows/Workflow_Ftp_download_tag.xml) is a sample ftp download tagging workflow. [Here](https://github.com/aelassas/wexflow/blob/main/samples/net/Wexflow/Workflows/Workflow_Ftp_upload_rename.xml) is a sample upload renaming workflow. [Here](https://github.com/aelassas/wexflow/blob/main/samples/net/Wexflow/Xslt/ListFiles.xslt) is the XSLT used for tagging and renaming. You can find a detailed documentation on how tagging and renaming works [here](https://github.com/aelassas/wexflow/wiki/Xslt).
