### ISSUE TITLE
disable workflow

### ISSUE THREAD

**Issue by Luuk34** [aelassas/Wexflow#71]
on this issue the API is explained
https://github.com/aelassas/Wexflow/issues/33

Why is the option to enable/disable a workflow not available?

(actually i was searching for a way to disable some/all workflows from commandline in Windows)

something like:
**curl "http://localhost:8000/wexflow/disable/42"**
to disable workflow 42

**Comment by aelassas** [comment]
Sorry, this feature is not available yet.

**Comment by aelassas** [comment]
@Luuk34 I added /disable/{id} and /enable/{id}. These two new functions will be available in the v5.4.

**Comment by aelassas** [comment]
I released the [v5.4](https://github.com/aelassas/Wexflow/releases/tag/v5.4).
