### ISSUE TITLE
passing variables to workflows

### ISSUE THREAD

**Issue by Busbar2297** [aelassas/Wexflow#73]
I can see that workflows has local variables which their values are set, is it possible to call a workflow and pass the variables through web services?!

I believe it will be a great feature.

**Comment by aelassas** [comment]
No, this feature is not available yet. Maybe in the upcoming version 4.0 that I'm working on.

**Comment by fabionaspolini** [comment]
For me it would also be very useful this feature.

**Comment by aelassas** [comment]
@fabionaspolini @Busbar2297 I added the following method:

**POST** http://localhost:8000/wexflow/startWithVariables

Starts a workflow with variables. You must remove Content-Type header before to run this method.

Here is a sample payload:

```json
{
	"WorkflowId":131,
	"Username":"admin",
	"Password":"ee05eaaba7b76f16e285d983d605c9bf",
	"Variables":[
	  {
		 "Name":"restVar1",
		 "Value":"C:\\WexflowTesting\\file1.txt"
	  },
	  {
		 "Name":"restVar2",
		 "Value":"C:\\WexflowTesting\\file2.txt"
	  }
	]
}
```

Here is a sample workflow:

```xml
<Workflow xmlns="urn:wexflow-schema" id="138" name="Workflow_RestVariables" description="Workflow_RestVariables">
  <Settings>
    <Setting name="launchType" value="trigger" />
    <Setting name="enabled" value="true" />
  </Settings>
  <LocalVariables></LocalVariables>
  <Tasks>
    <Task id="1" name="FilesLoader" description="Loading files" enabled="true">
      <Setting name="file" value="$restVar1" />
      <Setting name="file" value="$restVar2" />
    </Task>
    <Task id="2" name="ListFiles" description="Listing files" enabled="true"></Task>
  </Tasks>
</Workflow>
```

This feature will be available in the upcoming version 4.9. I will notify you once released.

**Comment by fabionaspolini** [comment]
Thank you very much!

**Comment by aelassas** [comment]
@Busbar2297 I've just released the [v4.9](https://github.com/aelassas/Wexflow/releases/tag/v4.9). Check out the new [RESTful API](https://github.com/aelassas/Wexflow/wiki/RESTful-API).

**Comment by SenyaMur** [comment]
How pass files throw REST API and use in workflow?

**Comment by janborup** [comment]
Hi @SenyaMur 
See the section about "Starts a workflow with variables.", in the Restful API, there you can configure files to the workflow.
If you at thinking about files upload, you has to use other method like [FTP](https://github.com/aelassas/Wexflow/wiki/Ftp), to the server.

**Comment by SenyaMur** [comment]
I wanted uplode files using RestFul Api and run workflow. Send FormData with params and files in one request (see example: https://applandeo.com/blog/nancy-net-parsing-multipartform-data-requests/)
But I found outed yo have the BIG problem (see new implement feature https://github.com/aelassas/Wexflow/issues/152). In the Wexflow code all workflow are instances. When you rerun workflow you just mutate workflow instance. It is wrong way.
