### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by Bykiev** [aelassas/Wexflow#74]
Hello,

I'm new to Wexflow, and I have a question about using it. I need to create a document flow designer, because there is no built-in task I need to create my custom task. 

My document flow looks like this:
Create document => Approve it by Person A => assign responsible (Person B) => Person B do it's work => Person A will check the work and close task.

The only question is how can Person A and Person B can be selected from a dropdown list and passed as parameter to Custom Task?

**Comment by aelassas** [comment]
The goal of Wexflow is to automate recurring tasks without user intervention so user-input scenarios are not supported yet. So you can't do what you want in Wexflow now.

**Comment by aelassas** [comment]
@Bykiev Now, Wexflow supports approval workflows. Check out this [example](https://github.com/aelassas/Wexflow/wiki/Samples#form-submission-approval-workflow).

**Comment by aelassas** [comment]
It is now possible to create [approval workflows](https://github.com/aelassas/Wexflow/wiki/Approval-workflows) on generic business objects such as documents, invoices, purchase orders, vacation requests, time sheets, etc. These generic business objects are called records.
