### ISSUE TITLE
Hot folders

### ISSUE THREAD

**Issue by khullarsunil** [aelassas/Wexflow#76]
Discovered WexFlow today!
1) Is there a method to create a hotfolder which will fire a task only when a file arrives in it? Instead of checking it every few seconds
2) I was not able to use wildcard with filesLoader?

**Comment by aelassas** [comment]
1. No, this feature is not available yet.
2. You can use wildcards through regexPattern setting option. Refer to the documentation [here](https://github.com/aelassas/Wexflow/wiki/FilesLoader).

**Comment by aelassas** [comment]
@khullarsunil I added [FileSystemWatcher](https://github.com/aelassas/Wexflow/wiki/FileSystemWatcher) task for both .net and .net core. This task watches a hot folder and triggers tasks on file created, changed or deleted. This task will be available in the v5.5. I will notify you once I will release it.

**Comment by aelassas** [comment]
@khullarsunil It's here! Wexflow 5.5 just released 🎉. It includes [FileSystemWatcher](https://github.com/aelassas/Wexflow/wiki/FileSystemWatcher) task for files monitoring for both .net and .net core. This task watches a hot folder and triggers tasks on file created, changed or deleted.
