### ISSUE TITLE
Request novice instructions - difficult to understand workflow creation.

### ISSUE THREAD

**Issue by burque505** [aelassas/Wexflow#77]
Hello, I've tried to create a simple workflow to run Notepad, thinking "ProcessLauncher" would be absolutely the simplest entry point. I just want to run Notepad - no file saving, no bells and whistles.

No luck so far. 

Upon saving, I get a "success" notification, also a notification that it was loaded. 

Upon hitting "Refresh", the new Workflow does not appear in the Designer or in the Manager.

The Workflow is, I believe, in the correct location:
"C:\Wexflow\Workflows\Workflow_Notepad.xml"

There doesn't seem to be any instruction as to the "nuts and bolts" of creating a new Workflow.
Thanks for your software and your attention to this issue.

[Workflow_Notepad.zip](https://github.com/aelassas/Wexflow/files/2932249/Workflow_Notepad.zip)

**Comment by aelassas** [comment]
You can't run gui processes from Wexflow since the server is hosted on a Windows service for the Windows version. That's why you are not able to run Notepad.

**Comment by aelassas** [comment]
Just use the .net core version. It will work fine for this use case.
