### ISSUE TITLE
run project error

### ISSUE THREAD

**Issue by landonzeng** [aelassas/Wexflow#79]
![QQ截图20190322144027](https://user-images.githubusercontent.com/7336781/54806915-7c056d00-4cb6-11e9-8c8d-ef2e515d67c2.png)
![QQ截图20190322144054](https://user-images.githubusercontent.com/7336781/54806922-80ca2100-4cb6-11e9-933e-0a8e078997c7.png)
After I downloaded the program, I visited http://localhost:8000 after running according to the document, and there was an error in the figure above.

**Comment by datauduong** [comment]
I have the same issue on, I wish the project would have a flow diagram.

**Comment by aelassas** [comment]
Open the backend by opening the web page Backend\index.html on a browser.

To open the backend, go to "Backend" folder and double-click on the file "index.html".

**Comment by landonzeng** [comment]
Thanks!
