### ISSUE TITLE
[Question] Roadmap and Issue Priority for contributions?

### ISSUE THREAD

**Issue by jeffward01** [aelassas/wexflow#8]
# Question

Do you have a list of `Wishlist` / `Backlog` / `Roadmap` features that you would like implemented?  This will be for contributors to review so they know what your priorities are.  

I think it would be very cool to have this, so that people can pick tickets instead of randomly implementing new features that may or may not be in scope of the project.

Thank you!

## Note

Again, I very much admire this app / tool! Its very cool and well made.  I very much appreciate that you used `Xml` compared to the more popular alternative `.yaml` .  As a C# developer, I find `XML` files very comfortable and dislike whitespace so much in `.Yaml` and other whitespaces langues _looks over at python..._  - So I just watnted to thank you agan.

**Comment by aelassas** [comment]
Thanks for your feedback and interest about Wexflow. I opened a [new issue](https://github.com/aelassas/wexflow/issues/9) regarding Wexflow Wishlist and feature requests. Feel free to add your feature requests there.
