### ISSUE TITLE
RestVariable's in Wexflow

### ISSUE THREAD

**Issue by HasanBsone** [aelassas/wexflow#82]
when i am continuously hit restapi i am not getting RestVariables in some api call's.please assist

**Comment by aelassas** [comment]
Issue fixed. I released a patch: [v8.2](https://github.com/aelassas/wexflow/releases/tag/v8.2)

Test it with this new patch and let me know if the issue is fixed on your side as well.

**Comment by HasanBsone** [comment]
Yes Thank's alot issue fixed.
