### ISSUE TITLE
About wf. LaunchType == LaunchType. Cron Setting Up to 10 Executions per 5-second Cycle

### ISSUE THREAD

**Issue by hua350264633** [aelassas/Wexflow#84]
I found that if the scheduler only executed 10 times after the Cron expression was set, it was found that the problem was caused by the absence of Task in the Workflow Job class.
Error code:
`/// <summary>
        /// Executes workflow the job
        /// </summary>
        /// <param name="context">Job context.</param>
        System.Threading.Tasks.Task IJob.Execute(IJobExecutionContext context)
        {
            Workflow workflow = (Workflow)context.JobDetail.JobDataMap.Get("workflow");
            workflow.Start();
            var task = new System.Threading.Tasks.Task(() =>
            {
                //workflow.Start();
            });
            //task.Start();
            return task;
        }`
Correct code:
`/// <summary>
        /// Executes workflow the job
        /// </summary>
        /// <param name="context">Job context.</param>
        System.Threading.Tasks.Task IJob.Execute(IJobExecutionContext context)
        {
            Workflow workflow = (Workflow)context.JobDetail.JobDataMap.Get("workflow");
            //workflow.Start();
            var task = new System.Threading.Tasks.Task(() =>
            {
                workflow.Start();
            });
            task.Start();
            return task;
        }`

**Comment by WangLiFan1993** [comment]
I have also found this problem and have no idea,thank you!

**Comment by hua350264633** [comment]
no problem 




------------------ 原始邮件 ------------------
发件人: "Eric"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 中午11:23
收件人: "aelassas/Wexflow"<Wexflow@noreply.github.com>;
抄送: "暮然回首"<125952481@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [aelassas/Wexflow] About wf. LaunchType == LaunchType. CronSetting Up to 10 Executions per 5-second Cycle (#84)




I have also found this problem and have no idea,thank you!

**Comment by StephenYjw** [comment]
The same to me,thx

**Comment by PeTrProduct** [comment]
This is a fix for LaunchType.Periodic too!

**Comment by buffonlwx** [comment]
The problem has been solved.

**Comment by aelassas** [comment]
I have fixed this issue and commited the fix to master.

**Comment by aelassas** [comment]
I fixed this issue in the new [version 3.9](https://github.com/aelassas/Wexflow/releases/tag/v3.9) that you can download.
