### ISSUE TITLE
Load all files generated by "Process Launcher" in "Select Files"

### ISSUE THREAD

**Issue by youngsmith1** [aelassas/Wexflow#85]
I am using "Process Launcher" task to encode mp4 file to HLS. Task Configuration is

```
<Task id="2" name="ProcessLauncher" description="WAV to MP3" enabled="true">
      <Setting name="selectFiles" value="1" />
      <Setting name="processPath" value="C:\Program Files\ffmpeg\bin\ffmpeg.exe" />
      <Setting name="processCmd" value="-i {$filePath} -profile:v baseline -level 3.0 -s 640x360 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls {$output:$fileNameWithoutExtension.m3u8}" />
      <Setting name="hideGui" value="true" />
      <Setting name="generatesFiles" value="true" />
</Task>
```

Output of this task is multiple .m3u8 and .ts files. Now i am trying to move all these generated files from Temp folder using "Files Mover" task.

```
<Task id="3" name="FilesMover" description="Moving MP3 files from temp folder" enabled="true">
      <Setting name="selectFiles" value="2" />
      <Setting name="destFolder" value="C:\WorkFlowData\12\mp3\" />
</Task>
```

**Problem:**
Only 1st m3u8 is being moved. Rest of the files stay in Temp folder.

**Question:**
How can i move all generated files of process launcher task?

**Comment by youngsmith1** [comment]
Do you need more details from me on this? I can definitely provide more details.

**Comment by aelassas** [comment]
ProcessLauncher task is designed to output only one single file so if your command outputs multiple files, only one file will be selected. That's why only the first m3u8 is being selected and moved and that's why the rest of files stay in temp folder.

If you want to select all the files, I'll have to redesign the ProcessLauncher task so it selects all the files generated in the temp folder. Maybe, I'll add this new feature in the upcomming version 4.0 that I am working on.

**Comment by youngsmith1** [comment]
Yes that will be handy. Ideally select file task should selected all generated files. When we can expect new release?
Also i will be happy to contribute. Do you accept pull requests?

**Comment by aelassas** [comment]
I'm working on the upcoming version 4.0 that I plan to release in August.
Of course, you can contribute if you want to. PRs are very welcome.

**Comment by aelassas** [comment]
@youngsmith1 I implemented the loading of multiple files in ProcessLauncher task. This featue will be available in the upcoming version 4.0 that I plan to release in August.

This is how it works: You just have to add the following settings in ProcessLauncher configuration to load multiple files:
```xml
<Setting name="generatesFiles" value="true" />
<Setting name="loadAllFiles" value="true" />

```

**Comment by aelassas** [comment]
@youngsmith1 I updated the task ProcessLauncher to load multiple files from the temp folder in the [version 4.0](https://github.com/aelassas/Wexflow/releases/tag/v4.0) that I just published.

This is how it works: You just have to add the following settings in ProcessLauncher configuration to load multiple files:

```xml
<Setting name="generatesFiles" value="true" />
<Setting name="loadAllFiles" value="true" />
```
And here is a sample HLS workflow:

```xml
<Workflow xmlns="urn:wexflow-schema" id="118" name="Workflow_ffmpeg_hls" description="Workflow_ffmpeg_hls">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
	</Settings>
	<Tasks>
		<Task id="1" name="FilesLoader" description="Loading MP4 files" enabled="true">
			<Setting name="file" value="C:\WexflowTesting\MP4\small.mp4" />
		</Task>
		<Task id="2" name="ProcessLauncher" description="MP4 to HLS" enabled="true">
			<Setting name="selectFiles" value="1" />
			<Setting name="processPath" value="C:\Program Files\ffmpeg\bin\ffmpeg.exe" /> <!-- You need to install FFMPEG -->
			<Setting name="processCmd" value="-i {$filePath} -profile:v baseline -level 3.0 -s 640x360 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls {$output:$fileNameWithoutExtension.m3u}" /> <!-- variables: {$filePath},{$fileName},{$fileNameWithoutExtension}-->
			<Setting name="hideGui" value="true" /> <!-- true|false -->
			<Setting name="generatesFiles" value="true" /> <!-- true|false -->
			<Setting name="loadAllFiles" value="true" /> <!-- true|false -->
		</Task>
		<Task id="3" name="FilesMover" description="Moving HLS files from temp folder" enabled="true">
			<Setting name="selectFiles" value="2" />
			<Setting name="destFolder" value="C:\WexflowTesting\HLS\" />
			<Setting name="overwrite" value="true" />
		</Task>
	</Tasks>
</Workflow>

```

**Comment by youngsmith1** [comment]
That is so cool, let me test this and i will update you.

**Comment by youngsmith1** [comment]
It is working fine. Thanks
