### ISSUE TITLE
using http sever  in wexflow

### ISSUE THREAD

**Issue by contisummer** [aelassas/wexflow#86]
hello , aelassa :

I want to put a http server(HttpListener Class) on wexflow , which  used for receiving request(JSON format using POST method) from http client on other platform, Where should the http server code  put on wexflow ?  Is it a custom TASK  ?  

Please give me some advice, thank you very much. I have no idea about the wexflow software architecture.

**Comment by aelassas** [comment]
If you want to manage workflows from another platform, you can use Wexflow API: https://github.com/aelassas/wexflow/wiki/RESTful-API

If you want to do something else, use custom tasks.

**Comment by contisummer** [comment]
ok. Thank you.
