### ISSUE TITLE
Difference with BPMN?

### ISSUE THREAD

**Issue by NanFengCheong** [aelassas/Wexflow#9]
Hi,
I was wondering, is it possible to integrate with [BPMN](https://en.wikipedia.org/wiki/Business_Process_Model_and_Notation) ?
Just curious, what are the reasons you decide to implement your own standard?

**Comment by HaMster21** [comment]
BPMN was designed to create a notation for business processes. It describes interactions between entites and when who does what. The goal of wexflow is to automate recuring tasks without user intervention. So neither is Wexflow an implementation similar to BPMN nor do they serve the same purpose.

So, how would you imagine integrating with BPMN? And with which implementation of BPMN? Thers's also no way to model waiting for user input in Wexflow at the moment.

Maybe this will work the other way around someday and workflows of Wexflow could be used to generate BPMN diagrams, but that seems to be a long distance future 😉

**Comment by mike7ang1rdz** [comment]
https://zeebe.io/  
this is much more powerful
