### ISSUE TITLE
index.html 404 page not found

### ISSUE THREAD

**Issue by AdemAygun** [aelassas/Wexflow#90]
Hi,
I tried to install WexFlow .Net Core on windows. I run install.bat and run.bat. But I got error "404 nancy" like this [issue ](https://github.com/aelassas/Wexflow/issues/67#issue-385247443) . I close run.bat and I run on IIS express (backend folder), appeared login page and I fill out user/password but submit button did not work, nothing happened. When I double clicked it's opened file:///D:/.../backend(index.html on browser.

**Comment by aelassas** [comment]
Open the backend by opening the web page Backend\index.html on a browser.

To open the backend, go to "Backend" folder and double-click on the file "index.html".
