### ISSUE TITLE
Can be used for an approval document workflow?

### ISSUE THREAD

**Issue by biapar** [aelassas/Wexflow#92]
Can be used for an approval document workflow?

**Comment by aelassas** [comment]
The goal of Wexflow is to automate recurring tasks without user intervention. Thus, user-input scenarios are not supported yet.

**Comment by aelassas** [comment]
@biapar Now, Wexflow supports approval workflows. Check out this [example](https://github.com/aelassas/Wexflow/wiki/Samples#form-submission-approval-workflow).
