### ISSUE TITLE
 how can I command WexFlow to proceed or start an instance

### ISSUE THREAD

**Issue by MasoudMirzaei** [aelassas/Wexflow#93]
I'm new in using Wexflow,So I looked up WexFlow's documentation for where it describes how can I use WexFlow in my programs but unfortunately I couldn't find it. for example I want to know how can I command WexFlow to proceed or start an instance  of my workflows (for example Booking Hotel Workflow), Sorry to bother you if my question is so silly.but if you don't mind please help me,

**Comment by aelassas** [comment]
Once you created your workflow,  you can set a launchType which is one of the following options:

- startup: The workflow is launched when Wexflow Engine starts.
- trigger: The workflow is launched manually from Wexflow Manager.
- periodic: The workflow is launched periodically.
- cron: The workflow is launched depending on a cron expression.

You can edit the launchType from the designer or from XML.

You can also start your workflow by calling the [RESTful API](https://github.com/aelassas/Wexflow/wiki/RESTful-API):

- Start a workflow (POST): http://localhost:8000/wexflow/start/{id}
