### ISSUE TITLE
Does wexflow provide High Availability

### ISSUE THREAD

**Issue by sathyatvrcbe** [aelassas/Wexflow#94]
I read through the documentation of workflow, I could not find any article or topic which discusses about High Availability of Wexflow.

**Comment by aelassas** [comment]
@sathyatvrcbe  Can you explain more and give some examples?

**Comment by hisubbotin** [comment]
> @sathyatvrcbe Can you explain more and give some examples?
@aelassas Hi, we need workflow engine for cloud solution in kubernates.
Do you have some container images? or helm chart to deploy multipods solution in kubernates ?

**Comment by aelassas** [comment]
@hisubbotin No, I don't have container images but you can create them from the dotnet core packages. You can follow the installation instructions on the wiki.

**Comment by hisubbotin** [comment]
@aelassas 
What approximate level of perfomance do you test? 
For example, simple scenario, 1 repeatable workflow with 10 empty tasks. How many RPS do you test? 
CosmosDB / MongoDB

**Comment by hisubbotin** [comment]
How it will work with millions of workflow runs?

**Comment by aelassas** [comment]
@hisubbotin Wexflow is pretty fast and does not cosume a lot of memory. Wexflow can handle millions of workflow runs without problems.

**Comment by KyleBCox** [comment]
I am happy to look into Containerising the application and i will give some feedback on performance / bottlenecks / availability

**Comment by aelassas** [comment]
@KyleBCox Thank you for your contribution. You can put your feedback in this issue or you can open a new issue and put your feedback there. As you want. You can follow Linux installation instructions [here](https://github.com/aelassas/Wexflow/wiki/Installation#linux). Regarding the backend, you'll need to put /opt/wexflow/Backend/ on a web server. [Here](https://github.com/aelassas/Wexflow/wiki/Usage#installation) are the installation instructions of the backend.

**Comment by bh-adrienne** [comment]
@KyleBCox is there a starter docker file or docker container for wexflow yet?

**Comment by aelassas** [comment]
[Here](https://github.com/aelassas/Wexflow/wiki/Docker) is the documentation for creating Docker images.
