### ISSUE TITLE
Multiple workflows created

### ISSUE THREAD

**Issue by MartinTeefy** [aelassas/wexflow#94]
Duplicate workflows were created when I clicked new workflow and then clicked the XML button in the designer and started writing the XML Tags and Elements, for some reason it appeared to not save the workflow as it wasn't shown in the list of workflows so I added the info again and it created duplicate workflows.

I was using .net core on windows 10 with version 8.3 of Wexflow. The batch DOS window didn't show duplicate workflows until I stopped and restarted the core server then it confirmed the workflows were duplicated in the database.

**Comment by aelassas** [comment]
Issue fixed. I released a new version with a patch: https://github.com/aelassas/wexflow/releases/tag/v8.4

Test with the new version and let me know if this is fixed.
