### ISSUE TITLE
read a specific xml attribute value/ csv column?

### ISSUE THREAD

**Issue by zeusmos** [aelassas/Wexflow#95]
below is the scenario i am trying to see if i can implement a workflow in wexflow. 

- [ ] step1: read specific data from (xml(element or attribute), csv) 

- [ ] step2: 

 - a) send extracted element/attribute value from step1 will be a key to get additional information from X system using an API/WebService. 
 - b) option to send the extracted data to an api/Webservice 

- [ ] step3: update/create the step1 xml with additional attributes(results from step2 (a)) and move it to a folder.

****

**Comment by aelassas** [comment]
Hi,

In step 1, you can use [Xslt](https://github.com/aelassas/Wexflow/wiki/Xslt) and [CsvToXml](https://github.com/aelassas/Wexflow/wiki/CsvToXml) tasks.

In steo 2, you can create your own [custom task](https://github.com/aelassas/Wexflow/wiki/Custom-tasks) that takes as input an XML file containing the extracted element/attribute from step 1  to get additional information from X system using an API/WebService and sends the extracted data to an api/Webservice.

In step 3, you can use  [Xslt](https://github.com/aelassas/Wexflow/wiki/Xslt) task to update/create the XML from step 1 with additional attributes (results from step 2) and [FilesMover](https://github.com/aelassas/Wexflow/wiki/FilesMover) task to move it to a folder.

Kind regards,
Akram.

**Comment by zeusmos** [comment]
Is there anything out of the box than can do without custom task? Can’t the local variable used to store the retrieved xml data to it and use it as step2 a) input param to html get and result from it can be stored in local variable and use the xslt implementation and same input param can be sent to step2 b) html put.

**Comment by aelassas** [comment]
Check out [network tasks](https://github.com/aelassas/Wexflow/wiki/Tasks-documentation#network-tasks) maybe it might help you interacting with the API/WebSerice. But unfortunatly, the only way to pass the information from step1 to step2 is to use a custom task. You can't create a local variable contaning information from step1 on the fly.

**Comment by zeusmos** [comment]
Ok thanks
