### ISSUE TITLE
Custom task mysql database backup and restore failed because of MySql.Data's version

### ISSUE THREAD

**Issue by Yangchunyu01** [aelassas/Wexflow#97]

**Comment by Yangchunyu01** [comment]
related [issue](https://github.com/aelassas/Wexflow/issues/96)
Hello Aelassas:
Following your advice, I got the same error in log file:
![image](https://user-images.githubusercontent.com/28860471/62261195-10db5c80-b447-11e9-87a8-2fe46dcc8a41.png)

**modify part of workflow_sql.xml** as below:
![image](https://user-images.githubusercontent.com/28860471/62261284-51d37100-b447-11e9-8b26-527aacf3be41.png)

Change MySql.Data.dll to original one, there are no error in log file.

I'll try to use MySQL.Data.dll that comes with Wexflow in my custom task.

**Comment by Yangchunyu01** [comment]
After using MySQL.Data.dll that comes with Wexflow and downgrading MySqlBackup.dll to 1.0.0.0, trigger my task, the error is gone

**Comment by aelassas** [comment]
Ok. I'll try to update the version of MySQL.Data.dll in the version 4.1 of Wexflow.
